### ISSUE TITLE
iMessage闪退，Facetime无法登录

### ISSUE THREAD

**Issue by Dragon526** [daliansky/XiaoXinPro-13-hackintosh#100]
型号是小新 pro13 2019独显版本，硬盘型号西数sn730，三星内存，网卡bcm943224pciebt2bx，系统版本big sur 11.2.3，使用的2.23最新的efi，已经替换了三码，但是iMessage依然闪退；Facetime无法登录，提示认证过程错误
<img width="235" alt="截屏2021-03-12 08 15 37" src="https://user-images.githubusercontent.com/55922224/110872668-36129b00-830b-11eb-9d94-6ff79d075a99.png">

**Comment by ClayMoreBoy** [comment]
我facetime可以 iMessage不行

**Comment by M69W** [comment]
这个影响因素有点多，一般与EFI无关。
![image](https://user-images.githubusercontent.com/15809201/111055927-b1b04b80-84b5-11eb-8aa5-4f14949df325.png)
iMessage 正常使用

**Comment by Dragon526** [comment]
> 这个影响因素有点多，一般与EFI无关。
> ![image](https://user-images.githubusercontent.com/15809201/111055927-b1b04b80-84b5-11eb-8aa5-4f14949df325.png)
> iMessage 正常使用

噢噢，谢谢啦，麻烦问下层主的系统是Catalina还是Big Sur呢

**Comment by M69W** [comment]
与系统无关吧

![image](https://user-images.githubusercontent.com/15809201/111072278-d1c32780-8514-11eb-85d6-c8567cd30b4d.png)

**Comment by Dragon526** [comment]
已解决，问题是apple id的原因，具体是什么因素还不太清楚，但是我重新使用之前在ipad上注册的另一个apple id登录imessage后一切正常。感谢各位的回复
