### ISSUE TITLE
v2.3.5 触摸板物理按键失效

### ISSUE THREAD

**Issue by frcc00** [daliansky/XiaoXinPro-13-hackintosh#103]
换回v2.3.4正常

**Comment by stoness2324** [comment]
尝试下reset narvm和重建缓存？
我换到v2.3.5触控板正常

**Comment by M69W** [comment]
@stoness2324 试试触摸板的按键

**Comment by stoness2324** [comment]
@M69W 开机后左右键都正常，睡眠后左键正常右键失效。

**Comment by M69W** [comment]
@frcc00 @stoness2324 
https://github.com/VoodooI2C/VoodooI2C/releases

用回旧的i2c驱动正常吗？

**Comment by ClayMoreBoy** [comment]
没问题 重建缓存试一下 不行就两下 三下

**Comment by stoness2324** [comment]
@M69W 需要我测试v2.6.4的老版本驱动吗？明天我试一试。最近github有点难。

**Comment by Flora-air** [comment]
老版本的驱动是没问题的

**Comment by M69W** [comment]
那就不更新驱动吧

**Comment by stoness2324** [comment]
对我影响不大，我基本上不用实体按键，双指也能替代右键功能，暂时不回滚了

**Comment by M69W** [comment]
习惯用双指和三指拖动

**Comment by cytown** [comment]
我现在触摸板休眠恢复后失效，之前一直用鼠标，今天才发现。不知道reset nvram是否能够修复。。。

**Comment by frcc00** [comment]
VoodooI2C.kext 换回旧版就行了
