### ISSUE TITLE
sn750睡眠耗电大，每小时4%

### ISSUE THREAD

**Issue by FortyPoint** [daliansky/XiaoXinPro-13-hackintosh#104]
sn750睡眠耗电严重，睡眠期间一直保持温热，请问如何解决？是否只能更换硬盘？

**Comment by FortyPoint** [comment]
并且没有使硬盘进入睡眠这个选项
![Uploading 截屏2021-04-01 下午4.22.25.png…]()

**Comment by M69W** [comment]
同sn750, 暂时没有办法
可以换evo 970等固体

**Comment by stoness2324** [comment]
@M69W 我也是750，晚上点了睡眠一晚上能用30%左右电，而且夏天快来了，稍微读写多一点，温度逼近50度，已经在考虑是否需要换970evo了。

**Comment by M69W** [comment]
到这个[issue](https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/110) 讨论吧，同一份话题
