### ISSUE TITLE
2020款i5 oc 0.6.7 安装big sur 11.2.3 (20D91) 合盖后黑屏，按电源键无法唤醒

### ISSUE THREAD

**Issue by nice172** [daliansky/XiaoXinPro-13-hackintosh#106]
大佬们，oc 0.6.7 安装big sur 11.2.3 (20D91) 电源键无法唤醒，怎么搞

**Comment by stoness2324** [comment]
是否重建缓存修复权限，另外hackintool电源选项卡下面有个螺丝刀，点一下效果也不错

**Comment by nice172** [comment]
> 是否重建缓存修复权限，另外hackintool电源选项卡下面有个螺丝刀，点一下效果也不错

这个方法点击多次了，也改过参数

**Comment by M69W** [comment]
之前使用是否正常？
尝试使用最新的 EFI 试试？

**Comment by nice172** [comment]
> 之前使用是否正常？
> 尝试使用最新的 EFI 试试？

换了可以唤醒，不在上班时间内可以唤醒。但是问题 早上8点半上班用到晚上18点下班这么长时间，然后点击锁定屏幕合盖一两小时后唤醒不了。很奇怪

**Comment by hqj12333** [comment]
我也遇到了这个问题 重装了bigsur也没用，用的是最新的oc，怀疑可能和之前安装那个睡眠关闭蓝牙补丁或者和我安装那些合上盖子不睡眠的软件有关 不知道有什么方法可以排除一下呢？会不会跟Hibernatemode设置有关？

**Comment by M69W** [comment]
我那边没有用这些软件或特意设置。
就正常使用EFI而已

**Comment by hqj12333** [comment]
今天发现好像关闭了WiFi之后好像合盖又可以正常睡眠了。网卡我更换的是dw1560，网卡驱动只打了BrcmBluetoothInjector和AirportBrcmFixup，其他参数就和最新的efi一样

**Comment by M69W** [comment]
试试设置一下
```diff
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
+			<key>PciRoot(0x0)/Pci(0x1C,0x0)</key>
+			<dict>
+				<key>pci-aspm-default</key>
+				<data>AgAAAA==</data>
+			</dict>
+			<key>PciRoot(0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)</key>
+			<dict>
+				<key>pci-aspm-default</key>
+				<data>AgEAAA==</data>
+			</dict>
...

```

**Comment by M69W** [comment]
> 试试设置一下
> 
> ```diff
> <key>DeviceProperties</key>
> 	<dict>
> 		<key>Add</key>
> 		<dict>
> +			<key>PciRoot(0x0)/Pci(0x1C,0x0)</key>
> +			<dict>
> +				<key>pci-aspm-default</key>
> +				<data>AgAAAA==</data>
> +			</dict>
> +			<key>PciRoot(0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)</key>
> +			<dict>
> +				<key>pci-aspm-default</key>
> +				<data>AgEAAA==</data>
> +			</dict>
> ...
> ```

最新EFI 已有这部分的设置，
https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI-OC(0.6.8)-PRO13/OC/config.plist#L411-L434

**Comment by hqj12333** [comment]
嗯嗯 我用的就是最新的EFI 就这样关WIFI用吧，也不是很影响使用。感谢大佬的回复🙏🏻

**Comment by M69W** [comment]
手里已经没有DW系列网卡，测试不了
BrcmBluetoothInjector对DW网卡型号是有用的

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
