### ISSUE TITLE
我的设备处无法显示图片

### ISSUE THREAD

**Issue by Dragon526** [daliansky/XiaoXinPro-13-hackintosh#109]
最新的v2.3.6我的设备处无法显示图片，之前的v2.3.3正常
<img width="399" alt="截屏2021-04-07 下午3 28 55" src="https://user-images.githubusercontent.com/55922224/113828148-a7345980-97b6-11eb-8e6b-454a7efba6e6.png">

**Comment by ClayMoreBoy** [comment]
我的早就无法这个显示图片

**Comment by cytown** [comment]
我的没有这个问题。不过我一直用同一套三码。

**Comment by M69W** [comment]
听说是`序列码`不对的导致的
我之前也是显示图片，后面换生成的`序列码`也是无图显示了。
![image](https://user-images.githubusercontent.com/15809201/114267533-cb9a6b00-9a2e-11eb-942c-6e4c582dc366.png)

**Comment by stoness2324** [comment]
一直不能显示。。。

**Comment by Pablolu430** [comment]
我猜是MBP16,2的問題 之前用MBP15,4,Air9,2都有圖 各機型三碼都是自己跟朋友白蘋果產生的(一台a1502,a1278,朋友的iMac)不知道有沒有人用16,2來生成三碼？
我的三碼是按照這製作的
https://mrmad.com.tw/hackintosh-fix-imessage-facetime

**Comment by Dragon526** [comment]
已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑

**Comment by M69W** [comment]
> 已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑

那之前估计是序列码没有改？

**Comment by Dragon526** [comment]
> > 已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑
> 
> 那之前估计是序列码没有改？

之前使用最新的v2.3.6 efi，除三码外未做任何修改，使用occ生成的Macbook16,2的三码，序列号查询显示“未验证购买日期”，说明三码可以用，也换过三四套，图片均无法显示
这次依然使用最新的v2.3.6 efi，修改了usbmap.kext里的机型为15,4 ，使用occ生成的Macbook15,4的三码，序列号查询显示“未验证购买日期”，成功显示图片
这个问题出现在v2.3.4版本及以后，而这个版本之后的机型从15,4改为了16,2 ，不排除是机型平台设置的问题
Ps：不显示图片不影响日常使用，但是强迫症真的很难受QAQ

**Comment by Dragon526** [comment]
> > > 已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑
> > 
> > 
> > 那之前估计是序列码没有改？
> 
> 之前使用最新的v2.3.6 efi，除三码外未做任何修改，使用occ生成的Macbook16,2的三码，序列号查询显示“未验证购买日期”，说明三码可以用，也换过三四套，图片均无法显示
> 这次依然使用最新的v2.3.6 efi，修改了usbmap.kext里的机型为15,4 ，使用occ生成的Macbook15,4的三码，序列号查询显示“未验证购买日期”，成功显示图片
> 这个问题出现在v2.3.4版本及以后，而这个版本之后的机型从15,4改为了16,2 ，不排除是机型平台设置的问题
> Ps：不显示图片不影响日常使用，但是强迫症真的很难受QAQ

同时不排除OCC编辑器的问题，但是同样使用最新的occ 2.33.1.2，机型平台设置为Macbook15,4后生成的三码可以正常显示图片，16,2的却不行，个人未尝试使用其他编辑器

**Comment by Pablolu430** [comment]
> > > > 已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑
> > > 
> > > 
> > > 那之前估计是序列码没有改？
> > 
> > 
> > 之前使用最新的v2.3.6 efi，除三码外未做任何修改，使用occ生成的Macbook16,2的三码，序列号查询显示“未验证购买日期”，说明三码可以用，也换过三四套，图片均无法显示
> > 这次依然使用最新的v2.3.6 efi，修改了usbmap.kext里的机型为15,4 ，使用occ生成的Macbook15,4的三码，序列号查询显示“未验证购买日期”，成功显示图片
> > 这个问题出现在v2.3.4版本及以后，而这个版本之后的机型从15,4改为了16,2 ，不排除是机型平台设置的问题
> > Ps：不显示图片不影响日常使用，但是强迫症真的很难受QAQ
> 
> 同时不排除OCC编辑器的问题，但是同样使用最新的occ 2.33.1.2，机型平台设置为Macbook15,4后生成的三码可以正常显示图片，16,2的却不行，个人未尝试使用其他编辑器

可是降成15,4 i7-10710u就浪費了🤣

**Comment by Dragon526** [comment]
> > > > > 已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑
> > > > 
> > > > 
> > > > 那之前估计是序列码没有改？
> > > 
> > > 
> > > 之前使用最新的v2.3.6 efi，除三码外未做任何修改，使用occ生成的Macbook16,2的三码，序列号查询显示“未验证购买日期”，说明三码可以用，也换过三四套，图片均无法显示
> > > 这次依然使用最新的v2.3.6 efi，修改了usbmap.kext里的机型为15,4 ，使用occ生成的Macbook15,4的三码，序列号查询显示“未验证购买日期”，成功显示图片
> > > 这个问题出现在v2.3.4版本及以后，而这个版本之后的机型从15,4改为了16,2 ，不排除是机型平台设置的问题
> > > Ps：不显示图片不影响日常使用，但是强迫症真的很难受QAQ
> > 
> > 
> > 同时不排除OCC编辑器的问题，但是同样使用最新的occ 2.33.1.2，机型平台设置为Macbook15,4后生成的三码可以正常显示图片，16,2的却不行，个人未尝试使用其他编辑器
> 
> 可是降成15,4 i7-10710u就浪費了🤣

我的是i5-10210u :-D
不去想无法显示的图片就忘了吧，反正也不会影响使用🤣

**Comment by cytown** [comment]
> > > > > 已解决，usbmap和config里修改机型为Macbook15,4后使用最新efi正常显示图片，感谢大家的答疑
> > > > 
> > > > 
> > > > 那之前估计是序列码没有改？
> > > 
> > > 
> > > 之前使用最新的v2.3.6 efi，除三码外未做任何修改，使用occ生成的Macbook16,2的三码，序列号查询显示“未验证购买日期”，说明三码可以用，也换过三四套，图片均无法显示
> > > 这次依然使用最新的v2.3.6 efi，修改了usbmap.kext里的机型为15,4 ，使用occ生成的Macbook15,4的三码，序列号查询显示“未验证购买日期”，成功显示图片
> > > 这个问题出现在v2.3.4版本及以后，而这个版本之后的机型从15,4改为了16,2 ，不排除是机型平台设置的问题
> > > Ps：不显示图片不影响日常使用，但是强迫症真的很难受QAQ
> > 
> > 
> > 同时不排除OCC编辑器的问题，但是同样使用最新的occ 2.33.1.2，机型平台设置为Macbook15,4后生成的三码可以正常显示图片，16,2的却不行，个人未尝试使用其他编辑器
> 
> 可是降成15,4 i7-10710u就浪費了🤣

应该也不会吧，我一直正常用15，4

**Comment by Jarvay** [comment]
应该是图片库里没有16,2的图片，从网页登录查看可以看到图片的地址是这个
https://appleid.cdn-apple.com/static/deviceImages-10.0/MacBookPro/MacBookPro16,2/online-infobox.png
访问是404
把机型换成其他的，比如15,4，大部分都是有的

**Comment by M69W** [comment]
> 应该是图片库里没有16,2的图片，从网页登录查看可以看到图片的地址是这个
> https://appleid.cdn-apple.com/static/deviceImages-10.0/MacBookPro/MacBookPro16,2/online-infobox.png
> 访问是404
> 把机型换成其他的，比如15,4，大部分都是有的

好奇是怎么发现的，
抓包？

**Comment by M69W** [comment]
https://appleid.cdn-apple.com/static/deviceImages-10.0/MacBookPro/MacBookPro16,1/online-infobox.png
16,1有
16,2没有

**Comment by ClayMoreBoy** [comment]
> https://appleid.cdn-apple.com/static/deviceImages-10.0/MacBookPro/MacBookPro16,1/online-infobox.png
> 16,1有
> 16,2没有

原來如此 終於找到問題的根源 重新搖號
