### ISSUE TITLE
你们睡眠每小时耗电多少？如何优化

### ISSUE THREAD

**Issue by FortyPoint** [daliansky/XiaoXinPro-13-hackintosh#110]
我的大概在3%

**Comment by Dragon526** [comment]
一个晚上十个小时大约消耗25%，硬盘是西数的sn730

**Comment by imerdell-55** [comment]
休眠10个小时 18% 原装硬盘亿联的，用了睡眠自动关闭蓝牙和wifi的脚本，听说970evo 比较省电，就是太贵了，

**Comment by M69W** [comment]
有空把群文件的文件去敏再发到这里，
到时不妨参考一下，
每台机子的测试过程可能不太一样

**Comment by M69W** [comment]
有空把群文件的文件去敏再发到这里，
到时不妨参考一下，
每台机子的测试过程可能不太一样

**Comment by bocaikun** [comment]
每小时大概0.7%，硬盘是西数sn550，网卡是94360cs2，用了盒盖自动关Wi-Fi蓝牙脚本，bios关闭独显

**Comment by M69W** [comment]
文档已备份到这里：https://github.com/daliansky/XiaoXinPro-13-hackintosh/tree/master/EFI/Document

## 这份文档的来源有必要说明一下：无他意

群(`946132482`)公告的耗电文档，似乎被人全部删除了？
已经@全体人员后，也已告知所有人。
这里备份的区别：已去掉原本文档出现的 【群昵称、机器SN码】敏感信息。

## PS：
 > 文档出现的网卡不算全面，后面经过测试可用的网卡还有包括：
 > BCM94360Z4、BCM94360CD、BCM943602CDP

**Comment by stoness2324** [comment]
并不是特别依赖睡眠，晚上一般都关机，大部分使用环境都有电源插头。
但还是测试了一下，sn750，网卡94360z4，一晚上6小时睡眠，耗电约为23%。
@M69W 电子表格下载了无法打开，是我个人网络问题吗？

**Comment by M69W** [comment]
> 并不是特别依赖睡眠，晚上一般都关机，大部分使用环境都有电源插头。
> 但还是测试了一下，sn750，网卡94360z4，一晚上6小时睡眠，耗电约为23%。
> @M69W 电子表格下载了无法打开，是我个人网络问题吗？

xls是用wps编辑过的，不知道是不是兼容问题，
回头看看

**Comment by cytown** [comment]
mode3 和mode0耗电上区别不大，目前应该都是1%-2%之间。

**Comment by chenjiangui** [comment]
小新不支持纯休眠吗, windows下是支持的.  多久都不掉电, 相当于关机.  唤醒速度比较慢, 但是我对唤醒速度没要求, 只想晚上扔包里不掉电

**Comment by cytown** [comment]
> 小新不支持纯休眠吗, windows下是支持的. 多久都不掉电, 相当于关机. 唤醒速度比较慢, 但是我对唤醒速度没要求, 只想晚上扔包里不掉电

这也是我想要达到的，目前来看不行。。。几十年前linux和windows就实现了的功能。

**Comment by surill** [comment]
> mode3 和mode0耗电上区别不大，目前应该都是1%-2%之间。

0和3都试了一下，没啥区别，n750一晚上30%左右，不知道直接改成hibernatemode 25会发生什么

**Comment by cytown** [comment]
> > mode3 和mode0耗电上区别不大，目前应该都是1%-2%之间。
> 
> 0和3都试了一下，没啥区别，n750一晚上30%左右，不知道直接改成hibernatemode 25会发生什么

会无法启动，或者说自动重启。

**Comment by M69W** [comment]
换一个好点硬盘

**Comment by cytown** [comment]
最新发现mode3还是会有睡死情况，换回mode0。。。

**Comment by Pablolu430** [comment]
奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣
<img width="1440" alt="截圖 2021-04-22 17 55 03" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png">
<img width="1440" alt="截圖 2021-04-22 17 55 47" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">

**Comment by surill** [comment]
> 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣
> <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png">
> <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">

因为懒得关机想要合盖就走，又担心第二天需要用的时候电量不足

**Comment by chenjiangui** [comment]
> 休眠10个小时 18% 原装硬盘亿联的，用了睡眠自动关闭蓝牙和wifi的脚本，听说970evo 比较省电，就是太贵了，

睡眠自动关闭蓝牙和wifi有教程吗

**Comment by Pablolu430** [comment]
> > 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣
> > <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png">
> > <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">
> 
> 因为懒得关机想要合盖就走，又担心第二天需要用的时候电量不足

我那20小時沒關機...所以才從100掉到88%

**Comment by surill** [comment]
> > > 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣
> > > <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png">
> > > <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">
> > 
> > 
> > 因为懒得关机想要合盖就走，又担心第二天需要用的时候电量不足
> 
> 我那20小時沒關機...所以才從100掉到88%

我一晚上（大约10小时）掉电接近30%.……
请问你是什么配置，硬盘是什么型号，有特殊设置什么吗

**Comment by M69W** [comment]
目前耗电最明显就是不同的硬盘
比如说sn750<>970evo

**Comment by Pablolu430** [comment]
> > > > 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣
> > > > <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png">
> > > > <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">
> > > 
> > > 
> > > 因为懒得关机想要合盖就走，又担心第二天需要用的时候电量不足
> > 
> > 
> > 我那20小時沒關機...所以才從100掉到88%
> 
> 我一晚上（大约10小时）掉电接近30%.……
> 请问你是什么配置，硬盘是什么型号，有特殊设置什么吗

<img width="1440" alt="截圖 2021-04-23 16 55 26" src="https://user-images.githubusercontent.com/49023418/115846829-e0c2c100-a454-11eb-9eb5-642d29cb56c2.png">
這是今天的 中間空白依舊是昨晚九點左右蓋上剛剛打開後按了兩下電源鍵喚醒
i7/mx350去年618買的 網卡是換1560 ssd是970pro（這是關鍵？

**Comment by surill** [comment]
> 這是今天的 中間空白依舊是昨晚九點左右蓋上剛剛打開後按了兩下電源鍵喚醒 i7/mx350去年618買的 網卡是換1560 ssd是970pro（這是關鍵？ 換970pro純粹是mlc情懷😂

正如大佬所说，睡眠耗电这个锅，可能就得SN750来背了……
重点是我一开始买的SN550，然后看到这里有朋友说连续坏了好几块，吓得我赶紧退货换了750，万万没想到竟然在这里翻车了……

**Comment by Pablolu430** [comment]
> > 這是今天的 中間空白依舊是昨晚九點左右蓋上剛剛打開後按了兩下電源鍵喚醒 i7/mx350去年618買的 網卡是換1560 ssd是970pro（這是關鍵？ 換970pro純粹是mlc情懷😂
> 
> 正如大佬所说，睡眠耗电这个锅，可能就得SN750来背了……
> 重点是我一开始买的SN550，然后看到这里有朋友说连续坏了好几块，吓得我赶紧退货换了750，万万没想到竟然在这里翻车了……

再退換970pro 省事還能享受最後一款民用mlc（？😂

**Comment by chenjiangui** [comment]
> > 這是今天的 中間空白依舊是昨晚九點左右蓋上剛剛打開後按了兩下電源鍵喚醒 i7/mx350去年618買的 網卡是換1560 ssd是970pro（這是關鍵？ 換970pro純粹是mlc情懷😂
> 
> 正如大佬所说，睡眠耗电这个锅，可能就得SN750来背了……
> 重点是我一开始买的SN550，然后看到这里有朋友说连续坏了好几块，吓得我赶紧退货换了750，万万没想到竟然在这里翻车了……

nvmeFix.kext不知道有没有用, 增强对非苹果ssd兼容性的, 看到对待机功耗有优化

**Comment by surill** [comment]
> nvmeFix.kext不知道有没有用, 增强对非苹果ssd兼容性的, 看到对待机功耗有优化

小白不知道怎么搞，大佬先给试试水😂

**Comment by surill** [comment]
> nvmeFix.kext不知道有没有用, 增强对非苹果ssd兼容性的, 看到对待机功耗有优化

试了一下，使用nvmefix.kext 1.0.6版本，待机两次发现功耗没有改观，平均每小时2%
![截屏2021-04-26 09 24 13](https://user-images.githubusercontent.com/75652673/116017094-3b386900-a671-11eb-918c-bdcb1c9887f1.png)
<img width="607" alt="截屏2021-04-26 09 24 28" src="https://user-images.githubusercontent.com/75652673/116017099-3e335980-a671-11eb-8f43-d9904abc501d.png">

**Comment by stoness2324** [comment]
@surill 哎，这个睡眠怕是难了

**Comment by surill** [comment]
比较奇怪的一个现象，为什么短时间的睡眠耗电量要比长时间睡眠的耗电量低呢？
<img width="901" alt="截屏2021-05-09 10 56 11" src="https://user-images.githubusercontent.com/75652673/117559134-59f91f80-b0b5-11eb-9fa5-f90a20b00f88.png">

**Comment by cytown** [comment]
> 比较奇怪的一个现象，为什么短时间的睡眠耗电量要比长时间睡眠的耗电量低呢？
> <img alt="截屏2021-05-09 10 56 11" width="901" src="https://user-images.githubusercontent.com/75652673/117559134-59f91f80-b0b5-11eb-9fa5-f90a20b00f88.png">

很正常，电池是通过电压来判断电量的，通常电池满电时电压下降曲线比较低，所以你会在待机1小时左右看到电量100%的情况也会出现，所以，至少待机8-10小时以上才有参考意义。

**Comment by xiaobai403** [comment]
是硬盘的问题。我之前用sn750的时候，待机平均是3%~4%。但是换了970evo之后，待机耗电稳定在1.2%

**Comment by Sun1090** [comment]
正常，人不在电脑旁边就关机呗

**Comment by arloan** [comment]
昨天又测试了一下，sn550 1TB，睡眠前手动关闭蓝牙wifi，满电14个多小时剩20%，每小时耗电5.5%。 😭
![image](https://user-images.githubusercontent.com/1157026/154786786-7efe85ac-2341-437f-8008-54ed8d5290d8.png)

**Comment by frozenzero123** [comment]
> 昨天又测试了一下，sn550 1TB，睡眠前手动关闭蓝牙wifi，满电14个多小时剩20%，每小时耗电5.5%。 😭
> ![image](https://user-images.githubusercontent.com/1157026/154786786-7efe85ac-2341-437f-8008-54ed8d5290d8.png)

哇比我的金士顿a2000还厉害我的是3～4%

**Comment by arloan** [comment]
我也尝试了nvmefix，结果睡眠耗电还更高了点，从5.x%增加到了6.x%。卸载掉了。

> > nvmeFix.kext不知道有没有用, 增强对非苹果ssd兼容性的, 看到对待机功耗有优化
> 
> 试了一下，使用nvmefix.kext 1.0.6版本，待机两次发现功耗没有改观，平均每小时2% ![截屏2021-04-26 09 24 13](https://user-images.githubusercontent.com/75652673/116017094-3b386900-a671-11eb-918c-bdcb1c9887f1.png) <img alt="截屏2021-04-26 09 24 28" width="607" src="https://user-images.githubusercontent.com/75652673/116017099-3e335980-a671-11eb-8f43-d9904abc501d.png">

**Comment by BronzedOreo** [comment]
> 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣 <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png"> <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">

大佬，你这个截屏的分辨率是2880*1800，这个分辨率是开启好HiDPI了吗，为什么分辨率有这么高呢？请教一下怎么弄这个分辨率的

**Comment by M69W** [comment]
> > 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣 <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png"> <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">
> 
> 大佬，你这个截屏的分辨率是2880*1800，这个分辨率是开启好HiDPI了吗，为什么分辨率有这么高呢？请教一下怎么弄这个分辨率的

https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/HiDPi

**Comment by BronzedOreo** [comment]
> > > 奇怪...為什麼大家一直糾結電量問題 我卻不覺得有啥耗電的...🤣 <img alt="截圖 2021-04-22 17 55 03" width="1440" src="https://user-images.githubusercontent.com/49023418/115695282-3daa7280-a394-11eb-9a52-8081e63ea27f.png"> <img alt="截圖 2021-04-22 17 55 47" width="1440" src="https://user-images.githubusercontent.com/49023418/115695319-4602ad80-a394-11eb-8b20-d66359ea6334.png">
> > 
> > 
> > 大佬，你这个截屏的分辨率是2880*1800，这个分辨率是开启好HiDPI了吗，为什么分辨率有这么高呢？请教一下怎么弄这个分辨率的
> 
> https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/HiDPi

这个hidpi开不了2880*1800呀

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
