### ISSUE TITLE
电池没有在充电

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#111]
小白照着教程终于一步一步鼓捣好了，单硬盘单系Big sur，目前问题
1、偶尔花瓶，合上盖子再打开一般就好了
2、电池无法充电：
    （1）状态栏电池图标显示“电池没有在充电”
    （2）设置--电池--中显示“正在充电61%”
用百度的方法……shift+ctrl+alt+电源键重置SMC之后出现的花屏，之前（今天以前，我昨天刚装好= =）没有出现过
请大神帮忙看看
<img width="665" alt="截屏2021-04-17 13 55 13" src="https://user-images.githubusercontent.com/75652673/115103483-cb492500-9f84-11eb-9775-3a75099978f5.png">
<img width="1015" alt="截屏2021-04-17 13 52 58" src="https://user-images.githubusercontent.com/75652673/115103485-cf754280-9f84-11eb-8d5a-e22c9eb365d5.png">
<img width="655" alt="截屏2021-04-17 13 56 37" src="https://user-images.githubusercontent.com/75652673/115103488-d0a66f80-9f84-11eb-9a81-c4d71431bc91.png">

**Comment by M69W** [comment]
是不是在Windows上设置了电池充电模式？

**Comment by surill** [comment]
> 是不是在Windows上设置了电池充电模式？

之前在windows里面，是有用Lenovo vantage设置了充电阈值（就是一个图标，打开不会充满）
可是我电脑上已经没有win10了……咋整

**Comment by surill** [comment]
引导使用EFI-OC(0.6.8)-PRO13

**Comment by surill** [comment]
大佬们，刚刚把电池放电到60%以下，重新插上电源，充电正常。
感谢，打扰！
<img width="373" alt="WX20210417-151957@2x" src="https://user-images.githubusercontent.com/75652673/115105278-7f03e200-9f90-11eb-97a7-714c92becea6.png">

**Comment by surill** [comment]
还是有问题……充电至60%以上就又不再充电了，没法充满

**Comment by surill** [comment]
不知道是不是因为之前在windows中用Lenovo vantage设置了电池充电阈值导致的，明天恢复windows把这个关上试一下

**Comment by M69W** [comment]
> 不知道是不是因为之前在windows中用Lenovo vantage设置了电池充电阈值导致的，明天恢复windows把这个关上试一下

如果不想装系统，
可以拆机把电池排线拔了再插回去就行了
就是不方便，也不建议。
PS：经常拆机发现的

**Comment by surill** [comment]
> > 不知道是不是因为之前在windows中用Lenovo vantage设置了电池充电阈值导致的，明天恢复windows把这个关上试一下
> 
> 如果不想装系统，
> 可以拆机把电池排线拔了再插回去就行了
> 就是不方便，也不建议。
> PS：经常拆机发现的

大佬确定吗，如果可以我就拔电池排线了，因为我恢复win10也是拆机把原来的硬盘装回去，反正都是拆

**Comment by surill** [comment]
> > 不知道是不是因为之前在windows中用Lenovo vantage设置了电池充电阈值导致的，明天恢复windows把这个关上试一下
> 
> 如果不想装系统，
> 可以拆机把电池排线拔了再插回去就行了
> 就是不方便，也不建议。
> PS：经常拆机发现的

大佬确定吗，如果可以我就拔电池排线了，因为我恢复win10也是拆机把原来的硬盘装回去，反正都是拆

**Comment by surill** [comment]
> > 不知道是不是因为之前在windows中用Lenovo vantage设置了电池充电阈值导致的，明天恢复windows把这个关上试一下
> 
> 如果不想装系统，
> 可以拆机把电池排线拔了再插回去就行了
> 就是不方便，也不建议。
> PS：经常拆机发现的
感谢大佬！把电池排线拔下再插上，电池可以正常充电了！！！
<img width="303" alt="截屏2021-04-18 16 38 07" src="https://user-images.githubusercontent.com/75652673/115139436-78df3580-a064-11eb-801f-5d24c55ae184.png">

**Comment by Silvdawn** [comment]
![02C2A2CE90D568A25EBB38067071D4C4](https://user-images.githubusercontent.com/87458369/171617584-a649e77a-cc11-41ab-8742-7ddee2d2de91.jpg)
更新BIOS貌似可以解决充不上电的问题，至少目前我没问题了（我之前的问题是必须放电后才能充电。充满后拔掉充电器，使用电池供电后再插上就充不进电了）
