### ISSUE TITLE
优化电池充电功能是否可用？

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#113]
大佬们，优化电池充电功能是否正常可用，我打开了，但是只要接上电源，电池就一直是保持充满的状态的，感觉没有起作用。
<img width="780" alt="截屏2021-04-22 16 44 28" src="https://user-images.githubusercontent.com/75652673/115684556-0931b900-a38a-11eb-8786-10a9f1b0c076.png">
<img width="346" alt="截屏2021-04-22 16 44 34" src="https://user-images.githubusercontent.com/75652673/115684598-0f279a00-a38a-11eb-98bd-1bc8eb2e2134.png">

**Comment by ClayMoreBoy** [comment]
> 大佬们，优化电池充电功能是否正常可用，我打开了，但是只要接上电源，电池就一直是保持充满的状态的，感觉没有起作用。
> <img alt="截屏2021-04-22 16 44 28" width="780" src="https://user-images.githubusercontent.com/75652673/115684556-0931b900-a38a-11eb-8786-10a9f1b0c076.png">
> <img alt="截屏2021-04-22 16 44 34" width="346" src="https://user-images.githubusercontent.com/75652673/115684598-0f279a00-a38a-11eb-98bd-1bc8eb2e2134.png">

你的不出現維修 傳一份到這裏

**Comment by surill** [comment]
> 你的不出現維修 傳一份到這裏

目前电池健康94%，你需要什么？
<img width="251" alt="截屏2021-04-24 18 53 05" src="https://user-images.githubusercontent.com/75652673/115956411-1936cd80-a52f-11eb-8187-cbdefe9413e1.png">

**Comment by jiangbeilaodao** [comment]
<img width="171" alt="image" src="https://user-images.githubusercontent.com/44474235/115957960-db8a7280-a537-11eb-8b11-f14c618dd972.png">

**Comment by surill** [comment]
@jiangbeilaodao 可以正常充电到100%吗，我之前也是充到60%就停了，后来按照W69M大佬的办法才能正常充满。但是感觉优化电池充电的功能并没有起作用。

**Comment by ClayMoreBoy** [comment]
> > 你的不出現維修 傳一份到這裏
> 
> 目前电池健康94%，你需要什么？
> <img alt="截屏2021-04-24 18 53 05" width="251" src="https://user-images.githubusercontent.com/75652673/115956411-1936cd80-a52f-11eb-8187-cbdefe9413e1.png">

efi 對比一下

**Comment by surill** [comment]
@ClayMoreBoy 请查收
[EFI.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6373667/EFI.zip)

**Comment by jiangbeilaodao** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/44474235/116017358-f6610200-a671-11eb-8ce3-061fa3e0f31f.png">
yogasmc conservation mode开关可以控制@surill

**Comment by cytown** [comment]
> <img alt="image" width="780" src="https://user-images.githubusercontent.com/44474235/116017358-f6610200-a671-11eb-8ce3-061fa3e0f31f.png">
> 
> yogasmc conservation mode开关可以控制@surill

这个支持小新pro？ https://github.com/zhen-zen/YogaSMC 是这里下载的吧？

**Comment by jiangbeilaodao** [comment]
@surill 是的，开启电池养护模式

**Comment by surill** [comment]
> 这个支持小新pro？ https://github.com/zhen-zen/YogaSMC 是这里下载的吧？

你先试一下，哈哈哈 @cytown

**Comment by cytown** [comment]
> > 这个支持小新pro？ https://github.com/zhen-zen/YogaSMC 是这里下载的吧？
> 
> 你先试一下，哈哈哈 @cytown

![image](https://user-images.githubusercontent.com/148625/116179563-2a0f5b00-a74a-11eb-9ebb-054c23623569.png)

貌似不识别啊。

**Comment by surill** [comment]
@jiangbeilaodao 老哥出来看看怎么回事
