### ISSUE TITLE
盒盖后外接显示屏问题

### ISSUE THREAD

**Issue by tomichen** [daliansky/XiaoXinPro-13-hackintosh#114]
在家办公的时候，使用Type-C转HDMI外接显示器，而且键盘和鼠标也外接了，但是在外接电源的情况下笔记本盒盖后就黑屏了（可能睡眠了，不清楚），外接显示器也无法点亮，不知道是什么原因，请大佬们赐教。另外，我用的版本是v2.3.4正式版，自己添加了相应的三码，其他为更改，电源适配器选项里面只勾选了第一个“当显示器关闭时，防止电脑自动进入睡眠”。

**Comment by M69W** [comment]
尝试接上电源🔌？

**Comment by sowhat4999** [comment]
> 尝试接上电源🔌？

我在问题反馈的时候已经说了：“但是在外接电源的情况下笔记本盒盖后就黑屏了”😂

**Comment by M69W** [comment]
没有外接显示器，无法测试

**Comment by surill** [comment]
@sowhat4999 试了一下，外接显示器盒盖后外接显示器黑屏一下，然后正常显示主桌面。
显示器是DELL P2419HC，使用Type-c连接（同时作为电源，这款显示器可输出65W）
![截屏2021-04-26 18 20 35](https://user-images.githubusercontent.com/75652673/116067849-22a17080-a6bc-11eb-93b6-027124642887.png)

**Comment by surill** [comment]
开盖盒盖显示都很正常，哎就是玩，你说气人不气人

![截屏2021-04-26 18 22 03](https://user-images.githubusercontent.com/75652673/116068021-51b7e200-a6bc-11eb-93f0-24afe919c72c.png)

**Comment by cytown** [comment]
> @sowhat4999 试了一下，外接显示器盒盖后外接显示器黑屏一下，然后正常显示主桌面。
> 显示器是DELL P2419HC，使用Type-c连接（同时作为电源，这款显示器可输出65W）
> ![截屏2021-04-26 18 20 35](https://user-images.githubusercontent.com/75652673/116067849-22a17080-a6bc-11eb-93b6-027124642887.png)

这样是正常的啊，mbp就是这样的。

**Comment by sowhat4999** [comment]
我现在只能是在盒盖的情况下重新插拔下外接Type-C电源才可以唤醒外接显示器作为主显示器，不知道什么情况，外接显示器是用的Panda 24寸 2K可旋转显示屏。

**Comment by stoness2324** [comment]
@cytown 请问你用的哪款拓展捂？能够在转换出的hdmi接口下输出4k 60吗？
我这个hdmi只能4k 30。

**Comment by cytown** [comment]
> @cytown 请问你用的哪款拓展捂？能够在转换出的hdmi接口下输出4k 60吗？
> 我这个hdmi只能4k 30。

汗，我没有4k显示器测试。。。就是很普通的转换接口。

**Comment by Pablolu430** [comment]
說到外接顯示器...大家有推薦的擴展塢嗎...能4k60p+pd充電的 我這款設計有問題... 

![IMG_3370](https://user-images.githubusercontent.com/49023418/116230469-4337fc00-a78a-11eb-911b-431b382349ca.png)
![IMG_3362](https://user-images.githubusercontent.com/49023418/116230485-46cb8300-a78a-11eb-81ce-afbc73799a2a.png)
如果只插其中之一 都正常 
![only 1](https://user-images.githubusercontent.com/49023418/116230996-e557e400-a78a-11eb-8b62-bc7d585096af.png)
![only 2](https://user-images.githubusercontent.com/49023418/116231084-03254900-a78b-11eb-901e-4089a6adcb59.jpg)
兩個都插
![both](https://user-images.githubusercontent.com/49023418/116231346-50091f80-a78b-11eb-83cf-bab99ca15899.png)
卻不能充電...

**Comment by stoness2324** [comment]
@Pablolu430 还是选个品牌的价格稍微贵点的比较好，不知道你那边能不用狗东，可以买来试用，不合适的退款。
我这个绿联的转换器，hdmi下始终只能4k30，过段时间我准备换成带DP输出的了。

**Comment by stoness2324** [comment]
@cytown 哎，头大，我怀疑是hdmi达不到4k60，要用dp。后续我再测试一下

**Comment by Pablolu430** [comment]
> @Pablolu430 还是选个品牌的价格稍微贵点的比较好，不知道你那边能不用狗东，可以买来试用，不合适的退款。
> 我这个绿联的转换器，hdmi下始终只能4k30，过段时间我准备换成带DP输出的了。

狗東有是有 不過跟大陸的狗東物流不太一樣（大陸段狗東 入境後新竹物流）感覺要退貨會有點麻煩哈哈 不過有推薦什麼品牌的擴展塢嗎 我喜歡這種可以併在一起的 看起來一體感比較好 （anker就沒有...）

**Comment by q944093** [comment]
http://m.feng.com/detail/post/11677019 
照着这个修改一下显示器文件试试，我的外接屏盒盖之前也遇到问题了，虽然现象不太一样但用这个方法修复好了

**Comment by S15932807676** [comment]
我是绿联拓展+HDMI接口，可以盒盖显示呀，就是不知道盒盖会不会影响散热

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/130338501-9e6f89d4-77d6-4fd0-9083-f2e48104ec88.png)

**Comment by M69W** [comment]
https://support.apple.com/zh-cn/HT202351

> 连接显示器
将显示器连接到电源，然后将显示器连接到 Mac。检查 Mac 上的端口，并确认需不需要转换器。

> 如果您将外置键盘和鼠标与 Mac 笔记本电脑搭配使用，则可以在连接外置显示器后关闭内建显示屏。您可能需要按下某个按键或点按鼠标才能唤醒外置显示器。

> 如果外置显示器在连接到 Mac 后没有开启，请在您的 Mac 处于关机状态时连接显示器，然后将 Mac 唤醒或开机。

**Comment by surill** [comment]
> https://support.apple.com/zh-cn/HT202351
> 
> > 连接显示器
> > 将显示器连接到电源，然后将显示器连接到 Mac。检查 Mac 上的端口，并确认需不需要转换器。
> 
> > 如果您将外置键盘和鼠标与 Mac 笔记本电脑搭配使用，则可以在连接外置显示器后关闭内建显示屏。您可能需要按下某个按键或点按鼠标才能唤醒外置显示器。
> 
> > 如果外置显示器在连接到 Mac 后没有开启，请在您的 Mac 处于关机状态时连接显示器，然后将 Mac 唤醒或开机。

请问在盒盖只用外接显示器的情况下，睡眠了还能用电源键正常唤醒吗
我盒盖用外接显示器，一旦睡眠，无法点按电源键环境，只有开盖才能唤醒
