### ISSUE TITLE
BCM943602CS Wifi无法驱动

### ISSUE THREAD

**Issue by Jacky2** [daliansky/XiaoXinPro-13-hackintosh#116]
小新pro 13 2020 i7 10710U （AX201网卡换成 BCM943602CS），在windows10 下wifi和蓝牙都可以驱动，使用该EFI无法找到wifi设备，不知道是不是驱动冲突了？这种情况有没有办法排查？

**Comment by Dragon526** [comment]
occ里添加快照，新增的驱动里面去除包含4360的驱动和其他多余的驱动就可以了

**Comment by M69W** [comment]
发一下使用的EFI ？或者 config.plist

**Comment by Jacky2** [comment]
@M69W 试过两个release版本 ，XiaoXinPro-13-hackintosh v2.3.6 和 XiaoXinPro-13-hackintosh v2.3.5
XiaoXinPro-13-hackintosh v2.3.5 下载的是没有网卡驱动的版本 EFI-OC.0.6.8.-PRO13-no-network-drivers.zip  , 系统报告中会显示 wifi的版本，但添加网络时没有wifi接口可选，只有一个蓝牙网络可添加

**Comment by Jacky2** [comment]
@Dragon526 按理说我用了 XiaoXinPro-13-hackintosh v2.3.5 版本中没有网卡驱动的版本 EFI-OC.0.6.8.-PRO13-no-network-drivers.zip  应该不带4360驱动了，就是不是config.plist有没有相关的一些配置有影响到wifi驱动的。

**Comment by M69W** [comment]
猜测是网络设置那里等问题，试试 设置里面的 Wi-Fi 删除，在手动添加回去试试

**Comment by Jacky2** [comment]
@M69W 试过了，系统报告wifi可以看到版本号，但是网络设置里面没有wifi接口，添加时也没有wifi选项

**Comment by Jacky2** [comment]
@M69W 
![WechatIMG119](https://user-images.githubusercontent.com/23411395/117000724-1d739f80-ad14-11eb-838e-9968c138ce82.jpeg)
![WechatIMG120](https://user-images.githubusercontent.com/23411395/117000750-24021700-ad14-11eb-8f77-6e8d79ca7b7b.jpeg)
![WechatIMG121](https://user-images.githubusercontent.com/23411395/117000765-26fd0780-ad14-11eb-9a52-b931d8c263a7.jpeg)

**Comment by M69W** [comment]
看看config.plist

**Comment by Jacky2** [comment]
@M69W 

[config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6421431/config.plist.zip)

**Comment by M69W** [comment]
> @M69W
> 
> [config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6421431/config.plist.zip)

文档目测没问题.



试试[重置网络](https://docs.oiw.workers.dev/itlwm/Troubleshooting.html#resetting-system-preferences-network)？

1.打开系统偏好设置→网络，删除所有端口，单击右下角的应用
2.打开终端，运行：
```
open /Library/Preferences/SystemConfiguration
```
3.然后删除
```
com.apple.airport.preferences.plist
preferences.plist
NetworkInterfaces.plist
com.apple.network.identification.plist
com.apple.wifi.message-tracer.plist
```
并且所有包含的文件 `enX`（`X`以整数表示）
如果以前已更改过`SMBIOS`，则还必须删除名称包含当前和先前型号的文件。

4.重启

**Comment by Jacky2** [comment]
@M69W 重置试了一下，还是一样，很奇怪，我重装系统也是不行的

**Comment by M69W** [comment]
看看是不是网卡屏蔽有问题

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/%E7%99%BD%E6%9E%9C%E6%8B%86%E6%9C%BA%E7%BD%91%E5%8D%A1

**Comment by Jacky2** [comment]
@M69W  试了一下，确实是的。现在可以了谢谢！！！
