### ISSUE TITLE
u盘启动正常，efi放入硬盘就启动不了了，换回u盘启动又一切正常

### ISSUE THREAD

**Issue by brucedu1342** [daliansky/XiaoXinPro-13-hackintosh#119]
用的方法是复制到硬盘后后esayuefi改引导
之前3.3.2正常，最近试了3.3.5-3.3.7。
EPS盘300m
硬盘970evo

**Comment by M69W** [comment]
操作问题

**Comment by brucedu1342** [comment]
> 操作问题

老大请问我哪里做错了…

**Comment by M69W** [comment]
![设置引导](https://user-images.githubusercontent.com/15809201/118370684-6dd3e280-b5db-11eb-93f5-13d8f2de84dc.gif)

[BOOTICEx64.exe.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6487734/BOOTICEx64.exe.zip)
我这边是用 BOOTICEx64.exe 设置的，大概操作如上面gif 所示

**Comment by brucedu1342** [comment]
> ![设置引导](https://user-images.githubusercontent.com/15809201/118370684-6dd3e280-b5db-11eb-93f5-13d8f2de84dc.gif)
> 
> [BOOTICEx64.exe.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6487734/BOOTICEx64.exe.zip)
> 我这边是用 BOOTICEx64.exe 设置的，大概操作如上面gif 所示
我用了你的方法，第一次进入成功，重启一次入上图
![FB54C7AD-47D6-4F4D-9B8F-51E6C6B5F03B](https://user-images.githubusercontent.com/72108211/118371320-733b2800-b5ef-11eb-8960-588a8c7459c2.jpeg)

**Comment by M69W** [comment]
尝试重启几下

实在不行就换EFI

**Comment by M69W** [comment]
日志貌似是硬盘分区有错误？

**Comment by brucedu1342** [comment]
> 日志貌似是硬盘分区有错误？

我估计是的，因为之前换硬盘是直接用的克隆硬盘，估计是eps分区被我玩坏了？

**Comment by surill** [comment]
我也遇到过这个问题，应该就是ESP分区的问题

**Comment by brucedu1342** [comment]
> 我也遇到过这个问题，应该就是ESP分区的问题

请问你最后怎么解决的

**Comment by surill** [comment]
我是刚开始安装的时候，用新的硬盘安装后无法从硬盘引导，必须u盘才可以。后来把原来硬盘的esp分区整个复制到新分区，然后再把ego复制过去才解决

发自我的iPhone

**Comment by M69W** [comment]
如果是ESP分区问题，重新新建ESP分区即可

**Comment by brucedu1342** [comment]
> 如果是ESP分区问题，重新新建ESP分区即可

我重试了一次，还是不行，请问esp重建需要注意什么，例如扇页512还是多少，我觉得我设置错误

**Comment by lookwi** [comment]
> > 如果是ESP分区问题，重新新建ESP分区即可
> 
> 我重试了一次，还是不行，请问esp重建需要注意什么，例如扇页512还是多少，我觉得我设置错误

理论上diskgenius 默认就没问题呀

**Comment by surill** [comment]
我用新硬盘安装黑苹果单系统的时候，用DG默认分一个ESP分区，然后把EFI文件复制进去也是不能引导，只能用U盘
搞了很久都不行，最后把原win硬盘的esp分区中的文件全部复制过去（尤其是根目录里的boot文件夹）之后再替换EFI才解决

<img width="457" alt="image" src="https://user-images.githubusercontent.com/75652673/119597919-8e3e4100-be14-11eb-9f63-fb01608a6d8c.png">

**Comment by chengyinghaoswat** [comment]
这种情况其实是硬盘的问题，我也买过一个硬盘，有一点问题
我用我的sn750什么事情都没有，换了另外一个硬盘，就只能从u盘启动
安装也能正常安装就是使用不了，启动就坚决启动不了
