### ISSUE TITLE
oc 0.7.0 ，dw1820a 开不了机

### ISSUE THREAD

**Issue by ctwillson** [daliansky/XiaoXinPro-13-hackintosh#120]
系统：mac os 11.3.1
网卡：
- 1820a 不做修改无法完成开机
- 更换ax201，airportitlwn 无法开机，itlwn 可以开机，但是Wi-Fi列表为空

**Comment by surill** [comment]
请问你是从0.6.8升级过来的吗，兄弟们有没有升级的教程
现在是OC-0.6.8  V2.3.6
怎么升级成OC-0.7 V2.3.7

**Comment by lookwi** [comment]
> 请问你是从0.6.8升级过来的吗，兄弟们有没有升级的教程
> 现在是OC-0.6.8 V2.3.6
> 怎么升级成OC-0.7 V2.3.7

没有，我想升级，还是停留在v2.3.5

**Comment by surill** [comment]
@M69W 大佬，能指导一下如何升级吗，是否可以直接把2.3.7中的文件直接替换目前的efi

**Comment by Dragon526** [comment]
可以呀，升级的话直接替换oc文件夹里的文件就可以了，但是序列号啥的最好不要变

**Comment by lookwi** [comment]
> 可以呀，升级的话直接替换oc文件夹里的文件就可以了，但是序列号啥的最好不要变

序列号备份，要对着往里面加

**Comment by Pablolu430** [comment]
> > 可以呀，升级的话直接替换oc文件夹里的文件就可以了，但是序列号啥的最好不要变
> 
> 序列号备份，要对着往里面加
序列號不是用MacSerialTransporter移轉就好了嗎😂

**Comment by ctwillson** [comment]
> 请问你是从0.6.8升级过来的吗，兄弟们有没有升级的教程
> 现在是OC-0.6.8 V2.3.6
> 怎么升级成OC-0.7 V2.3.7

挂载EFI分区然后直接替换。最后把当前使用的OC全部备份以防新OC开不了机

**Comment by M69W** [comment]
试试屏蔽网卡，能进系统吗

**Comment by lookwi** [comment]
> > > 可以呀，升级的话直接替换oc文件夹里的文件就可以了，但是序列号啥的最好不要变
> > 
> > 
> > 序列号备份，要对着往里面加
> 
> 序列號不是用MacSerialTransporter移轉就好了嗎😂

会丢的[狗头]

**Comment by M69W** [comment]
尝试开 -v 看下报错

**Comment by lookwi** [comment]
> 请问你是从0.6.8升级过来的吗，兄弟们有没有升级的教程
> 现在是OC-0.6.8 V2.3.6
> 怎么升级成OC-0.7 V2.3.7

已成功升级到0.7.0 
所有一切正常

**Comment by surill** [comment]
> > 请问你是从0.6.8升级过来的吗，兄弟们有没有升级的教程
> > 现在是OC-0.6.8 V2.3.6
> > 怎么升级成OC-0.7 V2.3.7
> 
> 已成功升级到0.7.0
> 所有一切正常

老兄，怎么升级的，可否介绍一下具体操作？
我现在是把2.3.7的config.plist中机型序列号等信息，照着之前的config改好；其他的用最新的efi文件
不知道这样是不是就可以了，一直没敢替换引导文件

**Comment by lookwi** [comment]
直接下载新版本的2.3.7EFI
使用 MacSerialTransporter 转移三码
加网卡注入
重建缓存后重启电脑

**Comment by lookwi** [comment]
> > > 请问你是从0.6.8升级过来的吗，兄弟们有没有升级的教程
> > > 现在是OC-0.6.8 V2.3.6
> > > 怎么升级成OC-0.7 V2.3.7
> > 
> > 
> > 已成功升级到0.7.0
> > 所有一切正常
> 
> 老兄，怎么升级的，可否介绍一下具体操作？
> 我现在是把2.3.7的config.plist中机型序列号等信息，照着之前的config改好；其他的用最新的efi文件
> 不知道这样是不是就可以了，一直没敢替换引导文件

直接下载新版本的2.3.7EFI
使用 MacSerialTransporter 转移三码
加网卡注入
重建缓存后重启电脑

**Comment by M69W** [comment]
如果是网卡问题，
试试先在BIOS里禁用，
安装完后再开启
