### ISSUE TITLE
DW1820A网卡，用airpods不稳定

### ISSUE THREAD

**Issue by niming175** [daliansky/XiaoXinPro-13-hackintosh#122]
### 情况说明
1、网卡是DW1820A， 屏蔽了针脚
2、efi用版本是`XiaoXinPro-13-hackintosh v2.3.6`
3、在上网的情况下，用airport听音乐不稳定，声音出现断断续续， 不上网的话还好

### 网卡信息
![image](https://user-images.githubusercontent.com/26159724/119253212-bf372f80-bbe2-11eb-9f54-15f464b9a24d.png)

**Comment by M69W** [comment]
估计同时用的是2.4G WiFi，
可以用5G WiFi 试试

**Comment by lookwi** [comment]
建议换新版本驱动试试，我用的新版连接的5G，2,.4也没啥问题

**Comment by niming175** [comment]
> 估计同时用的是2.4G WiFi，
> 可以用5G WiFi 试试

没有5G wifi环境

**Comment by M69W** [comment]
那这个问题应该无法避免

**Comment by M69W** [comment]
如果对蓝牙有要求，不妨试试以下网卡：
BCM94360Z4
BCM94360CD
BCM943602CDP
