### ISSUE TITLE
触摸板使用一段时间后失灵

### ISSUE THREAD

**Issue by ZW-L** [daliansky/XiaoXinPro-13-hackintosh#124]
自从抛弃无线鼠标，重度使用触摸板后，发现触摸板经常会在使用一段时间后失灵，无法使用其他按键激活，只有重启后才正常。

以前轻度使用触摸板的时候，未遇到过触摸板失灵，但我是外接键鼠使用的。我想会不会是不是使用内置键盘时热键冲突导致触摸板失灵？抑或是某些驱动原因？

另外，我使用的是 CLOVER 引导。

**Comment by M69W** [comment]
可以提供一下使用的EFI?

**Comment by ZW-L** [comment]
@M69W 谢谢，刚发现我用的还是去年3月份的EFI，i2c驱动版本是 2.3，我更新驱动试试还有没有问题。

**Comment by ZW-L** [comment]
Reset NVRAM，使用几天触摸板没有失灵的问题，应该是解决了。
