### ISSUE TITLE
更新macOS12以后声音挂了。1820A蓝牙也挂了，开机显卡驱动加载时特别慢。

### ISSUE THREAD

**Issue by HongxuanJiang** [daliansky/XiaoXinPro-13-hackintosh#125]
用的是最新的efi，OC7.0那个版本。

**Comment by HongxuanJiang** [comment]
亮度也不能调了。

**Comment by M69W** [comment]
暂时没有升级到12，
试试最新的[v2.3.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.3.8)?

**Comment by M69W** [comment]
蓝牙问题，可以关注这个 [pull](https://github.com/acidanthera/BrcmPatchRAM/pull/12)

**Comment by HongxuanJiang** [comment]
更新0.71即可
