### ISSUE TITLE
Big Sur 11.2.3可以在线升级吗

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#129]
大佬们，安装的Big Sur 11.2.3，可以在线升级吗
为何检查不到更新？
EFI已更新至最新的V2.3.9
<img width="780" alt="截屏2021-07-28 13 37 57" src="https://user-images.githubusercontent.com/75652673/127271554-2bf03eec-712b-422f-bd9d-599d7ffeebf7.png">
<img width="780" alt="截屏2021-07-28 13 38 01" src="https://user-images.githubusercontent.com/75652673/127271578-5fb8884b-316c-4e4f-88c6-5929490cd7e7.png">

**Comment by surill** [comment]
> 没问题，已经更新了
> <img alt="截屏2021-07-28 下午9 27 30" width="661" src="https://user-images.githubusercontent.com/55922224/127330449-73368e5b-c8f4-4d04-b6c6-5d9b7d4c18fa.png">

为啥我的检查不到更新，大佬知道问题可能出在哪里吗 @M69W @Dragon526

**Comment by surill** [comment]
网上看到了一个方法：
在App Store中搜索macOS Big Sur并点击获取，会跳转到系统偏好设置就能查看到更新了

但是好像下载了一个12G的完整big sur 11.5，不知道这样是更新，还是全新安装？
![Uploading 截屏2021-07-29 00.46.49.png…]()

**Comment by surill** [comment]
网上看到了一个方法：
在App Store中搜索macOS Big Sur并点击获取，会跳转到系统偏好设置就能查看到更新了

但是好像下载了一个12G的完整big sur 11.5，不知道这样是更新，还是全新安装？
<img width="912" alt="截屏2021-07-29 00 46 49" src="https://user-images.githubusercontent.com/75652673/127363326-fda3a278-c8e4-4c22-b966-14bb02410c30.png">

**Comment by surill** [comment]
用上面的方法安装了，是在原来的系统升级，不是重新安装，文件、设置都还保留

**Comment by M69W** [comment]
可以覆盖安装，
就是下载完整包略大
