### ISSUE TITLE
关于Big Sur开机的小问题

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#130]
前几天更新了V2.3.9，然后又将Big Sur从11.2.3升级到11.5.1，开机遇到问题：
1、之前开机：显示小新LOGO——>显示白苹果+进度条——>显示登录界面——>输入密码进入桌面
2、现在开机：显示小新LOGO——>显示白苹果——>显示登录界面——>输入密码——>显示白苹果+进度条——>进入桌面

什么情况……大家有没有遇到的？？？

**Comment by Kevin3256** [comment]
安全与隐私，文件保险箱停用

**Comment by surill** [comment]
关闭文件保险箱后恢复
之前没注意开启还是关闭，难道是更新系统后自动开启了吗
