### ISSUE TITLE
Flickering Screen 

### ISSUE THREAD

**Issue by GiveGreen** [daliansky/XiaoXinPro-13-hackintosh#131]
Hello,

Thankyou for for the amazing EFI!

After 2 minutes in the recovery my screen starts flickering. Any idea why this is happening?

I have a Lenovo s540 13IML which i think is the same as XiaoXin Pro 13.

I turned off the GeForce MX350 in the BIOS.
CPU: i7 10510U
Intel UHD Graphics 620

![FC6B54B5-A68B-4FD7-8A83-D339F2529B2F](https://user-images.githubusercontent.com/23339013/127785196-db91410f-79b9-4357-95ee-969588a35638.jpeg)

**Comment by M69W** [comment]
```<key>AAPL,ig-platform-id</key>
<data>BQCmPg==</data>
```
for example, change the data as `0x12345678`
after finished, change it back, backup your config.plist before change.

https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/16
