### ISSUE TITLE
关于 Apple Music 无损音乐播放的问题

### ISSUE THREAD

**Issue by baolong24** [daliansky/XiaoXinPro-13-hackintosh#133]
升级到 macOS 11.4 后发现 Apple Music 并不能正常播放无损音乐。
打开无损音乐后在播放支持无损音乐内容时会自动下一曲，无法播放。

是黑苹果都有这个问题吗？

**Comment by Flora-air** [comment]
我已经升级到了macOS11.5.1 选择无损确实会出现这个问题

**Comment by DrKoschei** [comment]
插外放也没用，难道对外放也有特殊要求了？

**Comment by LitCcc** [comment]
同样的问题，不知道是哪里出问题了
