### ISSUE TITLE
OC-0.7.2-20210807最新的EFI显示OC版本是0.6.0

### ISSUE THREAD

**Issue by Flora-air** [daliansky/XiaoXinPro-13-hackintosh#134]
使用的是小兵8月7日发的最新的0.7.2的OC引导
<img width="254" alt="截屏2021-08-08 下午6 05 53" src="https://user-images.githubusercontent.com/62434508/128628341-995189f0-f430-4566-abf1-46de25c7a1f1.png">

但是在hackintool里面显示的却是0.6.0的引导
<img width="650" alt="截屏2021-08-08 下午6 02 12" src="https://user-images.githubusercontent.com/62434508/128628234-69f9d2f7-4f21-4848-9435-9ef9a38eacb9.png">

**Comment by M69W** [comment]
有可能是缓存。

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/128634548-e8584b34-71f2-469c-b039-c7d2da682313.png)
