### ISSUE TITLE
大佬们会一直更新Clover版本吗

### ISSUE THREAD

**Issue by ruigemen** [daliansky/XiaoXinPro-13-hackintosh#135]

**Comment by M69W** [comment]
目前这个版本能用吗？
[v2.4.1](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.4.1)

**Comment by ruigemen** [comment]
> 目前这个版本能用吗？
> [v2.4.1](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.4.1)

目前这个版本我的 BigSur 11.5.1完美使用

**Comment by M69W** [comment]
Clover 的更新相对比较简单。
把ACPI 照搬，config.plist  正常情况下不用改。

https://github.com/CloverHackyColor/CloverBootloader/releases
