### ISSUE TITLE
2.3.9启动登录后偶尔出现屏幕不亮的问题

### ISSUE THREAD

**Issue by swieer** [daliansky/XiaoXinPro-13-hackintosh#136]
2.3.9启动登录后偶尔出现屏幕不亮的问题，大概有三成概率，只能手动强制重启，不知是个例还是有bug

**Comment by Silvdawn** [comment]
不是个例，我有时也会出现这个问题，我觉得应该是显卡驱动没有加载的问题，其实系统已经进去了，只是屏幕不亮

**Comment by q944093** [comment]
好像从某个版本EFI开始就遇到这个问题，读条到一半时候直接黑屏，但是系统正常加载，等两分钟左右屏幕会自动恢复。
当我使用外接屏时候发现黑屏现象只针对笔记本内屏。

**Comment by M69W** [comment]
i7 貌似没遇到此现象。

**Comment by swieer** [comment]
> i7 貌似没遇到此现象。

我的就是i7，OC升级到0.7.2，efi升级到3.0.0要好一些，继续观察

**Comment by q944093** [comment]
可能是WEG新版本和某些补丁不兼容导致，我降级使用1.4.3的WEG之后暂时还没有复现过，可以尝试。

**Comment by S15932807676** [comment]
i5用了几个月目前还没遇到过

**Comment by M69W** [comment]
尝试一下 最新 的 [EFI](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases)

**Comment by Silvdawn** [comment]
最新版目前应该是解决了这个问题，忘了说，之前版本我把AAPL,ig-platform-id修改为00009B3E，登录后偶尔出现屏幕不亮的问题，但解决了花屏的问题
最新版未修改，目前没有任何问题，不闪屏不黑屏。
非常感谢大佬🙏

**Comment by Silvdawn** [comment]
AAPL,ig-platform-id修改为00009B3E，可以解决大部分开机花屏的现象；添加启动参数 -igfxblr 可解决此id开机灰屏的现象（大概，修改后使用至今未灰屏）
