### ISSUE TITLE
合上盖子后自自动唤醒了

### ISSUE THREAD

**Issue by Treeisu** [daliansky/XiaoXinPro-13-hackintosh#140]
这两天不知道干了啥，小新无法睡眠了。盒盖后，十几秒，又能听到被唤醒的声音，打开盖子发现，屏幕是亮的（没有从暗到亮的过程，说明直接被唤醒了）。左上角点击睡眠也没有用

**Comment by M69W** [comment]
之前正常？
中间动了哪里？

**Comment by Treeisu** [comment]
> 之前正常？
> 中间动了哪里？



> 之前正常？
> 中间动了哪里？

替换了了0.7.2的efi 加了个cpufriend驱动 其他也没有干啥

**Comment by M69W** [comment]
`log show --last 1d | grep "Wake reason"`
看看

**Comment by Treeisu** [comment]
> `log show --last 1d | grep "Wake reason"`
> 看看

<img width="585" alt="image" src="https://user-images.githubusercontent.com/25004717/129561964-1da8e046-392f-44e2-93ee-a6e674117f4e.png">

**Comment by M69W** [comment]
为什么是问题？


我的是这样
![image](https://user-images.githubusercontent.com/15809201/129575815-46418976-7550-4de2-b388-944bf35d3ef7.png)

**Comment by cytown** [comment]
不确定是不是一样原因： https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/42

**Comment by cytown** [comment]
我碰到的是有时8个小时就耗电100%，应该类似这样的情况。。。但我把所有的唤醒都关了。

**Comment by Treeisu** [comment]
> 我碰到的是有时8个小时就耗电100%，应该类似这样的情况。。。但我把所有的唤醒都关了。

你是不是开了cpu friend；我上次是由于这个导致的。就是一直没有睡眠

**Comment by cytown** [comment]
> > 我碰到的是有时8个小时就耗电100%，应该类似这样的情况。。。但我把所有的唤醒都关了。
> 
> 你是不是开了cpu friend；我上次是由于这个导致的。就是一直没有睡眠

没有，这个是0.7.2，也就是3.0.0的，只加了网卡和三码。
