### ISSUE TITLE
v3.0.0 i5处理器开机花屏

### ISSUE THREAD

**Issue by DrKoschei** [daliansky/XiaoXinPro-13-hackintosh#142]
建议的三个id用了也不行，有用i5的伙伴吗？

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/130087939-359f7a74-aabf-40d1-baa1-bc1fc0dafe25.png)

**Comment by surill** [comment]
我是在刚安装系统、升级系统、升级OC的第一次开机会花屏，但是以后就没有出现过了（或者说小概率会出现，概率小到我感觉没花过）

**Comment by M69W** [comment]
是的，这些几乎有出现一会儿，然后消失。

**Comment by q944093** [comment]
> 是的，这些几乎有出现一会儿，然后消失。

为什么我开机之后很大概率会花屏，一会正常一会又花的那种，但只要睡眠过一次就不会再花了？

**Comment by brandbao** [comment]
> 建议的三个id用了也不行，有用i5的伙伴吗？

我也是花屏，不定时的，大概十来分钟给我来一下，然后合上笔记本再打开，就好了
系统catalina，硬件是2020版i5，当然我现在只用了一个id，AAPL,ig-platform-id 设为 0500A63E，其他两个id我不知道是啥，所以不知道怎么试

**Comment by MatyTanQ** [comment]
v3.0.0 -v开机之后也花 外接显示器开了hidpi

**Comment by xiaobai403** [comment]
换显卡id，wiki里面有。

**Comment by DrKoschei** [comment]
> 换显卡id，wiki里面有。

都试过了，而且wiki里是针对i7的

**Comment by M69W** [comment]
没有针对，只是参考。
因为只有i7的机子。

找很早以前宪武的EFI 参考一下，
他机子是i5的

**Comment by DrKoschei** [comment]
> 没有针对，只是参考。
> 因为只有i7的机子。
> 
> 找很早以前宪武的EFI 参考一下，
> 他机子是i5的

使用宪武EFI里找到的00009B3E, 9B3E0000这组后，出现了更为严重的花屏，无法解决，只能换回原来的了

**Comment by xiaobai403** [comment]
> 没有针对，只是参考。
> 因为只有i7的机子。
> 
> 找很早以前宪武的EFI 参考一下，
> 他机子是i5的

你是i5的吗？i5的你可以看一下你是不是仿冒CPU了。i5的可以不用仿冒CPU直接进系统的。换显卡id以后在resetNvram试试呢

**Comment by DrKoschei** [comment]
> > 没有针对，只是参考。
> > 因为只有i7的机子。
> > 找很早以前宪武的EFI 参考一下，
> > 他机子是i5的
> 
> 你是i5的吗？i5的你可以看一下你是不是仿冒CPU了。i5的可以不用仿冒CPU直接进系统的。换显卡id以后在resetNvram试试呢

我把仿冒CPU的代码清空了，重启后系统概览里显示i7；另外，宪武的显卡ID在降低分辨率（低于默认，已开启HIDPI）后可以正常使用，而设置为默认分辨率后开机必然花屏。

**Comment by q944093** [comment]
> > > 没有针对，只是参考。
> > > 因为只有i7的机子。
> > > 找很早以前宪武的EFI 参考一下，
> > > 他机子是i5的
> > 
> > 
> > 你是i5的吗？i5的你可以看一下你是不是仿冒CPU了。i5的可以不用仿冒CPU直接进系统的。换显卡id以后在resetNvram试试呢
> 
> 我把仿冒CPU的代码清空了，重启后系统概览里显示i7；另外，宪武的显卡ID在降低分辨率（低于默认，已开启HIDPI）后可以正常使用，而设置为默认分辨率后开机必然花屏。

花屏目前应该没有根本的解决方法，这是由于开启hidpi导致的，但是只要睡眠一次之后就肯定再也不会出现花屏现象。

**Comment by S15932807676** [comment]
同i5，用的bigsur间歇性花屏，只好换成Catalina了

**Comment by xiaobai403** [comment]
> > > > 没有针对，只是参考。
> > > > 因为只有i7的机子。
> > > > 找很早以前宪武的EFI 参考一下，
> > > > 他机子是i5的
> > > 
> > > 
> > > 你是i5的吗？i5的你可以看一下你是不是仿冒CPU了。i5的可以不用仿冒CPU直接进系统的。换显卡id以后在resetNvram试试呢
> > 
> > 
> > 我把仿冒CPU的代码清空了，重启后系统概览里显示i7；另外，宪武的显卡ID在降低分辨率（低于默认，已开启HIDPI）后可以正常使用，而设置为默认分辨率后开机必然花屏。
> 
> 花屏目前应该没有根本的解决方法，这是由于开启hidpi导致的，但是只要睡眠一次之后就肯定再也不会出现花屏现象。

我的是19款的，i5处理器。在未仿冒CPU的情况下，使用`0400A53E `和`A53E0004`后，并未出现花屏现象（开机闪一下不算），分辨率是1440*900。

**Comment by M69W** [comment]
没必要，肯定是哪里设置不对

**Comment by xiaobai403** [comment]
> > > > 没有针对，只是参考。
> > > > 因为只有i7的机子。
> > > > 找很早以前宪武的EFI 参考一下，
> > > > 他机子是i5的
> > > 
> > > 
> > > 你是i5的吗？i5的你可以看一下你是不是仿冒CPU了。i5的可以不用仿冒CPU直接进系统的。换显卡id以后在resetNvram试试呢
> > 
> > 
> > 我把仿冒CPU的代码清空了，重启后系统概览里显示i7；另外，宪武的显卡ID在降低分辨率（低于默认，已开启HIDPI）后可以正常使用，而设置为默认分辨率后开机必然花屏。
> 
> 花屏目前应该没有根本的解决方法，这是由于开启hidpi导致的，但是只要睡眠一次之后就肯定再也不会出现花屏现象。

你开hidpi的分辨率是多少

**Comment by q944093** [comment]
> 你开hidpi的分辨率是多少

我是i7处理器，内屏1440*900，外接4K显示器默认hidpi，开机之后内屏有概率花屏，试过了那三个ID都花屏，不过睡眠一次就好了，平时不关机所以影响不大。

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/HiDPi
试试这个Wiki ？

**Comment by DrKoschei** [comment]
http

> https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/HiDPi
> 试试这个Wiki ？

00009B3E这个我试过，相当不好用，默认分辨率下开机必然花屏，得调小分辨率，之后甚至出现了冻屏的现象。我还是用EFI默认的吧。
