### ISSUE TITLE
cann't  boot with latest OC 

### ISSUE THREAD

**Issue by qimingxingyuliyang** [daliansky/XiaoXinPro-13-hackintosh#143]
I can boot Macos by Clover but  latest OC 7.2 (https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases)

err info show as follow screenshots
![image](https://user-images.githubusercontent.com/20723740/130212400-4f319e56-df73-47ea-adb2-2a96ded0e8af.png)

![image](https://user-images.githubusercontent.com/20723740/130212418-4e6e370e-b421-4c83-a240-b17772e88092.png)

Thank you first

**Comment by M69W** [comment]
try Reset NVRAM and set OC boot again?

**Comment by qimingxingyuliyang** [comment]
yes, I. have tried  this many times

**Comment by M69W** [comment]
you need to [set DVMT、CFG Lock](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/DVMT%E8%A1%A5%E4%B8%81#%E6%B5%8B%E8%AF%95%E7%89%88bios) if you install macOS first time.

**Comment by Treeisu** [comment]
不知道你俩干嘛用英文对话

**Comment by M69W** [comment]
try a same language as a rule if we can.

**Comment by qimingxingyuliyang** [comment]
> 不知道你俩干嘛用英文对话
我也不知道 ，突然脑子一抽，不过有好处外国人可以搜到

**Comment by qimingxingyuliyang** [comment]
> try a same language as a rule if we can.

sorry reply too late。The OS can boot the way you said, although it still has exactly the same error,reference the screenshot above
