### ISSUE TITLE
合盖外接4k显示器，鼠标移动时迟滞感很强

### ISSUE THREAD

**Issue by musicyy** [daliansky/XiaoXinPro-13-hackintosh#145]
请问：
1.是否支持外接4k显示器
2.是否为核显带不动4k显示器

**Comment by musicyy** [comment]
是垃圾倍思扩展坞的问题，打扰了。。

**Comment by FINatiend** [comment]
> 是垃圾倍思扩展坞的问题，打扰了。。

有好用的拓展坞的话可以推荐下😁

**Comment by musicyy** [comment]
> > 是垃圾倍思扩展坞的问题，打扰了。。
> 
> 有好用的拓展坞的话可以推荐下😁

放弃了，最终用Type-C转HDMI线解决，买了两款扩展坞都不能激活60hz刷新率。

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/69#issuecomment-903193093

手里刚好有便携屏， C2C一线通搞定
