### ISSUE TITLE
关于系统语言（俄文）的问题

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#147]
同志们，当初黑苹果安装系统的时候，安装界面是俄文的，连蒙带猜的安装完之后把语言和地区改成了简体中文
但是还是有些地方有残留的俄文，大家知道是什么问题吗
<img width="160" alt="WechatIMG30976" src="https://user-images.githubusercontent.com/75652673/131650757-28ac70de-eab7-491b-8f09-b48cf4b0df21.png">

**Comment by Dragon526** [comment]
直接删除就可以了

**Comment by surill** [comment]
> 直接删除就可以了
已经删除了
<img width="780" alt="截屏2021-09-02 10 51 47" src="https://user-images.githubusercontent.com/75652673/131773882-552db569-85d7-4fb6-b134-d22970651582.png">

**Comment by FINatiend** [comment]
安装或者进入Recovery时显示俄文的解决方法

OpenCore配置文件中修改：

NVRAM -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> prev-lang:kbd，输入：7a682d48 616e733a 323532

或者直接清空 prev-lang:kbd的值
来源：https://blog.daliansky.net/Common-problems-and-solutions-in-macOS-BigSur-11.0-installation.html
另外我之前通过终端输入命令sudo languagesetup  然后按照屏幕提示首先输入自己账户的密码； 再输入相应的系统语言代码也解决这个问题了

**Comment by FINatiend** [comment]
但是我进入recovery会一直闪屏，也没有办法通过recovery使用时间机器

**Comment by M69W** [comment]
> 但是我进入recovery会一直闪屏，也没有办法通过recovery使用时间机器

可以临时把这个data值改为系统无法识别的值
```
<key>AAPL,ig-platform-id</key>
<data>BQCmPg==</data>
```
