### ISSUE TITLE
v3.0.0 wifi 非常吊诡的问题

### ISSUE THREAD

**Issue by brandbao** [daliansky/XiaoXinPro-13-hackintosh#148]
硬件：小新pro13 2020版，i5-10210U，无线网卡AX201
系统：Catalina

1. 制作启动盘的无线驱动用的AirportItlwm.kext，安装过程需要使用wifi，很正常
2. 安装完毕进入系统后没有Wi-Fi，则出妖怪了，在系统偏好设置中都找不到Wi-Fi，更谈不上wi-fi列表，关于本机下的Wi-Fi只有软件版本，没有接口
3. 后将驱动切换到itlwm.kext，wifi可以使用，但是在关于本机下的Wi-Fi仍然只有软件版本，没有接口

其中试过将SecureBootModel切换为Default，然后系统就无法启动了。
百思不得其解。

听人说AirportItlwm.kext要放在intel的蓝牙.kext之前？
稍后我再试试这个行不行。

**Comment by M69W** [comment]
[AX201(AX200) 的使用教程](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/Intel%E7%BD%91%E5%8D%A1)

**Comment by brandbao** [comment]
> [AX201(AX200) 的使用教程](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/Intel%E7%BD%91%E5%8D%A1)

这个我非常仔细的读过，只是最后一段不知道该如何实践

我只会用proper来修改config.plist，这里提到的修改部分，不知道Force放在哪一个位置。
是否是用opencore configure程序来编辑？

如果上述方法不管用，还原对 DmgLoading 和 SecureBootModel 的修改，然后强制加载 IO80211Family。打开 /EFI/OC/config.plist 并更改以下代码：
<key>Force</key>
<array>
	<dict>
		<key>Arch</key>
		<string>Any</string>
		<key>BundlePath</key>
		<string>System/Library/Extensions/corecapture.kext</string>
		<key>Comment</key>
		<string></string>
		<key>Enabled</key>

**Comment by jiangbeilaodao** [comment]
Catalina OC0.7.2 AirportItlwm.kext SecureBootModel 设置为 **j137**

**Comment by brandbao** [comment]
> Catalina OC0.7.2 AirportItlwm.kext SecureBootModel 设置为 **j137**

请问j137是啥，直接填写j137？
这个字段一般填default或者disabled吧

**Comment by brandbao** [comment]
> Catalina OC0.7.2 SecureBootModel 设置为 **j137**

明白你所说的了，对于MacBooPro15,4 那就是应该填写j213了，谢谢，我试试
j213 — MacBookPro15,4 (July 2019) Minimum macOS 10.14.5

**Comment by qimingxingyuliyang** [comment]
建议用 open configer 工具配置，然后把 AirportItlwm.kext 放在上面

**Comment by qimingxingyuliyang** [comment]
![1630639545033](https://user-images.githubusercontent.com/20723740/131946360-886b5635-a69b-4070-87b1-18e684d13820.jpg)
补上截图，记得勾选启用

**Comment by brandbao** [comment]
> Catalina OC0.7.2 SecureBootModel 设置为 **j137**

确实如你所说，搞定了，非常感谢

**Comment by brandbao** [comment]
> 建议用 open configer 工具配置，然后把 AirportItlwm.kext 放在上面

谢谢，我也看到有人这么说，但是我没来及去试一下
但是根据上面朋友的指点，改SecureBootModel也能解决这个问题。
