### ISSUE TITLE
音频默认输出是耳机

### ISSUE THREAD

**Issue by YongyuJiang** [daliansky/XiaoXinPro-13-hackintosh#15]
更新了最新的efi版本后，每次开机的默认音频输出是耳机，每次都要手动改成内置扬声器，这个要怎么调呢

**Comment by M69W** [comment]
尝试：声卡ID改成`0b000000`

**Comment by M69W** [comment]
> 尝试：声卡ID改成`0b000000`

声卡：新增layout-id:100，手动切换输入与输出节点，以解决无法驱动Intel SST DMIC内麦所带来的一系列问题
ID改为99是自动切换,默认内置扬声器

**Comment by YongyuJiang** [comment]
我100和99都试了，没有变化，感觉两者是一样的

**Comment by YongyuJiang** [comment]
声卡改成0b000000在哪里改，我刚接触不是很清楚

**Comment by Hush-vv** [comment]
> 声卡改成0b000000在哪里改，我刚接触不是很清楚

DeviceProperties-Add-PciRoot(0x0)/Pci(0x1f,0x3)-layout-id

**Comment by M69W** [comment]
> > 声卡改成0b000000在哪里改，我刚接触不是很清楚
> 
> DeviceProperties-Add-PciRoot(0x0)/Pci(0x1f,0x3)-layout-id

楼上@Hush-vv 有说到了


具体情况，可以看下这个[commit](https://github.com/daliansky/XiaoXinPro-13-hackintosh/commit/1087b3bef02d17c6b43b9b4b91a0614b82a6c1b8) .

**Comment by tangzuzhang** [comment]
改为100后的出现的情况是：
输出：默认为外接扬声器
输入：默认内置麦克风
正好与说明的相反。。。

**Comment by kakaliyan** [comment]
上面修改不成功的是因为clover引导参数里有一个alcid=100，设备属性的修改被这个盖掉了；需要把它修改为99或删除后去设备属性处修改99

**Comment by nekomiao123** [comment]
所以是改声卡id呢还是改layout-id好用啊

**Comment by ifaswind** [comment]
我将 alcid 改为 11 就好了，目前没发现什么不对。
pro13 2020 intel i7 wd

**Comment by cytown** [comment]
我的也是alcid=100，现象是内置输出使用一会儿就关闭，应该是自动改成外置输出吧。。。
