### ISSUE TITLE
U盘启动盘制作失败。。。。。。

### ISSUE THREAD

**Issue by semiknown** [daliansky/XiaoXinPro-13-hackintosh#150]
在第一步就gg了，怎么U盘制作就一直失败呢
![Q6F 4 BQSY4@Y7D9R DK~JJ](https://user-images.githubusercontent.com/57552937/132544706-3f0517c1-70b3-4f6c-8221-8e9b0c582230.png)

**Comment by DrKoschei** [comment]
最近我也出现这个，解决方案是把U盘格式化为某个类型就可以了
