### ISSUE TITLE
使用0.7.3 oc出现合盖不插电源的情况下，外接显示器黑屏

### ISSUE THREAD

**Issue by deng-dengdengdeng-deng** [daliansky/XiaoXinPro-13-hackintosh#152]
使用0.7.3且升级macos12
开机速度有点慢，然后就是外接显示器，如果不插电源，合盖后外接显示器会变黑。电脑直接睡眠。
但是插电没事

**Comment by onnonn** [comment]
> 使用0.7.3且升级macos12
> 开机速度有点慢，然后就是外接显示器，如果不插电源，合盖后外接显示器会变黑。电脑直接睡眠。
> 但是插电没事

mac官网说明貌似写过，合盖外接显示器要接电源

**Comment by deng-dengdengdeng-deng** [comment]
> > 使用0.7.3且升级macos12
> > 开机速度有点慢，然后就是外接显示器，如果不插电源，合盖后外接显示器会变黑。电脑直接睡眠。
> > 但是插电没事
> 
> mac官网说明貌似写过，合盖外接显示器要接电源

好的谢谢！这个场景确实不常见，但是我好像记得之前11系统是可以的。
