### ISSUE TITLE
外接USB设备开机会卡住

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#153]
兄弟们，我现在是用Type-C外接了DELL显示器（充电+显示）
另外用DELL显示器自带的USB插了鼠标接收器、USB有线网卡、移动硬盘
如果在插着显示的情况下重启或者开机的话，就会卡在小新LOGO或者白苹果
只有拔掉Type-C才能继续开机
这个该如何解决？？？

**Comment by deng-dengdengdeng-deng** [comment]
我是开机后连接外界显示器，一会儿就死机。。（概率出现）

**Comment by surill** [comment]
刚刚试了一下，如果拔下显示器上的USB设备（移动硬盘、USB网卡、鼠标接收器），只用Type-C连接显示器，是可以正常开机的，有USB设备就会卡在小新LOGO

**Comment by AlanWalkBill123** [comment]
同样的问题，求解决办法

**Comment by surill** [comment]
> 同样的问题，求解决办法

【已解决】
进入BIOS设置，BOOT——USB BOOT——Disable
