### ISSUE TITLE
合盖外界显示器睡眠后无法唤醒/亮屏

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#155]
兄弟们帮忙测试一下，合盖只用外界显示器，一旦睡眠就不能按电源键唤醒亮屏，只能开盖才能唤醒

**Comment by ThankRain** [comment]
睡眠后长按电源键3~5s试试

**Comment by surill** [comment]
这不强制关机了……

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
