### ISSUE TITLE
oc0.7.3使用macos12系统无法睡眠问题

### ISSUE THREAD

**Issue by deng-dengdengdeng-deng** [daliansky/XiaoXinPro-13-hackintosh#156]
之前一直用0.6.2版本oc，在big sur上，合盖一晚上最多掉电百分之10（三星970）
但是自从换了0。7。3并升级12系统后，合盖放在书包里电脑就很热，今下午五个小时掉电百分之50.
请问是哪里的设置问题么？

**Comment by M69W** [comment]
@deng-dengdengdeng-deng 
方便的话，发一下 EFI，
在你的EFI 基础上升级 OC 测试

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
