### ISSUE TITLE
睡眠电脑还是发热 耗电很快  怎么排查问题

### ISSUE THREAD

**Issue by MagicianLjj** [daliansky/XiaoXinPro-13-hackintosh#158]

**Comment by surill** [comment]
很快是多快

**Comment by MagicianLjj** [comment]
> 很快是多快

没具体测过 睡眠放包里  第二天稳定因为电量耗完关机

**Comment by musicyy** [comment]
感觉不拆电源极其的耗电

**Comment by xiaobai403** [comment]
970evo 大概1.4%/h。

**Comment by Gabriel-theguy** [comment]
> 970evo 大概1.4%/h。

问一下用的哪个efi和oc版本呀。我i7，同970，用最新的efi睡一小时掉8%...

**Comment by MagicianLjj** [comment]
我的情况是：efi v3.0.2   oc 7.5   硬盘是原装忆联  macos 12.0.1   一小时耗电高于8%  基本上满电待机10小时见底
耗电很高  而且有发热的情况

**Comment by M69W** [comment]
没用 12.0.1 不清楚。
目前 10.15.7

**Comment by cytown** [comment]
> 没用 12.0.1 不清楚。 目前 10.15.7

+1

**Comment by MagicianLjj** [comment]
我最近才从10.15.7升级到12  两个系统表现一样  耗电很快

**Comment by M69W** [comment]
推荐使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)，并设置25睡眠
有问题再 reopen
