### ISSUE TITLE
出现冻屏死机现象

### ISSUE THREAD

**Issue by wh1456** [daliansky/XiaoXinPro-13-hackintosh#159]
音频也一直卡这,鼠标键盘无法使用,屏幕卡死,有时候会变灰,重启后进入安全模式

**Comment by chtys2008** [comment]
是不是换了网卡？要做屏蔽的。

**Comment by wh1456** [comment]
> 是不是换了网卡？要做屏蔽的。

没有啊,原装Intel网卡,的itlwm驱动

**Comment by wang-junda** [comment]
我这边也出现了，暂时也没有解决方案

**Comment by M69W** [comment]
小新 遇到 这种现象，只在 没屏蔽网卡的针脚时出现过。
其他硬件倒没有出现过。

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
