### ISSUE TITLE
OC版升级 10.15.4 失败

### ISSUE THREAD

**Issue by yinchaow** [daliansky/XiaoXinPro-13-hackintosh#16]
试过OC和Clover，v1.8版，都是在升级过程（白苹果+进度条）中，进度条走到差不多一半的地方（尚未提示安装剩余时间），自动重启。
也试过把Lilu、WG和Clover都升级到最新版，也不成功。
不知有无解决办法，谢谢！

**Comment by yinchaow** [comment]
看了debug日志，问题可能是出在这里：

> OC: Kernel patcher skips com.apple.driver.AppleIntelCFLGraphicsFramebuffer (DVMTpatch-10.15-10.15.1-10.15.2-10.15.3) patch at 0 due to version 0 <= 190400 <= 190300
OC: Kernel patcher com.apple.driver.AppleIntelCFLGraphicsFramebuffer (DVMTpatch-10.15.4) init failure - Not Found

这是核显的Framebuffer二进制补丁吗？

**Comment by daliansky** [comment]
安装过程中可能无法驱动核显，解决方案：注入无效的`platform-id`

**Comment by yinchaow** [comment]
> 安装过程中可能无法驱动核显，解决方案：注入无效的`platform-id`，比如：`0x12345678`试试

非常感谢小兵！按你的方法一遍成功，帮我节省了大量时间。

**Comment by M69W** [comment]
> 安装过程中可能无法驱动核显，解决方案：注入无效的`platform-id`，比如：`0x12345678`试试

补充一下：
`OC/config.plist / DeviceProperties / PciRoot(0x0)/Pci(0x2,0x0) / AAPL,ig-platform-id / EjRWeA==`
`12345678` -> `EjRWeA==`
