### ISSUE TITLE
monterey 可以用了吗

### ISSUE THREAD

**Issue by elf3** [daliansky/XiaoXinPro-13-hackintosh#164]
monterey 可以用了吗大佬

**Comment by yalay** [comment]
直接升级失败。重启安装界面进度条走了一点就重启了，一直这样子失败

**Comment by elf3** [comment]
> 直接升级失败。重启安装界面进度条走了一点就重启了，一直这样子失败

我升级成功了，重试了两次，目前蓝牙，wifi都正常，yogasmc也工作正常
