### ISSUE TITLE
兄弟们，有升级Monterey的吗

### ISSUE THREAD

**Issue by surill** [daliansky/XiaoXinPro-13-hackintosh#167]
兄弟们，有升级的吗，使用有没有问题

**Comment by cytown** [comment]
还在观望，没升级11呢。。。

**Comment by surill** [comment]
> 还在观望，没升级11呢。。。

大佬也太过保守了吧……11用着挺正常的，为啥不升级

**Comment by cytown** [comment]
据说兼容性还是有些问题，而且速度会慢。

https://www.zhihu.com/question/442467326

**Comment by jiangbeilaodao** [comment]
升级试了一下，发热耗电明显，又退回Catalina了

**Comment by wh1456** [comment]
升了 动画比以前11.6.1流畅很多,暂时没遇到软件兼容问题,Safari有点小bug

**Comment by Dragon526** [comment]
更新了，很好用，隔空播放很好用

**Comment by nujabse** [comment]
唯一的问题就是待机耗电比较高，其它都比 big sur 好
