### ISSUE TITLE
接hdmi无法4k60hz

### ISSUE THREAD

**Issue by liangwenzhong** [daliansky/XiaoXinPro-13-hackintosh#168]
type-c口直接外接显示器，可以实现4k60hz。

但是经过type-c拓展邬，通过拓展邬的hdmi口再接显示器，就无法实现4k60hz。只能30hz。

已经验证了很多个品牌的拓展邬，情况都一样。请问大家有遇到吗？

**Comment by musicyy** [comment]
是的，据说dc的八合一使用4lane可以支持4k60，不过尚未验证，还是直连吧。

**Comment by M69W** [comment]
> 是的，据说dc的八合一使用4lane可以支持4k60，不过尚未验证，还是直连吧。


虽然手里刚好有此拓展，支持的；
不一定要dockCase；
如果可以，typec 一线通何尝不更好？

**Comment by stoness2324** [comment]
使用了2个 tc转hdmi的拓展捂，都只能4k30，但是用tc转dp的线可以4k 60。
一线通估计得DELL那个带全能tc口的显示器才行
