### ISSUE TITLE
触摸板无法驱动

### ISSUE THREAD

**Issue by hyboyx** [daliansky/XiaoXinPro-13-hackintosh#17]
升级15.4后触摸板无法驱动。15.3可以。用的oc1.6版，换了1.8版也不行！

**Comment by mukeran** [comment]
执行 sudo kextcache -i / 试试

**Comment by M69W** [comment]
新装或升级系统后，都需要重建缓存才能正常正常工作

**Comment by handsomebroB** [comment]
我也无法使用  不知道什么原因，能否有朋友帮忙解决下啊，升级到15.4，用了最新的v2.0

**Comment by xqdxqd** [comment]
> 我也无法使用 不知道什么原因，能否有朋友帮忙解决下啊，升级到15.4，用了最新的v2.0

单独替换触摸板1.9里面的驱动就好了
