### ISSUE TITLE
S3睡眠探索

### ISSUE THREAD

**Issue by countrysideboy** [daliansky/XiaoXinPro-13-hackintosh#170]
目前手上没有这个机器，过段时间那回来了，开始折腾。想想睡眠还是s3的香啊，基本不耗电。不知道能否用acpi补丁的方式补齐代码，或者修改bios开启相关功能（测试版bios里面有，当时没有详细测试）

**Comment by cytown** [comment]
目前没找到办法。。。不过按理说，几十年前的老电脑都能实现的，现在没道理不能。

**Comment by countrysideboy** [comment]
> 目前没找到办法。。。不过按理说，几十年前的老电脑都能实现的，现在没道理不能。

我看到dell有机型有人做出补丁，补齐s3睡眠的相关代码，不懂小新行不行

**Comment by elf3** [comment]
s0-s4的睡眠都是在bios上提供的吧，理论上可行？

**Comment by surill** [comment]
期待大佬解决睡眠问题，现在只要带走笔记本就得关机，真是不方便

**Comment by jiangbeilaodao** [comment]
BIOS ACPI S3 Support: Enabled, Low Power S0 Idle: Disabled
win11可以进，powercfg -a 显示s3正常，S0 idle关闭，但实际睡眠死机，进入catalina睡眠同样死机
二者睡眠死机前键盘背光均亮一下，死机按电源键关机重启后键盘背光都重置为关闭状态

如果ssdt中设置s0id=0则win11无法启动蓝屏，catalina睡眠死机

**Comment by brandbao** [comment]
> 目前手上没有这个机器，过段时间那回来了，开始折腾。想想睡眠还是s3的香啊，基本不耗电。不知道能否用acpi补丁的方式补齐代码，或者修改bios开启相关功能（测试版bios里面有，当时没有详细测试）

拿回来了吗？折腾的怎么样了

**Comment by loserc6** [comment]
> 目前手上没有这个机器，过段时间那回来了，开始折腾。想想睡眠还是s3的香啊，基本不耗电。不知道能否用acpi补丁的方式补齐代码，或者修改bios开启相关功能（测试版bios里面有，当时没有详细测试）
s3 需要bios 支持才行，对于补齐s3代码 这个不清楚，你可以发出来连接我去看看

**Comment by Jane42070** [comment]
我在网上看到了给不支持S3睡眠的YOGA笔记本通过补全DSDT添加S3睡眠的步骤 [YOGA笔记本](https://valinet.ro/2020/12/08/Enable-S3-sleep-on-Lenovo-Yoga-Slim-7-14are05.html)
也许对这个有帮助

**Comment by Jane42070** [comment]
> > 目前手上没有这个机器，过段时间那回来了，开始折腾。想想睡眠还是s3的香啊，基本不耗电。不知道能否用acpi补丁的方式补齐代码，或者修改bios开启相关功能（测试版bios里面有，当时没有详细测试）
> 
> s3 需要bios 支持才行，对于补齐s3代码 这个不清楚，你可以发出来连接我去看看

s3在小新13BIOS解锁高级菜单里的acpi table 里面是支持的，但是在bios里关闭s0开启s3睡眠，在window里睡眠就无法唤醒，我的mac monetery下可以，但是没有测试续航，不知道是不是真的s3睡眠

**Comment by cytown** [comment]
> > > 目前手上没有这个机器，过段时间那回来了，开始折腾。想想睡眠还是s3的香啊，基本不耗电。不知道能否用acpi补丁的方式补齐代码，或者修改bios开启相关功能（测试版bios里面有，当时没有详细测试）
> > 
> > 
> > s3 需要bios 支持才行，对于补齐s3代码 这个不清楚，你可以发出来连接我去看看
> 
> s3在小新13BIOS解锁高级菜单里的acpi table 里面是支持的，但是在bios里关闭s0开启s3睡眠，在window里睡眠就无法唤醒，我的mac monetery下可以，但是没有测试续航，不知道是不是真的s3睡眠

你要在windows下执行：
`powercfg /a
`
看看结果输出里面有没有S3

**Comment by Jane42070** [comment]
> > > > 目前手上没有这个机器，过段时间那回来了，开始折腾。想想睡眠还是s3的香啊，基本不耗电。不知道能否用acpi补丁的方式补齐代码，或者修改bios开启相关功能（测试版bios里面有，当时没有详细测试）
> > > 
> > > 
> > > s3 需要bios 支持才行，对于补齐s3代码 这个不清楚，你可以发出来连接我去看看
> > 
> > 
> > s3在小新13BIOS解锁高级菜单里的acpi table 里面是支持的，但是在bios里关闭s0开启s3睡眠，在window里睡眠就无法唤醒，我的mac monetery下可以，但是没有测试续航，不知道是不是真的s3睡眠
> 
> 你要在windows下执行： `powercfg /a ` 看看结果输出里面有没有S3

![6c02eb662364db20](https://user-images.githubusercontent.com/45375971/169471450-36d75ca6-e42d-437d-9825-d09491f03915.jpg)
这个是我bios关闭s0后
![image](https://user-images.githubusercontent.com/45375971/169471658-1f2cd6ec-2af7-4305-bc3d-4cc14a07b329.png)
这是我bios开启s0后

**Comment by cytown** [comment]
看来还是需要修改DSDT

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)，设置25睡眠
有问题再 reopened
