### ISSUE TITLE
跑码完成后键盘没反应

### ISSUE THREAD

**Issue by GitHubAdminis** [daliansky/XiaoXinPro-13-hackintosh#176]
跑码完成后用自带键盘和外接键盘均按键无反应，无法选择启动系统，只能外接有线鼠标点击选择

**Comment by GitHubAdminis** [comment]
系统是macOS Monterey 12.0.1

**Comment by jiangbeilaodao** [comment]
检查下kext加载次序

**Comment by GitHubAdminis** [comment]
> 检查下kext加载次序

就用的最新版EFI，没改动

**Comment by liang-0131** [comment]
我也有这个问题

**Comment by M69W** [comment]
没法重现

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
