### ISSUE TITLE
Dec 11, 2021 version of OC is 0.7.6

### ISSUE THREAD

**Issue by Sun1090** [daliansky/XiaoXinPro-13-hackintosh#177]
On December 14th, apple released macOS12.1, I can't seem to receive the update, how should I receive the update?

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/55db74883887ecd0a4e0690833e8477c00eea388/EFI/EFI_OC/OC/config.plist#L839-L840

set `Disabled` as `Default`,
reboot and try a again.

if it can't works, need `reset NVRAM`.

**Comment by Sun1090** [comment]
According to what you said, I have completed the upgrade of macOS12.1, thank you！
![image](https://user-images.githubusercontent.com/51160517/146130552-54e9f60d-16ec-4882-a087-2d5abd4f30a0.png)

**Comment by surill** [comment]
> According to what you said, I have completed the upgrade of macOS12.1, thank you！
> ![image](https://user-images.githubusercontent.com/51160517/146130552-54e9f60d-16ec-4882-a087-2d5abd4f30a0.png)

系统语言是中文，咋还说英语呢🤤🤤🤤

**Comment by Sun1090** [comment]
> > 按照你说的，我已经完成了macOS12.1的升级，谢谢！
> > ![图片](https://user-images.githubusercontent.com/51160517/146130552-54e9f60d-16ec-4882-a087-2d5abd4f30a0.png)
> 
> 系统语言是中文，咋还说英语呢🤤🤤🤤

哈哈，被发现了
