### ISSUE TITLE
OC0.7.6 无法升级12.1 

### ISSUE THREAD

**Issue by yanxu117** [daliansky/XiaoXinPro-13-hackintosh#178]
把securebootmodel设置为default之后，收到了更新，重启之后卡在初始化界面，如图
![3911639543004_ pic](https://user-images.githubusercontent.com/76116903/146124220-f8a5563a-d61a-47f3-a680-84d028685517.jpg)

**Comment by M69W** [comment]
尝试重启
或 reset NVRAM 再试试

**Comment by baolong24** [comment]
> 尝试重启
> 或 reset NVRAM 再试试

咱也是一样的问题，已经尝试过 Reset NVRAM 但是并不起作用

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/177#issuecomment-994230031
尝试一下以上链接里的操作

**Comment by baolong24** [comment]
> [#177 (comment)](https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/177#issuecomment-994230031)
> 尝试一下以上链接里的操作

已经设为 `Default` 但依旧卡在 `-v`
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/30337499/146669350-6e810cb8-4f54-4c4e-8bd0-db2a14ffcba0.png">

**Comment by M69W** [comment]
贴报错 日志
