### ISSUE TITLE
引导页黑屏

### ISSUE THREAD

**Issue by liangwenzhong** [daliansky/XiaoXinPro-13-hackintosh#179]
10月8日之后的版本。
开机，显示完小新logo后，屏幕完全黑。
所有文字logo都没有但是，但是再按回车键，可以进入系统。
感觉就是所有的图标，文字都没显示。load进度条的苹果logo也没显示。
是否图标格式有问题？还是配置？

**Comment by liangwenzhong** [comment]
有人遇到这种情况？

**Comment by Silvdawn** [comment]
重置引导项，我这边是开机黑屏后键盘左键然后回车就可以了，建议准备好pe

**Comment by M69W** [comment]
无法重现。
也不知道怎么条件下导致的。

**Comment by liangwenzhong** [comment]
在旧的 efi，先reset一下，然后再替换新的就可以了。 或者按照上面的办法，左键然后回车，reset。也可以解决。
