### ISSUE TITLE
i7使用1.8的OC声音会断

### ISSUE THREAD

**Issue by wulie88** [daliansky/XiaoXinPro-13-hackintosh#18]
小新pro 13 i7 2019使用1.8的OC，加了DW1820A网卡，使用内置扬声器，播放bilibili网页视频、优酷app电影，一会儿没有声音了，切换耳机再用内置扬声器会有声音，又能正常一会儿，如此反复。
出问题时候，调整内置扬声器音量，会有吱吱声音。

希望大神有空之余解决一下这个问题，非常感谢。如需更多细节，请回复，我会积极配合。

**Comment by M69W** [comment]
目前声卡和麦克风，还不能很好地支持
先解决能不能用，再解决好不好用的问题。

**Comment by Hush-vv** [comment]
我一直使用的声卡ID是11，不知道你们使用这个会不会正常

**Comment by loserc6** [comment]
需要打开系统偏好设置 声音-输入 挂后台 才不会没声音 
反正我是这样就不会掉声音

**Comment by M69W** [comment]
> 需要打开系统偏好设置 声音-输入 挂后台 才不会没声音
> 反正我是这样就不会掉声音

尝试：[04-18-2020：关于声卡ID 使用情况](https://github.com/daliansky/XiaoXinPro-13-hackintosh/commit/1087b3bef02d17c6b43b9b4b91a0614b82a6c1b8)

**Comment by wulie88** [comment]
这个问题这几天没有再出现了。

这个提问我先关闭了，再次感谢大神无私维护。

**Comment by LightingStar404** [comment]
唤醒后没有声音，在设置-输入中重新选择声音输入设备后，会短暂的有声音，然后一会就没有声音时。可以通过连接一个蓝牙耳机，在使用线控耳机就一切正常。
这个问题貌似与输入有关，在连接了一个蓝牙耳机后，设置中会多出一个输入设备，这个时候断开蓝牙耳机，使用线控就一切正常。

**Comment by wulie88** [comment]
现在这个问题又出现了，无解。

我还是没声音了，切换下耳机，再切换回来。。。

**Comment by LightingStar404** [comment]
你连接一个蓝牙耳机试试，只要输入设备中多一个设备，耳机输出就能够正常。

**Comment by LightingStar404** [comment]
先连接蓝牙耳机，然后在断开。断开后，耳机输出就是正常的

**Comment by yalay** [comment]
只要声音断了，我连了一个有线耳机，切换下输出，之后即使拔掉耳机，也是正常放音的，不重启就一直ok。可能重启了需要重复下这个动作

**Comment by M69W** [comment]
同 /issues/63
