### ISSUE TITLE
更新12.1后无法使用DW1820A

### ISSUE THREAD

**Issue by yanxu117** [daliansky/XiaoXinPro-13-hackintosh#180]
如题，没法截图因为跑码总是随机卡住，只有在BIOS关闭网卡才能进系统

**Comment by yanxu117** [comment]
尝试了把所有和网卡相关的kext全部去掉，也是卡住，只要网卡还开着就不行

**Comment by yanxu117** [comment]
换了白果卡，一切都完美了，小兵当时为啥要推DW系列卡呢，费解

**Comment by cytown** [comment]
白果卡尺寸不合适。大部分人都没有问题。而且那时候也没有12.1
