### ISSUE TITLE
Monterey 因特尔 蓝牙

### ISSUE THREAD

**Issue by tonynesss** [daliansky/XiaoXinPro-13-hackintosh#182]
家人们，现在Monterey的蓝牙可以用了吗？系统是最新的12.1，网卡AX201，添加了BlueToolFixup.kext。按照之前的提供的教程。有的人蓝牙又是可用的，有的又不行。要怎么操作呢，用不了耳机太难受了。

**Comment by medlar01** [comment]
不知道，我的是换了苹果能用的网卡

**Comment by Silvdawn** [comment]
自己不看开发者说明，都说了不要用在Monterey
<img width="805" alt="截屏2021-12-25 上午10 01 55" src="https://user-images.githubusercontent.com/87458369/147375808-b4bf709e-6c7f-4e5b-a26d-91f9234b3d28.png">

**Comment by tonynesss** [comment]
> 自己不看开发者说明，都说了不要用在Monterey
> <img width="805" alt="截屏2021-12-25 上午10 01 55" src="https://user-images.githubusercontent.com/87458369/147375808-b4bf709e-6c7f-4e5b-a26d-91f9234b3d28.png">
> 

说的不是这个驱动啊

**Comment by Silvdawn** [comment]
非常抱歉，我看错了，回复错人了，对不起

**Comment by tonynesss** [comment]
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/369看到一个类似issue

**Comment by medlar01** [comment]
原装的可以驱动wifi和蓝牙了？

**Comment by chenyulun** [comment]
大佬，帮忙关注一下，有消息通知一下，我的12.2.1，蓝牙也用不了
ax210+蓝牙5.2

  蓝牙控制器：
  地址：	NULL
  状态：	关闭
  芯片组：	BCM_4350C2
  可被发现：	关闭
  固件版本：	v0 c0
  产品ID：	0x0001
  支持的服务：	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  传输：	USB
  供应商ID：	0x004C (Apple)

**Comment by arloan** [comment]
我的Intel网卡在12.2.1下蓝牙正常用，甚至比 Windows 下更好用。之前在Windows10下面，连着蓝牙鼠标的同时连蓝牙耳机，用不了几分钟耳机就会声音拉长，然后丢失连接，Monterey下面跟鼠标共存和谐。

![bluetooth](https://user-images.githubusercontent.com/1157026/155872085-7333c209-28df-49c8-b361-2a7c536e2d34.png)

注意：几个蓝牙相关的驱动加载顺序据说非常重要，我直接按照正确顺序做的配置，没有测试非正确顺序：
![plist](https://user-images.githubusercontent.com/1157026/155872173-cc3cb36e-71d0-4ead-bbad-4e36783553ab.png)

**Comment by chenyulun** [comment]
@arloan 你的是蓝牙5.x吗

我的是Intel 的ax210,带的蓝牙5.2版本的，确实驱动不了
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/15979948/155878386-0671a311-a31e-40a1-81dc-8bb39f7aea15.png">

**Comment by arloan** [comment]
@chenyulun 这个不清楚，怎么查？

**Comment by ThankRain** [comment]
> 我的Intel网卡在12.2.1下蓝牙正常用，甚至比 Windows 下更好用。之前在Windows10下面，连着蓝牙鼠标的同时连蓝牙耳机，用不了几分钟耳机就会声音拉长，然后丢失连接，Monterey下面跟鼠标共存和谐。
> 
> ![bluetooth](https://user-images.githubusercontent.com/1157026/155872085-7333c209-28df-49c8-b361-2a7c536e2d34.png)
> 
> 注意：几个蓝牙相关的驱动加载顺序据说非常重要，我直接按照正确顺序做的配置，没有测试非正确顺序： ![plist](https://user-images.githubusercontent.com/1157026/155872173-cc3cb36e-71d0-4ead-bbad-4e36783553ab.png)

十分感谢，我将加载顺序调整后能够正常使用了

**Comment by akFace** [comment]
> 

请问 BlueToolFixup.kext文件在哪下载啊

**Comment by ThankRain** [comment]
> > 
> 
> 请问 BlueToolFixup.kext文件在哪下载啊

Wiki https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-does-this-kext-do
BlueToolFixup https://github.com/acidanthera/BrcmPatchRAM

**Comment by akFace** [comment]
> > > 
> > 
> > 
> > 请问 BlueToolFixup.kext文件在哪下载啊
> 
> Wiki https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer BlueToolFixup https://github.com/acidanthera/BrcmPatchRAM

多谢
