### ISSUE TITLE
睡眠后cpu发热

### ISSUE THREAD

**Issue by FortyPoint** [daliansky/XiaoXinPro-13-hackintosh#185]
拆机摸了下，确实是cpu在发热，不是硬盘或其他，以前睡眠都不怎么耗电的。在macOS下空载cpu也有近2w的功耗，以前只有1w

**Comment by liangwenzhong** [comment]
一样的情况，盖上盖子，风扇还在转。

**Comment by cytown** [comment]
我的是10没问题，升级成11以后就变成这样了。各种OC版本都是如此。

**Comment by Bobotou** [comment]
感觉和OC没有关系，不同版本在bigsur下都会出现这个问题

**Comment by cytown** [comment]
> 感觉和OC没有关系，不同版本在bigsur下都会出现这个问题

也不能说完全没关系，应该是OC本身的兼容性问题吧。或者是bigsur对于待机就是有bug？？？

**Comment by Bobotou** [comment]
> ？？？

我打算一会儿升降Monterey试试

**Comment by Kanepan** [comment]
> 
现在测试后是什么结果 ？

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)，设置25睡眠
有问题再 reopened
