### ISSUE TITLE
两处错误

### ISSUE THREAD

**Issue by ClayMoreBoy** [daliansky/XiaoXinPro-13-hackintosh#186]
UEFI->Output->TextRenderer是无效的 (只能是BuiltinGraphics, BuiltinText, SystemGraphics, SystemText, 或 SystemGeneric)!
UEFI->Output->SanitiseClearScreen没有在System TextRenderer模式下启用 (当前模式为 )!
CheckUefi 返回2处错误!

**Comment by M69W** [comment]
所用检测工具是？

**Comment by ClayMoreBoy** [comment]
OpenCore Configurator @M69W

**Comment by surill** [comment]
@M69W 大佬最近怎么没有更新了

**Comment by M69W** [comment]
@surill 
最近忙于人生大事，然后要15后回去上班，所以就暂时停更了。

**Comment by Sun1090** [comment]
过年这段时间，大家都忙于人生大事吧

**Comment by ClayMoreBoy** [comment]
@M69W 人生大事很重要 恭禧

**Comment by M69W** [comment]
> @M69W 人生大事很重要 恭禧

今天已上班了。这几天找时间更新一下

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
