### ISSUE TITLE
OC 1.9 开HiDPi

### ISSUE THREAD

**Issue by M69W** [daliansky/XiaoXinPro-13-hackintosh#19]
版本：[releases OC v1.9](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v1.9)
机型：小新pro 13 2019 + i7 + 华星屏(不解CFG、不解DVMT)
系统：10.15.4 (19E287)

### 使用一键脚本：
[xzhih‘s one-key-hidpi](https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md)
脚本操作过程：
1.`保持原样`
2.`开启HIDPI(同时注入EDID)`
3.`手动输入分辨率`
3.`1680x1050` (或`1680x1050,1680x945,1280x800`)
4.重启

#### 开启HiPDI 后出现的现象
1.开机过程出现花瓶；无使用影响
2.可能出现显示不完整，变小，**解决**：盒盖再开盖，输入密码，不行再盒盖再开盖；或电源键睡眠然后再电源键唤醒；
3.睡眠可能会显示不完整，**解决**：盒盖再开盖，输入密码，不行再盒盖再开盖；或电源键睡眠然后再电源键唤醒；
4.使用过程中，偶尔出现闪屏，一瞬间后恢复正常，不太影响正常使用。

### 基本能正常使用

**Comment by Hush-vv** [comment]
第三点可以改显卡ID解决AAPL,ig-platform-id Datd 0400A53E、device-id Data A53E0004。我的i7就说这样解决睡眠唤醒显示不完整的

**Comment by ltesla** [comment]
> 第三点可以改显卡ID解决AAPL,ig-platform-id Datd 0400A53E、device-id Data A53E0004。我的i7就说这样解决睡眠唤醒显示不完整的

萌新请问下，睡眠显示不完整是不是说 外接显示器的情况下，合上主机盖子后，外接屏幕就黑屏了？
![IMG_8699](https://user-images.githubusercontent.com/40025140/82537938-7d158100-9b7d-11ea-973e-4581a1b11d95.JPG)

**Comment by M69W** [comment]
> > 第三点可以改显卡ID解决AAPL,ig-platform-id Datd 0400A53E、device-id Data A53E0004。我的i7就说这样解决睡眠唤醒显示不完整的
> 
> 萌新请问下，睡眠显示不完整是不是说 外接显示器的情况下，合上主机盖子后，外接屏幕就黑屏了？
> ![IMG_8699](https://user-images.githubusercontent.com/40025140/82537938-7d158100-9b7d-11ea-973e-4581a1b11d95.JPG)

参考 [PciRoot(0x0)/Pci(0x2,0x0)](https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI-CLOVER-PRO13/CLOVER/config.plist#L338-L370) 即

把 `<key>AAPL,ig-platform-id</key>` 对应的值改成 `<data>BQCmPg==</data>`
 或者
直接抄整个

```
<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>BQCmPg==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>pj4AAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>enable-hdmi-dividers-fix</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-pipe</key>
				<data>EgAAAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>model</key>
				<string>Intel Iris Plus Graphics 655</string>
			</dict>
```

**Comment by ltesla** [comment]
好的，谢谢！

M69W <notifications@github.com>于2020年7月14日 周二23:42写道：

**Comment by fncheng** [comment]
> #### 开启HiPDI 后出现的现象
> 1.开机过程出现花瓶；无使用影响
> 2.可能出现显示不完整，变小，**解决**：盒盖再开盖，输入密码，不行再盒盖再开盖；或电源键睡眠然后再电源键唤醒；
> 3.睡眠可能会显示不完整，**解决**：盒盖再开盖，输入密码，不行再盒盖再开盖；或电源键睡眠然后再电源键唤醒；
> 4.使用过程中，偶尔出现闪屏，一瞬间后恢复正常，不太影响正常使用。

请问第三点是不是指睡眠唤醒后,屏幕显示区域变小, 具体表现为,屏幕右边和下边有黑边不显示?

**Comment by M69W** [comment]
参考一下[HiDPi](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/HiDPi)
