### ISSUE TITLE
19款i7版 - Monterey 12.2 无法调整屏幕亮度和分辨率

### ISSUE THREAD

**Issue by arloan** [daliansky/XiaoXinPro-13-hackintosh#190]
小新Pro13-2019 i7-10710U，未替换wifi网卡，内置三星硬盘未替换，安装到usb外置西数硬盘。
EFI: 3.0.4 发布原版，cpuid 该 EFI 已仿冒 6ec，因Monterey版本高过Guide说明的10.15.7上限，所以DVMT／CFG补丁也没有使用。

安装过程：
一开始始终报告“mutable product symlink creation failed”然后挂起，思考良久，删除EFI中所有BCM相关驱动后一切顺利。
手动安装 AirportIntlwm 驱动后 wifi 工作正常，蓝牙暂时未关注。
因为屏幕亮度太刺眼，字太小，试图调整时发现 Fn+F11/F12 无反应，HiDPI 脚本 enable 之后仍然只有 2560x1600 一个分辨率。

求解决办法／想法。谢过！

**Comment by arloan** [comment]
对了，系统显示设置面板里甚至没有那个亮度拖动条。:(

**Comment by arloan** [comment]
![Screen Shot 2022-02-15 at 9 04 04 PM](https://user-images.githubusercontent.com/1157026/154073148-a2f649b6-46c4-4312-b8f2-f34b5fe87b96.png)
![Screen Shot 2022-02-15 at 9 04 31 PM](https://user-images.githubusercontent.com/1157026/154073194-a827222a-a721-42bb-9a80-3dd8dabc3b76.png)

我推测还是dvmt的问题，系统属性里显存只有15M，并且没有为显卡加载kext。
![Screen Shot 2022-02-15 at 21 26 39](https://user-images.githubusercontent.com/1157026/154073820-d746f726-9353-4656-bf05-0207d0e4367e.png)

不知道该咋办，必须刷自定义BIOS吗？

**Comment by arloan** [comment]
另外：USB-C to HDMI+USB-A 的 Docker 也不起作用，这个绿联的 Docker 接白苹果是可用的。

**Comment by arloan** [comment]
更新一下目前的发现：

想起来我安装是用的OC那个 config-install.plist，里面的 ig-platform-id 是 12345678，然后无论是改用运行用的 config.plist，还是仅仅把 config-install.plist 里的 ig-platform-id 改为 0500A63E 而其余不变，均会导致系统无法启动，字幕走不完。

12.2.1 有人成功了的吗？

**Comment by Byvm815** [comment]
i5-10210u 系统12.0.1 也有上述问题。蓝牙可以通过安装最新的IntelBluetoothFirmware解决。显卡id00009B3E,显存没有问题，玩mc有60多帧。由于现在手边没有额外的电脑，系统也没有空间装windows，所以没有办法折腾。希望能帮到你。

**Comment by Byvm815** [comment]
@arloan i5-10210u 系统12.0.1 也有上述问题。蓝牙可以通过安装最新的IntelBluetoothFirmware解决。显卡id00009B3E,显存没有问题，玩mc有60多帧。由于现在手边没有额外的电脑，系统也没有空间装windows，所以没有办法折腾。希望能帮到你。

**Comment by arloan** [comment]
@Byvm815 感谢！总算有了一个回音。不过我没有看明白，只需要改显卡ID就可以了吗？我试过几个，只要不是 config-install.plist 里面的 12345678 都过不了滚字幕。我先试试这个ID。
另外，你的机器有没有刷DVMT/CFG Lock 测试版 BIOS呢？

**Comment by Byvm815** [comment]
在设备属性设置中，更改AAPL,ig-platform-Id的值为00009B3E，更改device-id的值为9B3E0000。附上我的efi文件，https://cloud.189.cn/t/fiaimmANbYra 。之前安装10.15版本时更改过bios，现在用的12.0是更新上去的，能用，但问题多。

**Comment by arloan** [comment]
> @arloan 我使用oc引导，在设备属性设置中，更改AAPL,ig-platform-Id的值为00009B3E，更改device-id的值为9B3E0000。附上我的efi文件，https://cloud.189.cn/t/fiaimmANbYra 。之前安装10.15版本时更改过bios。

已解决，感谢兄弟！
![Screen Shot 2022-02-17 at 09 29 28](https://user-images.githubusercontent.com/1157026/154386818-f55d977c-e72d-4ed1-8096-584051da3e31.png)
