### ISSUE TITLE
省钱福音：有人说自己的三星 PM981a 在黑苹果中可以正常使用了

### ISSUE THREAD

**Issue by arloan** [daliansky/XiaoXinPro-13-hackintosh#191]
代价是性能损失：不过我觉得性能完全可以接受。
有人有兴趣做个验证吗？

https://www.reddit.com/r/hackintosh/comments/ls9gd8/pm981_ssd_finally_working_with_no_kernel_panic/

After a lot of tries in order to get my Samsung PM981 SSD working properly on macOS with no random freezes and random kernel panics, I got it working by setting nvme mode to SATA in the bios. I switched nvme mode from auto to SATA5,6 in bios and got my ssd working. my motherboard is Asus B450-F

I get about 1700MB/S write speed with SATA mode enabled comparing to 3000MB/S on Auto mode.

**Comment by M69W** [comment]
21年9月已经测试通过，不过没测试性能
https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/151

**Comment by fredeason** [comment]
一直都可以啊，，只是不建议用而已，，我的pro13s 就是981a，，macos下用了2年多了，还是办公用，，没出过什么意外啊

**Comment by arloan** [comment]
> 一直都可以啊，，只是不建议用而已，，我的pro13s 就是981a，，macos下用了2年多了，还是办公用，，没出过什么意外啊

嗯，早知道我就不买这个sn500了，省钱。我想是不是可以修改一下wiki里面关于硬盘的说明了。 @M69W

**Comment by M69W** [comment]
话是这么说，
但是你问下楼上是怎么处理的，劝退一部分人。

虽然可以Wiki 上加上，最优方案是什么？

**Comment by arloan** [comment]
最优方案当然是换硬盘。我关掉Issue吧。
