### ISSUE TITLE
v3.0.4 保持睡眠状态,电量耗光之后, 再次充电 一直保持1% ,无法充电

### ISSUE THREAD

**Issue by bozhihua** [daliansky/XiaoXinPro-13-hackintosh#193]
睡眠状态电量自动耗光，之后再次充电可以开机但是电量一直显示为1% ，拔下充电头立刻关机，关机充电也没有效果，并且左侧c口添加hub拓展hdmi也没有反应

**Comment by bozhihua** [comment]
目前情况，将原来的拆机windows硬盘重新换上 ，可以充电，电量显示正常。等电量充够之后拆机换回mac硬盘，可以正常使用，充电正常，c口转接hub也可以正常hdmi拓展

**Comment by arloan** [comment]
你把自动关机关了？我上次休眠一宿自动关机了，第二天插电开机电池10%，我推测低于10%休眠过程会自动关机。
你看看`sudo pmset -g`显示`autopoweroff`吗？

—— 奇怪，昨天我的还显示有 `autopoweroff`，今天怎么没有了。🤔

**Comment by Pablolu430** [comment]
我過年時也出現一樣的狀況... 更慘的是我在windows下還充不了電 （只能維持1% 用Lenovo Vantage會死機
然後我正想著要怎麼把這個電池運來台灣時
他就又正常了...

**Comment by M69W** [comment]
目前的建议是 `尽量不要用光电`

**Comment by bozhihua** [comment]
> 你把自动关机关了？我上次休眠一宿自动关机了，第二天插电开机电池10%，我推测低于10%休眠过程会自动关机。 你看看`sudo pmset -g`显示`autopoweroff`吗？
> 
> —— 奇怪，昨天我的还显示有 `autopoweroff`，今天怎么没有了。🤔

目前情况最好就是在长时间不使用的情况下进行关机处理，睡眠耗电不可控

**Comment by bozhihua** [comment]
> 我過年時也出現一樣的狀況... 更慘的是我在windows下還充不了電 （只能維持1% 用Lenovo Vantage會死機 然後我正想著要怎麼把這個電池運來台灣時 他就又正常了...

之前很多次电量耗光之后再次充电正常，这次也是偶发情况，最好注意一下。长时间不用做个关机处理 或者连接电源，不要用光电量

**Comment by bozhihua** [comment]
> 目前的建议是 `尽量不要用光电`

好的，谢谢，以后注意电量使用了

**Comment by surill** [comment]
可以试试关机后，长按电源键20秒以上
我之前遇到的问题是无法充电（充电口旁边指示灯不亮）
