### ISSUE TITLE
Monterey 睡醒后系统界面反应异常

### ISSUE THREAD

**Issue by arloan** [daliansky/XiaoXinPro-13-hackintosh#196]
有时候（不是每次）睡醒后系统界面操作和反应出现异常，还没有捕捉到规律。异常包括：

1. 系统菜单条右边的图标区所有图标点击无反应，有点击的UI效果出现，但是没有菜单弹出；
2. Cmd+Tab可以切换应用窗口，但是鼠标左键点击程序窗口无法把前台/焦点切换到该窗口，但是左键按住可以拖动该窗口，即使拖动窗口，该窗口仍然处于失焦窗台，不会成为前台焦点窗口；
3. 点击任务栏的未启动程序的图标，不会启动该程序，而是会打开一个/Application目录的Finder窗口，并定位到（选中）该程序，简直莫名其妙 ；
4. 执行命令行命令：`killall Finder`不能解决问题，`killall SystemUIServer`不能解决问题，登出并重新登入用户不能解决问题。
5. 重启系统解决问题。

这个现象好奇怪，感觉有点像键盘某个键被保持按住了似的，但是把键盘的Ctl/Shift/Cmd(Win)/Alt按了个遍也没用。大家有出现过吗？

补充：刚才在UI正常的情况下测试了一遍，以上的猜测是正确的，完全符合Cmd键被保持按下的界面反应。不知道如何强迫系统认为Cmd键已经松开？

**Comment by arloan** [comment]
补充：并没有开Sticky Keys

![image](https://user-images.githubusercontent.com/1157026/155826709-1f2e689d-1104-4e19-9497-7036e46c579a.png)

**Comment by Silvdawn** [comment]
Catalina中偶尔会遇到第3个问题，不过几率很小，我猜是系统问题？？？

**Comment by LonelyFantasy** [comment]
同样碰到了一样的问题。不过我是每次唤醒登录后需要自行按一下cmd（Alt）键后才恢复正常。

**Comment by BlackEdn** [comment]
我现在是big sur11.6，同样也有偶尔睡眠结束后自动按住cmd按键的问题，暂时我的解决方法是出现的时候按cmd+shift就可以恢复正常，不知道是不是什么快捷键？

**Comment by arloan** [comment]
我这边满键盘按遍都没有用，暂时没有找到除关机冷启动之外的办法。

**Comment by M69W** [comment]
没遇到过

**Comment by surill** [comment]
没遇到过+1

**Comment by liuxuan0218** [comment]
同问，遇到过几次同样的的情况，睡眠唤醒之后类似于command键被一直按住的情况，点击应用直接打开访达中其所在的位置，按一下command才能正常。

**Comment by arloan** [comment]
找到原因了：USB-C扩展坞的问题，可能有漏电或者什么原因。拔掉扩展坞重新插入就解决了。
