### ISSUE TITLE
opencore 0.7.9 ，蓝牙以及启动时滚两次代码才能开机

### ISSUE THREAD

**Issue by elf3** [daliansky/XiaoXinPro-13-hackintosh#197]
1. 蓝牙驱动
![image](https://user-images.githubusercontent.com/18027182/156522183-bb8c2ff0-901a-4457-b6bf-97fe0fa9d1fa.png)
需要去掉 BrcmBluetoothInjector.kext 的选项

2. 启动经常会需要滚两次代码才能开机
这个我现在不好录屏，找个时间录个屏上传一下
说一下开机碰到的问题

纠正
小新logo > opencore启动界面 > 白果logo >  小新logo > opencore启动界面 > 白果logo  > 正常启动

`小新logo > opencore启动界面 > 白果logo `  这个过程可能会重复1-3遍都有可能

有尝试过清理nvarm, 没用

但是只需要开启 `-v` 就不会出现这个问题，已经重建过缓存了
有遇到这个问题的大佬给解答一下

**Comment by elf3** [comment]
会重启的参数
```
bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 keepsyms=1 forceRenderStandby=0 brcmfx-country=#a
```

不会重启的参数
```
-v bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 keepsyms=1 forceRenderStandby=0 brcmfx-country=#a
```

**Comment by elf3** [comment]
https://www.tonymacx86.com/threads/monterey-boot-error.316663/post-2301658

这里有一个一样的问题

**Comment by elf3** [comment]
![2941646299782_ pic](https://user-images.githubusercontent.com/18027182/156682377-68386dde-a659-44ed-a45d-71a9bb714b29.jpg)


启动时的错误

**Comment by elf3** [comment]
Copyright (c) 1982.
acptb:
acptb:
acplb:
acplb:
acplb:
acplb:
acptb:
Invalid
Invalid
Invalid
Invalid
invalid
Invalid
invalid
supplement
supplement
supplement
supplement
supplement
supplement
supplement
info
Info
Info
Info
Info
Info
info
for
for
for
for
for
for
for
ManufactureDate (ffffffff)
Temperature (4294967295)
TlmeToFull (4294967295)
TimeToEmpty (4294967295)
ChargeLevel (4294967295)
Charg ingCurrent (-1)
ChargIngVoItage (-1)
MRC Framework successfully Initialized v 、 __«>
RppIeKeyStore:863:0: oy vey
RMFIInttialtzeLcK»LSlgningPublIcKey: failed to get local signing public key (e60002bc)
using 16384 buffer headers and 10240 cluster 10 buffer headers
mcache: 12 CPU(s), 64 bytes CPU cache line size
mbtnit: done 1256 HB total pool size, (170/85) split]
Waiting for all the create dill kernel threads to get scheduled at least once.
.fill the created dill kernel threads have been scheduled at least once. Proceeding.
com .apple .Rppl^SCompresslonTypeDataless kmod start
tfnet_attach: All kernel threads created for Interface loO have been scheduled at least once. Proceeding.
lfnet_attach: Matting for all kernel threads created for Interface glfO to get scheduled at least once.
lfnet_attach: fill kemei threads created for Interface glfO have been scheduled at least once. Proceeding,
com.apple.flppLeFSCompresslonTypeZlib kmod start

**Comment by M69W** [comment]
> 会重启的参数
> 
> ```
> bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 keepsyms=1 forceRenderStandby=0 brcmfx-country=#a
> ```
> 
> 不会重启的参数
> 
> ```
> -v bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 keepsyms=1 forceRenderStandby=0 brcmfx-country=#a
> ```

这些启动参数是？

默认启动参数只有这几个
https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI_OC/OC/config.plist#L856

**Comment by M69W** [comment]
我看到了
https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/117#issuecomment-840313578

**Comment by elf3** [comment]
我测试了DW1560不会出现这个情况，是因为dw1820A的问题吗

**Comment by elf3** [comment]
#183 这个问题也是一样的

**Comment by elf3** [comment]
brcmfx-delay delays start of native broadcom driver for specified amount of milliseconds. It can solve panics or missing wi-fi device in Monterey. You can start with 15 seconds (brcmfx-delay=15000) and successively reduce this value until you notice instability in boot.

加上这个参数就可以了
brcmfx-delay=15000

**Comment by elf3** [comment]
```
brcmfx-delay=15000 bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 keepsyms=1 forceRenderStandby=0 brcmfx-country=#a
```

这个是我的启动参数

**Comment by M69W** [comment]
问题解决了吗？

**Comment by elf3** [comment]
> 问题解决了吗？

没有，还是偶尔能开机，要滚几遍代码

**Comment by elf3** [comment]
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/18027182/160039895-bc0a436c-3732-48fb-b340-78c83ead8896.png">
去掉这俩货，目前正常开机，但是airdrop就用不了

**Comment by M69W** [comment]
大佬什么网卡？

**Comment by BlackEdn** [comment]
大佬你也是1820a吗？我也遇到了一样的情况，删掉AirportBrcmFixup和里面的AirportBrcm_NIC_injector之后可以正常开机，但是wifi没有驱动，是不是要去掉屏蔽的五个针脚才能正常驱动wifi？

**Comment by elf3** [comment]
> 大佬你也是1820a吗？我也遇到了一样的情况，删掉AirportBrcmFixup和里面的AirportBrcm_NIC_injector之后可以正常开机，但是wifi没有驱动，是不是要去掉屏蔽的五个针脚才能正常驱动wifi？ 真的迷惑……偶尔能开机而且wifi可驱动，大部分，重启之后就会卡在MAC Framework suceessfully initialized后的不确定的一小段里

1820a, 你按照小兵的教程，屏蔽针脚就能用了

**Comment by elf3** [comment]
> 大佬什么网卡？

1820a
