### ISSUE TITLE
关于DVMT补丁和CFG开关的疑问

### ISSUE THREAD

**Issue by luozhongxiangsi** [daliansky/XiaoXinPro-13-hackintosh#198]
看了小兵的博客和wiki，关于DVMT和CFG开关，请教哈是不是如果已经用了OC DVMT补丁 ，就不需要再刷bios来解锁DVMT和CFG

**Comment by arloan** [comment]
那个OC DVMT补丁只适配到Catalina，后面的就不管用了。我的Monterey既没刷BIOS也没用这个补丁。

**Comment by M69W** [comment]
[DVMT 、 CFG 相关](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/DVMT%E8%A1%A5%E4%B8%81)
