### ISSUE TITLE
关于运行过程时异常电流声问题

### ISSUE THREAD

**Issue by XINZHOUZHANG** [daliansky/XiaoXinPro-13-hackintosh#199]
i5 pro13 2019 iml 仅换过白果网卡，其他硬件一致，系统为最新版。使用过程电脑偶尔有异常电流声且声音非常大，当把手放到触摸板移动时就会减小电流声音，移开后仍会继续响，关机停个一段时间后就会恢复了，请给予关注，非常感谢。

**Comment by surill** [comment]
我好像也听到有，回去确认一下

**Comment by DrKoschei** [comment]
左边键盘有一点点

**Comment by surill** [comment]
是的，我之前也注意到了，触摸板左边，听起来像机械硬盘的声音，后来一想不对啊，电脑里没有机械硬盘啊

**Comment by M69W** [comment]
有些网卡有嘶叫声，估计是网卡体质不好吧
下载时最为明显。
