### ISSUE TITLE
ALC257 works with latest version of VoodooHDA.

### ISSUE THREAD

**Issue by 3ig** [daliansky/XiaoXinPro-13-hackintosh#2]
I have Ideapad S540 with the same alc codec and the only way to make it work was with VoodooHDA.

**Comment by fpx-one** [comment]
Please provide your voodoo HDA

**Comment by fpx-one** [comment]
> 我的Ideapad S540具有相同的ALC编解码器，而使其工作的唯一方法是使用VoodooHDA。

请提供您的伏都教HDA

**Comment by fpx-one** [comment]
> I have Ideapad S540 with the same alc codec and the only way to make it work was with VoodooHDA.

Please provide your voodoo HDA

**Comment by fpx-one** [comment]
> I have Ideapad S540 with the same alc codec and the only way to make it work was with VoodooHDA.

Please provide your voodoo HDA

**Comment by fpx-one** [comment]
> 我的Ideapad S540具有相同的ALC编解码器，而使其工作的唯一方法是使用VoodooHDA。

In fact, we are s540

**Comment by fpx-one** [comment]
> I have Ideapad S540 with the same alc codec and the only way to make it work was with VoodooHDA.

We are all Lenovo products, belonging to the same model

**Comment by fpx-one** [comment]
> I have Ideapad S540 with the same alc codec and the only way to make it work was with VoodooHDA.

need you voodoohda ，
With the help of voodoohda's own application: getdump, how to use it: open the terminal, enter the command:
Getdump > ~ / desktop / voodoo dump.txt can be used to generate a voodoo dump.txt file. There will be two paragraphs of text description beginning with dumping playback / record paths, which includes both effective nodes and effective paths

**Comment by 3ig** [comment]
I'm away from home and the laptop is still not my daily driver. I'll dump it and post it here later tonight.

**Comment by fpx-one** [comment]
ok
Please upload EFI folder

**Comment by 3ig** [comment]
Everything you need is here: 
https://github.com/3ig/IdeaPad-S540-15IML-hackintosh

**Comment by thefiredragon** [comment]
For me with voodoohda is also microphone working.
So I am wondering about this, I also need to select speakers after an reboot.

**Comment by sarkrui** [comment]
As suggested by @宪武, the ALC257 works by injecting the following device properties `layout-id = 18 (12000000)` and `device-id (C89D0000)` to device `PciRoot(0x0)/Pci(0x1f,0x3)`. Of course, you will have `Lilu.kext` and `AppleALC.kext` properly installed. Below you can find the configuration details.

1. Remove `VoodooHDA.kext` and any setting that might be related to it.
2. Update `Lilu.kext` and `AppleALC.kext` to the latest and install them according to which bootloader you're using. 
2.1 **Clover:** /EFI/CLOVER/kexts/Other
2.2 **OpenCore:** /EFI/OC/kexts/ and load them in `config.plist`
3. Install `FakePCIID.kext`, `FakePCIID_Intel_HDMI_Audio.kext`. Please note that `FakePCIID.kext` should go first in OC `config.plist`
4. then you add `layout-id = 18 (12000000)` and `device-id (C89D0000)` to device `PciRoot(0x0)/Pci(0x1f,0x3)`

**** 

1 清除VoodooHDA.kext以及和它相关的所有列表、设置等。
2 更新Lilu.kext、AppleALC.kext，并且正确安装。
3 安装FakePCIID.kext、FakePCIID_Intel_HDMI_Audio.kext，如果是OC注意列表顺序。
4 PciRoot(0x0)/Pci(0x1f,0x3)下添加：
* layout-id = 18 （12000000）
* device-id （C89D0000）

**Comment by 3ig** [comment]
Using @sarkrui method i was able to run native audio with AppleALC on my IdeaPad-S540. The only difference is that i needed to change to layout-id = 11 ... layout 18 was distorting the audio signal from the headphone jack.

**Comment by thefiredragon** [comment]
Nice to see thank you guys
