### ISSUE TITLE
为啥qq群加不进去。。

### ISSUE THREAD

**Issue by arldeng** [daliansky/XiaoXinPro-13-hackintosh#202]

**Comment by M69W** [comment]
哪个群？

**Comment by arldeng** [comment]
> 

小新pro13的黑果群  黑果小兵的都进不去  大佬方便拉我进去吗 主要是方便交流

**Comment by M69W** [comment]
发号码看看

**Comment by arldeng** [comment]
> 发号码看看

我的q 328049603

**Comment by M69W** [comment]
可以试 这个 946132482，其他群应该也是可以的吧

**Comment by arldeng** [comment]
> 可以试 这个 946132482，其他群应该也是可以的吧

这个群搜索不到 提示无该群或设置不可搜索  其他有能搜索到的 申请了好几次都是没结果

**Comment by M69W** [comment]
> > 可以试 这个 946132482，其他群应该也是可以的吧
> 
> 这个群搜索不到 提示无该群或设置不可搜索 其他有能搜索到的 申请了好几次都是没结果

刚看了一下，群主设置不能搜索群号 找到这个群
![image](https://user-images.githubusercontent.com/15809201/163345598-d64335d6-83ad-4935-9744-85efcf4ffbd5.png)

我加你QQ吧
