### ISSUE TITLE
dw1560在big sur 11.6下隔空投送只能单向接受，可以看到设备但无法发送

### ISSUE THREAD

**Issue by BlackEdn** [daliansky/XiaoXinPro-13-hackintosh#203]
wifi，蓝牙一切正常；接力的网站，剪切板等可以正常打开和使用，只有隔空投送有问题。。同时，在测试的时候并没有连接蓝牙设备，清除蓝牙设备和恢复蓝牙出厂设置的方法以及在安全与隐私中添加如图的三个应用也试过，均无效。
更新：刚发现接力也是只能单方向，从手机到黑苹果。。。从黑苹果到手机一概不行
<img width="666" alt="截屏2022-04-11 下午5 34 12" src="https://user-images.githubusercontent.com/96945583/162710499-30d96f9f-ca03-4dd2-ae6a-4621c514a947.png">

<img width="628" alt="截屏2022-04-11 下午5 21 04" src="https://user-images.githubusercontent.com/96945583/162710160-134519ef-0659-4e68-b25b-62fb09f2b326.png">
<img width="953" alt="截屏2022-04-11 下午5 30 33" src="https://user-images.githubusercontent.com/96945583/162710167-89648692-55c6-45ae-bba5-3e30486c8f1d.png">
<img width="361" alt="截屏2022-04-11 下午5 42 43" src="https://user-images.githubusercontent.com/96945583/162712215-c9aac439-a693-4b2e-bb93-1af8d905bc16.png">
<img width="639" alt="截屏2022-04-11 下午5 31 26" src="https://user-images.githubusercontent.com/96945583/162712410-74a4fe70-bd13-4a7e-8712-550cd442f0f0.png">

[config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/8462958/config.plist.zip)

**Comment by M69W** [comment]
DW 系列网卡，毕竟不是拆机网卡，
这类问题 固件和 工作 都不同。
建议更新更好的黑苹果网卡：拆机网卡、Z3、Z4等

先关闭，如果有必要可以再次开启
