### ISSUE TITLE
V3.0.6 大家能低功耗休眠吗？

### ISSUE THREAD

**Issue by onnonn** [daliansky/XiaoXinPro-13-hackintosh#208]
西数sn750，bcm94360

**Comment by surill** [comment]
同硬盘，一小时耗电3%以上，一晚上就没电关机了

**Comment by cytown** [comment]
我的硬盘是intel的，在10.15下，每小时耗电不到1%，升级到11以后，每小时耗电4%左右。一天肯定就关机了。

而且，休眠的时候感觉电脑还是发热。

```
# pmset -g
System-wide power settings:
Currently in use:
 standby              1
 womp                 0
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 powernap             0
 gpuswitch            0
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                14
 hibernatemode        0
 ttyskeepawake        0
 displaysleep         14
 tcpkeepalive         0
 highstandbythreshold 50
 standbydelaylow      10800
```

**Comment by surill** [comment]
System-wide power settings:
Currently in use:
 standby              1
 womp                 1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        1
 powernap             1
 gpuswitch            2
 networkoversleep     0
 disksleep            10
 standbydelayhigh     86400
 sleep                0 (sleep prevented by dasd)
 hibernatemode        3
 ttyskeepawake        1
 displaysleep         120
 tcpkeepalive         1
 highstandbythreshold 50
 lowpowermode         0
 standbydelaylow      10800

**Comment by M69W** [comment]
羡慕 1%/1h

**Comment by cytown** [comment]
> 

hibernatemode 3 应该是不支持的。

**Comment by surill** [comment]
> 羡慕 1%/1h

大佬，最近怎么不更新EFI了

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)，设置25睡眠
有问题再 reopened
