### ISSUE TITLE
YOGASMC无法调整性能模式或性能模式下对CPU频率无影响

### ISSUE THREAD

**Issue by hawcat** [daliansky/XiaoXinPro-13-hackintosh#209]

**Comment by hawcat** [comment]
想用YOGASMC驱动提高下i7的睿频 不然mac上不了4ghz 
附win下和Mac下geekbench5跑分情况
[https://www.hawcat.cn/articles/77](url)
[https://cdn.hawcat.cn/articles/eb0f24a2a9072b9b7e98e98e59a327e4.png](url)
[https://cdn.hawcat.cn/articles/c4b5f668b142b080d0822b1262fef0d9.png](url)

**Comment by surill** [comment]
用YOGA SMC好像解决不了，之前测试即使选了高性能模式，还是上不了4G以上
用了CPU Friend和定制date也不行，更换机型也不行，不知道该怎么搞了

**Comment by M69W** [comment]
> 想用YOGASMC驱动提高下i7的睿频 不然mac上不了4ghz 附win下和Mac下geekbench5跑分情况 https://www.hawcat.cn/articles/77

文不对题？

**Comment by hawcat** [comment]
> 

我也是 用CPUFriend改了之后最高也只到过3.9g YOGASMC每次改了之后关掉又回去了

**Comment by hawcat** [comment]
> 用YOGA SMC好像解决不了，之前测试即使选了高性能模式，还是上不了4G以上
> 用了CPU Friend和定制date也不行，更换机型也不行，不知道该怎么搞了



> 用YOGA SMC好像解决不了，之前测试即使选了高性能模式，还是上不了4G以上
> 用了CPU Friend和定制date也不行，更换机型也不行，不知道该怎么搞了

我也是 用CPUFriend改了之后最高也只到过3.9g YOGASMC每次改了之后关掉又回去了

**Comment by hawcat** [comment]
> 用YOGA SMC好像解决不了，之前测试即使选了高性能模式，还是上不了4G以上
> 用了CPU Friend和定制date也不行，更换机型也不行，不知道该怎么搞了

我也是 用CPUFriend改了之后最高也只到过3.9g YOGASMC每次改了之后关掉又回去了

**Comment by hawcat** [comment]
> > 想用YOGASMC驱动提高下i7的睿频 不然mac上不了4ghz 附win下和Mac下geekbench5跑分情况 https://www.hawcat.cn/articles/77
> 
> 文不对题？

修改了哈

**Comment by M69W** [comment]
性能模式是可以调的
有双系统的话，在 macOs 调整 后，重启直接 进 Windows，用 联想管家 看
