### ISSUE TITLE
型号更新为MacBookAir9,1后无法睿频

### ISSUE THREAD

**Issue by lymansix** [daliansky/XiaoXinPro-13-hackintosh#21]
型号更新为MacBookAir9,1后无法睿频
使用cpu-s测试后：
---------------------------------
您的型号标识符：MacBookAir9,1
您的处理器型号：i5-10210U
您的睿频状态为：未睿频
您的变频档位共：1个
具体档位如下：
0 MHz
---------------------------------
上一个版本测试可以睿频
有什么办法可以解决吗？

**Comment by Hush-vv** [comment]
是拿cpu-s测试的吗？

**Comment by M69W** [comment]
建议使用：[Intel® Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget) 测试

**Comment by M69W** [comment]
/issues/89
