### ISSUE TITLE
i7 空载状态下gfx avg来回横跳

### ISSUE THREAD

**Issue by lovelinessmoe** [daliansky/XiaoXinPro-13-hackintosh#210]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/32808610/179885481-8d08bbed-ed72-4dda-9ad1-775fcd6a555d.png">

**Comment by lovelinessmoe** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/32808610/179885782-36b1e204-1d4f-4dd0-b561-55c57e204d02.png">
这是看视频时候的状态

**Comment by lovelinessmoe** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/32808610/179885893-f58c803b-9b63-49f6-b7fa-d0ad7357f84d.png">
这是看视频时候的状态

**Comment by lovelinessmoe** [comment]
之前通过 #89 的SSDT-PLUG-_SB.PR00进行操作并且定制了CPUfrind
现在更改SSDT-PLUG-_SB.PR00为[SSDT-PLUG-HWP16.2-_SB.PR00.aml](https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/2f1052c95e2b4c124fc465ed49e3cb656d7404e4/EFI/EFI_OC_0.6.0_for_xiaoxinPro13_by_daliansky/OC/ACPI/SSDT-PLUG-HWP16.2-_SB.PR00.aml),虽然不知道这个和别的的区别是什么,删除了CPUfrined和data现在大致恢复正常,但是不能睿频4.0以上
<img width="403" alt="image" src="https://user-images.githubusercontent.com/32808610/180189946-c5696a7d-649c-44df-af3d-0c50799cf67d.png">

**Comment by lovelinessmoe** [comment]
不对劲,应该是没解决,这张图正常是因为正在看视频

**Comment by surill** [comment]
> 不对劲,应该是没解决,这张图正常是因为正在看视频

用CPUfrined和data可以睿频4.0以上吗？

**Comment by lovelinessmoe** [comment]
> 

用原来的dsdt可以,换回relase里的不行
