### ISSUE TITLE
［已解决］OC: Failed to bootstrap SB NVRAM values. Invalid Parameter

### ISSUE THREAD

**Issue by Byvm815** [daliansky/XiaoXinPro-13-hackintosh#211]
EFI从0.7.9升级到0.8.0遇到问题
在编辑时没有注意，使用的occ和配置文件版本不一致，导致0.8.0无法引导进入系统。
但在我改回使用0.7.9时，遇到下图问题，0.7.9是用的备份，之前一直能正常使用。
![7B143035-F446-452E-BC4B-0082798C225E](https://user-images.githubusercontent.com/99241417/180975805-98431394-b233-4c76-9f0e-82cf76b88d55.jpeg)
在查阅资料和搜索相关问题时，只在外网找到一篇相关[文章](https://www.tonymacx86.com/threads/monterey-install-failing-via-oc-and-only-preboot-available-via-clover.320048/page-6) ，目前在查看oc官方文档，如果有相同问题的小伙伴可以和我一起探讨（帮帮我）。

**Comment by M69W** [comment]
尝试 在 引导界面 Reset NVRAM 一下。

**Comment by Byvm815** [comment]
> 尝试 在 引导界面 Reset NVRAM 一下。
> 
> 如果可以，找出原版对比你修改过的？

找了我的历史版本的efi，现在能进了。就是不知道问题在哪

**Comment by M69W** [comment]
试试 [beyond compare](https://www.baidu.com/s?wd=beyond%20compare) 对比一下差异

**Comment by gawinwong** [comment]
想请问楼主，目前有什么进展，我也遇到了这个问题

**Comment by gawinwong** [comment]
> I was able to solve the problem by putting the following items in the DELETE of NVRAM
4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14:BridgeOSHardwareModel

https://github.com/acidanthera/bugtracker/issues/1868 通过这个解决了

**Comment by StarVase** [comment]
您好，怎样在无法进入引导的情况下重置nvram？
谢谢了！
