### ISSUE TITLE
請問有人還在用big sur嗎⋯求救

### ISSUE THREAD

**Issue by Pablolu430** [daliansky/XiaoXinPro-13-hackintosh#213]
如題 我從monterey回big sur了... 為了藍芽和airdrop...
可是現在開機順序有點玄 不知道這是啥原因 以前沒碰過這情況...
macos 11.6.8

https://ntutedutw-my.sharepoint.com/:v:/g/personal/t105332038_ntut_edu_tw/EU2jCZToM9NKg0dgFuAcO0oBz7TdGu88cs8HClG9ftYJWQ?e=oGsOAO

**Comment by surill** [comment]
设置——安全性与隐私——文件保险箱——关闭，即可解决

**Comment by BronzedOreo** [comment]
> 安全性

大佬，提问区到处都能看见你，我想问一下，我在提问区看到一个系统截屏，我看那个图片分辨率是2880*1800，是16：10比例，小新Pro13不是2560*1600吗，怎么可以开到2880*1800吗？还有这个电脑支持1920*1200的hidpi吗？

**Comment by surill** [comment]
> 



> > 安全性
> 
> 大佬，提问区到处都能看见你，我想问一下，我在提问区看到一个系统截屏，我看那个图片分辨率是2880_1800，是16：10比例，小新Pro13不是2560_1600吗，怎么可以开到2880_1800吗？还有这个电脑支持1920_1200的hidpi吗？

不是大佬，也是个菜鸡，你看到的截图不一定是内置显示器，我记得用RDM是可以选择1920/1200的分辨率的，hidpi就是把高物理分辨率虚拟成低分辨率啊
这是我外界的两个显示器，一个没有hidpi，一个有hidpi
<img width="355" alt="image" src="https://user-images.githubusercontent.com/75652673/182054821-1dc0d68e-8569-476b-8bb3-7f51cb20655c.png">

**Comment by BronzedOreo** [comment]
> > 
> 
> > > 安全性
> > 
> > 
> > 大佬，提问区到处都能看见你，我想问一下，我在提问区看到一个系统截屏，我看那个图片分辨率是2880_1800，是16：10比例，小新Pro13不是2560_1600吗，怎么可以开到2880_1800吗？还有这个电脑支持1920_1200的hidpi吗？
> 
> 不是大佬，也是个菜鸡，你看到的截图不一定是内置显示器，我记得用RDM是可以选择1920/1200的分辨率的，hidpi就是把高物理分辨率虚拟成低分辨率啊 这是我外界的两个显示器，一个没有hidpi，一个有hidpi <img alt="image" width="355" src="https://user-images.githubusercontent.com/75652673/182054821-1dc0d68e-8569-476b-8bb3-7f51cb20655c.png">

我懂了 成功hidpi之后的显示 分辨率是UI看起来的两倍，再请问一下为什么我的不现实刷新率 我看到有一些人的显示刷新率

**Comment by surill** [comment]
> 我懂了 成功hidpi之后的显示 分辨率是UI看起来的两倍，再请问一下为什么我的不现实刷新率 我看到有一些人的显示刷新率

不显示刷新率应该是你的显示器只支持一个刷新率吧（猜的）

**Comment by Pablolu430** [comment]
> 设置——安全性与隐私——文件保险箱——关闭，即可解决

太感謝了 話說新版的oc在monterey上 可以airdrop了嗎 🥺

**Comment by Pablolu430** [comment]
> > 
> 
> > > 安全性
> > 
> > 
> > 大佬，提问区到处都能看见你，我想问一下，我在提问区看到一个系统截屏，我看那个图片分辨率是2880_1800，是16：10比例，小新Pro13不是2560_1600吗，怎么可以开到2880_1800吗？还有这个电脑支持1920_1200的hidpi吗？
> 
> 不是大佬，也是个菜鸡，你看到的截图不一定是内置显示器，我记得用RDM是可以选择1920/1200的分辨率的，hidpi就是把高物理分辨率虚拟成低分辨率啊 这是我外界的两个显示器，一个没有hidpi，一个有hidpi <img alt="image" width="355" src="https://user-images.githubusercontent.com/75652673/182054821-1dc0d68e-8569-476b-8bb3-7f51cb20655c.png">

![截圖 2022-10-14 01 24 52](https://user-images.githubusercontent.com/49023418/195665198-5d04dcab-ff5b-462f-9b70-64c823dba073.jpg)

你看到的截圖也有可能是內置顯示器 薛定諤的貓嗎？🤣

**Comment by surill** [comment]
airdrop 应该是要看网卡吧，网卡免驱或者驱动合适一直都可以正常airdrop

2022年10月14日 01:24，Pablolu430 ***@***.***> 写道：


设置——安全性与隐私——文件保险箱——关闭，即可解决

太感謝了 話說新版的oc在monterey上 可以airdrop了嗎 🥺
