### ISSUE TITLE
使用v306 配合yoga驱动 截图键和小星星不能用

### ISSUE THREAD

**Issue by lovelinessmoe** [daliansky/XiaoXinPro-13-hackintosh#214]
问一下大家也是这样吗,还是只有我自己是这样的

**Comment by lovelinessmoe** [comment]
刚刚在https://ydkb.io/ 看了下发现和PrtSc相同绑定的Ins插入键也没有绑定

**Comment by lovelinessmoe** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/32808610/183799099-1e74104c-eb09-43b7-a254-b11bb876599a.png">
通过修改SSDT-RMCF-PS2Map-LenovoPRO13的DSDT将截图键映射到了F13

但是Ins键还在看

**Comment by lovelinessmoe** [comment]
Ins 不能进行映射
小星星也找不到对应的键盘扫描码

**Comment by lovelinessmoe** [comment]
e052对应的就是ins的扫描码,即使映射到了0x52 或者0x92(e052)还是不能触发
[键盘映射](https://github.com/daliansky/OC-little/tree/master/07-PS2%E9%94%AE%E7%9B%98%E6%98%A0%E5%B0%84%E5%8F%8A%E4%BA%AE%E5%BA%A6%E5%BF%AB%E6%8D%B7%E9%94%AE)

**Comment by lovelinessmoe** [comment]
在[OC-lite特殊补丁](https://github.com/daliansky/OC-little/blob/master/18-%E5%93%81%E7%89%8C%E6%9C%BA%E5%99%A8%E7%89%B9%E6%AE%8A%E8%A1%A5%E4%B8%81/18-2-%E5%B0%8F%E6%96%B0PRO13%E7%89%B9%E6%AE%8A%E8%A1%A5%E4%B8%81/SSDT-RMCF-PS2Map-LenovoPRO13.dsl)中找到了每个按键的描述
```
"e037=0", //disable Fn+S
"e052=0", //disable PrtSc
"46=0",   //disable Fn+C
"e045=0"  //disable Fn+P
```

**Comment by lovelinessmoe** [comment]
> 

但是在我这里Fn+s 并不能触发e037 ,反而是截图键

我默认是f模式不是功能模式

**Comment by M69W** [comment]
这部分SSDT本属于自定义的功能，不过并没过多处理，不太清楚具体的表现。
