### ISSUE TITLE
menterey12.5.1 最新版3.0.6efi 耗电巨大。。

### ISSUE THREAD

**Issue by Kanepan** [daliansky/XiaoXinPro-13-hackintosh#217]
硬盘是亿联的， 用了sleepwithoutbluetoothandwifi  用每小时大概 9%的电 。。。 
折腾了各种方法都是 耗电巨大。  
求大佬帮忙 。 难到真的是硬盘的问题 ？  
另外求加一下群。 群好像都满了

**Comment by akFace** [comment]
待机一晚上耗电50%+
这个真的太离谱了，比win下耗电严重多了

**Comment by MagicianLjj** [comment]
群里说去掉启动参数会减少耗电 一小时2%耗电是正常的 我删了之后粗略计算了一下 基本上2%  之前8%以上
然后睡眠后发热情况也有好转 不过没有仔细测 
具体跟v3.0.1 一次更新有关
添加 boot-args 参数 forceRenderStandby=0 详情看 https://github.com/acidanthera/bugtracker/issues/1193
可以尝试一下

**Comment by cytown** [comment]
> 群里说去掉启动参数会减少耗电 一小时2%耗电是正常的 我删了之后粗略计算了一下 基本上2% 之前8%以上 然后睡眠后发热情况也有好转 不过没有仔细测 具体跟v3.0.1 一次更新有关 添加 boot-args 参数 forceRenderStandby=0 详情看 [acidanthera/bugtracker#1193](https://github.com/acidanthera/bugtracker/issues/1193) 可以尝试一下

👍，这就去试试。

**Comment by cytown** [comment]
不过我用的是071版本的OC，不知道是否管用。

**Comment by cytown** [comment]
昨晚测试了一下，不好使，或者说071的OC在Big Sur下不要用，平常13小时还剩40%多，用了后直接0%关机了。

**Comment by MagicianLjj** [comment]
> 
你可能看错我的意思了 我那句是引用了那个版本release里更新内容的原话  我想表达的是要清空启动参数 什么都不加
然后你平时13小时 剩下40%还不算离谱 因为小新本身就不能正常 s3睡眠 每小时耗电跟硬盘 还有wifi 蓝牙有关
而我回复@Kanepan 说的是每小时耗电超过9%这种异常情况，平时我的电脑睡眠一晚上就关机了，而且电脑发热明显，但是这个现象并不是刚开始装黑苹果就出现的，是在某次efi更新之后出现的
我稍微研究了一下这个参数 是关于核显省电的  在一些主板bios里也叫RC6  在v3.0.1更新的时候 加了forceRenderStandby=0会强制关闭rc6 导致核显最低频率是299mhz  可以用一些传感器软件看一下 intel IGPU的频率会被锁定在这个频率以上 
这样就会导致核显功耗增加 至少 1w  所以不论是使用时的续航和伪睡眠都会受到影响
不加这个参数的时候 核显频率是可以到0的
如果你没有理解错我说的，也的确清空了参数我就不太能解释了
另外希望有其他看到的人也帮忙测试一下

我目前是 menterey12.6 最新的efi  oc 8.4

**Comment by cytown** [comment]
我没升级bigsur之前，每小时待机耗电大概1%-1.5%。此外，071以后的版本基本都会IGPU出现crash。。。频率还挺高。

改成071+bigsur配合后，半个月不重启应该是比较容易做到的。唯一就是待机功耗还是比较高。待机后，摸机器壳还是温温的。

不过看wakelock又没有任何日志。

**Comment by MagicianLjj** [comment]
我目前待机7小时 耗电21% 基本上每小时3%  如果按照晚上待机12小时来算  能够接受  比之前没电关机好太多了

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
