### ISSUE TITLE
大佬可以帮看下崩溃报告吗，最近崩溃俩次了，崩溃重启出现五国，但是能正常重新启动

### ISSUE THREAD

**Issue by qinglt** [daliansky/XiaoXinPro-13-hackintosh#219]
panic(cpu 4 caller 0xffffff801edc4996): Kernel trap at 0xffffff801eb010ba, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x000000003630d000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0xffffff9381ce3370, RCX: 0x0000000000000100, RDX: 0x0000000000000100
RSP: 0xffffffa0c41fb9d8, RBP: 0xffffffa0c41fbd10, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0xffffffa0b04ac780, R10: 0x0000000000005c78, R11: 0xffffff86b5b0e090
R12: 0x00000000e00002cc, R13: 0xffffffa0a61d1090, R14: 0xffffff8023526050, R15: 0xffffff86b5d85b40
RFL: 0x0000000000010246, RIP: 0xffffff801eb010ba, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000002, Fault CPU: 0x4, PL: 0, VF: 1

Backtrace (CPU 4), Frame : Return Address
0xffffffa0c41fb3f0 : 0xffffff801ec8cfdd mach_kernel : _handle_debugger_trap + 0x3fd
0xffffffa0c41fb440 : 0xffffff801edd3fd3 mach_kernel : _kdp_i386_trap + 0x143
0xffffffa0c41fb480 : 0xffffff801edc45ca mach_kernel : _kernel_trap + 0x55a
0xffffffa0c41fb4d0 : 0xffffff801ec31a2f mach_kernel : _return_from_trap + 0xff
0xffffffa0c41fb4f0 : 0xffffff801ec8c7fd mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffa0c41fb610 : 0xffffff801ec8caf3 mach_kernel : _panic_trap_to_debugger + 0x273
0xffffffa0c41fb680 : 0xffffff801f49cdca mach_kernel : _panic + 0x54
0xffffffa0c41fb6f0 : 0xffffff801edc4996 mach_kernel : _sync_iss_to_iks + 0x2c6
0xffffffa0c41fb870 : 0xffffff801edc467d mach_kernel : _kernel_trap + 0x60d
0xffffffa0c41fb8c0 : 0xffffff801ec31a2f mach_kernel : _return_from_trap + 0xff
0xffffffa0c41fb8e0 : 0xffffff801eb010ba 
0xffffffa0c41fbd10 : 0xffffff8023526232 com.zxystd.AirportItlwm : __ZN6ItlIwx15_iwx_start_taskEP8OSObjectPvS2_S2_S2_ + 0x1e2
0xffffffa0c41fbda0 : 0xffffff801f3eff35 mach_kernel : __ZN13IOCommandGate13attemptActionEPFiP8OSObjectPvS2_S2_S2_ES2_S2_S2_S2_ + 0xb5
0xffffffa0c41fbe00 : 0xffffff80235263a1 com.zxystd.AirportItlwm : __ZN6ItlIwx9iwx_startEP6_ifnet + 0x81
0xffffffa0c41fbe50 : 0xffffff802356ac11 com.zxystd.AirportItlwm : __ZN12AirportItlwm12outputPacketEP6__mbufPv + 0x221
0xffffffa0c41fbeb0 : 0xffffff802356a982 com.zxystd.AirportItlwm : __ZN12AirportItlwm11outputStartEP18IONetworkInterfacej + 0xc2
0xffffffa0c41fbf20 : 0xffffff80214efcb9 com.apple.iokit.IONetworkingFamily : __ZN18IONetworkInterface16drainOutputQueueEP7__ifnetP19IONetworkController + 0x5f
0xffffffa0c41fbf60 : 0xffffff801ef9d2aa mach_kernel : _ifnet_attach + 0x285a
0xffffffa0c41fbfa0 : 0xffffff801ec3113e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.4)[85A525E4-C60E-345C-B651-6266952AFCA5]@0xffffff80214e0000->0xffffff80214f6fff
         com.zxystd.AirportItlwm(2.1)[F01B7CA4-C327-3B12-B582-87217AFD92E6]@0xffffff80234aa000->0xffffff8024443fff
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[CAB76D43-3874-3057-9F2C-3C3FEA43B495]@0xffffff8020713000->0xffffff8020892fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[85A525E4-C60E-345C-B651-6266952AFCA5]@0xffffff80214e0000->0xffffff80214f6fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[4E85D41F-6AD7-3C24-911C-A8B80B599F86]@0xffffff802176c000->0xffffff8021794fff

Process name corresponding to current thread: kernel_task
Boot args: keepsyms=1 forceRenderStandby=0 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20G165

Kernel version:
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
Kernel UUID: C2591F4E-EE82-33CC-8C59-DB81D9AD80DD
KernelCache slide: 0x000000001ea00000
KernelCache base:  0xffffff801ec00000
Kernel slide:      0x000000001ea10000
Kernel text base:  0xffffff801ec10000
__HIB  text base: 0xffffff801eb00000
System model name: MacBookPro15,4 (Mac-53FDB3D8DB8CA971)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 5845176207534
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000550efa6cebe
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x000000065b985100 0x0000000000000000
last started kext at 6998660542: >AudioAUUC	1.70 (addr 0xffffff7fb9826000, size 12288)
last stopped kext at 453556108718: >IOPlatformPluginLegacy	1.0.0 (addr 0xffffff7fb9b9e000, size 36864)
loaded kexts:
as.acidanthera.voodoo.driver.PS2Keyboard	2.2.8
me.kishorprins.VoodooInput	1.1.3
com.alexandred.VoodooI2CHID	1
com.zxystd.!I!BFirmware	2.1.0
com.zxystd.AirportItlwm	2.1.0
com.alexandred.VoodooI2C	2.7
as.acidanthera.voodoo.driver.PS2!C	2.2.8
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.2.9
as.acidanthera.BrightnessKeys	1.0.2
com.alexandred.VoodooI2CServices	1
as.vit9696.!AALC	1.7.1
ru.usrsse2.SMCLightSensor	1.2.9
ru.usrsse2.SMCBatteryManager	1.2.9
as.vit9696.VirtualSMC	1.2.9
as.vit9696.WhateverGreen	1.5.8
as.vit9696.Lilu	1.6.0
>AudioAUUC	1.70
@fileutil	20.036.15
>!AHDA	283.15
>!APlatformEnabler	2.7.0d0
>AGPM	122.1
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
@filesystems.ntfs	3.14.3
>!AUpstreamUserClient	3.6.8
>!AGraphicsDevicePolicy	6.3.5
@AGDCPluginDisplayMetrics	6.3.5
>!A!IKBLGraphics	16.0.5
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
|IO!BSerialManager	8.0.5d7
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!ABacklight	180.3
>!AMCCSControl	1.14
>!ASMCLMU	212
>!A!IPCHPMC	2.0.1
>!A!ISlowAdaptiveClocking	4.0.0
>!A!ICFLGraphicsFramebuffer	16.0.5
>!ATopCaseHIDEventDriver	4050.1
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.100.11
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
@filesystems.apfs	1677.141.2
@private.KextAudit	1.0
>!AHPET	1.8
>!ARTC	2.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	311
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@kext.triggers	1.0
>!AGraphicsControl	6.3.5
|IOAVB!F	940.4
|IOEthernetAVB!C	1.1.0
>!ABacklightExpert	1.1.0
|IONDRVSupport	585.1
>!ASMBus!C	1.0.18d1
|IOSerial!F	11
@plugin.IOgPTPPlugin	985.2
@!AGPUWrangler	6.3.5
|IOSlowAdaptiveClocking!F	1.0.0
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>!ASMBusPCI	1.0.14d1
|IOAccelerator!F2	442.9
@!AGraphicsDeviceControl	6.3.5
|IOGraphics!F	585.1
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!AActuatorDriver	4440.3
>!AMultitouchDriver	4440.3
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4050.1
>IO!BHIDDriver	8.0.5d7
>usb.IOUSBHostHIDDevice	1.2
>usb.!UHub	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	8.0.5d7
|IO!BHost!CUSBTransport	8.0.5d7
|IO!BHost!CTransport	8.0.5d7
>!UMergeNub	900.4.2
>!ABSDKextStarter	3
|IOSurface	290.8.1
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AXsanScheme	3
|IONVMe!F	2.1.0
>!AEFINVRAM	2.1
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
$!AImage4	3.0.0
|IOHID!F	2.0.0
|IOSMBus!F	1.1
|IOTimeSync!F	985.2
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.5d7
|IOReport!F	47
|IO!BPacketLogger	8.0.5d7
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.141.1
|IOUSBMass!SDriver	184.140.2
|IOSCSIBlockCommandsDevice	436.140.1
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.140.1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
