### ISSUE TITLE
OpenCore 多系统引导支持GUI

### ISSUE THREAD

**Issue by wulie88** [daliansky/XiaoXinPro-13-hackintosh#22]
https://github.com/n-d-k/NdkBootPicker 是一个OpenCore GUI项目，我按照教程操作没有成功，也联系过作者，回复是版本不匹配 https://github.com/n-d-k/NdkBootPicker/issues/12

希望了解EFI编译同学帮我处理下，编译一个完整的小新Pro能用的版本，后续大家可以出几个主题。

尽管OC定位是原生效果，但是也有多系统引导的需求。

**Comment by mrzilong** [comment]
> [https://github.com/ndk/NdkBootPicker](https://github.com/n-d-k/NdkBootPicker)是一个OpenCore GUI项目，我遵循教程操作没有成功，也联系过作者，回复是版本不匹配[ndk / NdkBootPicker＃12](https://github.com/n-d-k/NdkBootPicker/issues/12)
> 
> 希望了解EFI编译同学帮我处理下，编译一个完整的小新Pro能用的版本，后续大家可以出几个主题。
> 
> 尽管OC定位是原生效果，但也有多系统引导的需求。

QQ群：946132482内有已经配置好的NdkBootPicker版本

**Comment by M69W** [comment]
[releases v2.1](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1)
