### ISSUE TITLE
2019 i7用上i5的显卡id暂时不花屏了

### ISSUE THREAD

**Issue by Jesselee0322** [daliansky/XiaoXinPro-13-hackintosh#220]
**AAPL,ig-platform-id : 00009B3E
device-id: 9B3E0000**

之前用的i7的三个，都测试了，过一晚上再开机，总是花屏（一分为四）
试了上面i5的反倒暂时没问题了

**Comment by ouruomiya** [comment]
现在用了一段时间还花屏吗？我以前就是一直花屏，所以没有用macos了

**Comment by Jesselee0322** [comment]
> 现在用了一段时间还花屏吗？我以前就是一直花屏，所以没有用macos了

不花了，只是偶尔开机苹果logo进度条那里闪一下，其他没问题

**Comment by ouruomiya** [comment]
谢谢，请问你现在苹果系统是那个版本啦？

**Comment by Jesselee0322** [comment]
> 谢谢，请问你现在苹果系统是那个版本啦？

用的最新的13.2.1了，就开机那里偶尔微闪一下，用着挺好的
