### ISSUE TITLE
有独显会有影响吗？

### ISSUE THREAD

**Issue by haoyaxuan** [daliansky/XiaoXinPro-13-hackintosh#221]
目前在海鲜市场看，很少卖不带独显的。
买独显的有两点担忧：
1.耗点方面，小新无法休眠，独显耗点大户。
2.长期在Macos下办公，会不会对独显造成损失，致使主板受损。

**Comment by haoyaxuan** [comment]
看了BIOS教程，可以直接在BIOS屏蔽独显。

**Comment by 2020jia** [comment]
兄弟，双系统能只在mac下屏蔽独显吗？
