### ISSUE TITLE
有人升级MacOS 13吗

### ISSUE THREAD

**Issue by hongbaio** [daliansky/XiaoXinPro-13-hackintosh#224]
有人升级MacOS 13吗，感觉怎么样，可以升级吗

**Comment by Sun1090** [comment]
084直接升
<img width="316" alt="image" src="https://user-images.githubusercontent.com/51160517/199422762-100cd06d-4c09-45cb-8e6f-676330f5b2b8.png">

**Comment by hongbaio** [comment]
> 084直接升 <img alt="image" width="316" src="https://user-images.githubusercontent.com/51160517/199422762-100cd06d-4c09-45cb-8e6f-676330f5b2b8.png">

好的，这下放心升级啦，谢谢

**Comment by Agoines** [comment]
原装的蓝牙和 WIFI 还能用嘛

**Comment by hongbaio** [comment]
> 
不清楚，我换了白果卡，可以去远景论坛找一下相关的帖子

**Comment by Agoines** [comment]
明白了，我最后更新的 alpha 版本，还是感谢解答
