### ISSUE TITLE
0.8.6成功在线升级Ventura13.0

### ISSUE THREAD

**Issue by medlar01** [daliansky/XiaoXinPro-13-hackintosh#225]
感谢大佬辛苦维护OC，太方便了

**Comment by yanxu117** [comment]
有没有什么问题？

**Comment by medlar01** [comment]
暂时没发现问题

yanxu117 ***@***.***> 于2022年11月7日周一 11:54写道：

**Comment by bupthui** [comment]
> 

分享下包含intel网卡驱动的OC吧

**Comment by medlar01** [comment]
网卡和蓝牙要换免驱的

bupthui ***@***.***> 于2022年11月10日周四 14:03写道：
