### ISSUE TITLE
黑果0.8.6，使用有线耳机，声音无法辨识

### ISSUE THREAD

**Issue by bupthui** [daliansky/XiaoXinPro-13-hackintosh#227]
黑果0.8.6，使用有线耳机，刚开机声音正常，可以正常使用，如果一会儿不用，等机子休眠黑屏，再重新按电源激活电脑，声音就变得特别小，而且音质变得奇差无法辨识。如果拔掉有线耳机，外放没有任何问题。

**Comment by bupthui** [comment]
0.8.8版本也是一样的问题  电脑休眠回来后，耳机播放声音奇差无法辨识

**Comment by M69W** [comment]
[小新pro13的声卡ID](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/%E5%A3%B0%E5%8D%A1)
