### ISSUE TITLE
BCM94360Z4在最新版本win10家庭中文版无法驱动蓝牙

### ISSUE THREAD

**Issue by EvilMoOd** [daliansky/XiaoXinPro-13-hackintosh#231]
机型是联想小新pro13 2019 i7-10710u版本
[BCM94360Z4/BCM94360Z3_For_Windows_x64_Drivers_v1.0.0.3.zip](https://pics.daliansky.net/d/xD0Ar91B/blog/BCM94360Z4/BCM94360Z4_and_BCM94360Z3_for_Windows10_x64_v1.0.0.3.zip?download=1)用的是这个压缩包里的驱动
![img](https://user-images.githubusercontent.com/98245255/210473722-3ac72e43-cd10-4028-87a8-be0cda310d49.png)

**Comment by M69W** [comment]
你是怎么安装蓝牙驱动的（过程）？

**Comment by EvilMoOd** [comment]
![image](https://user-images.githubusercontent.com/98245255/210496502-7cc7a2f6-5832-4059-afd8-774db20eae29.png)
这个启动然后下面两个选项，选哪个都没有用
![image](https://user-images.githubusercontent.com/98245255/210496601-1cad3c3e-69b3-4ff5-b036-671b6dd00d04.png)
安装之后应用里显示是这个，wifi的驱动能用，但是蓝牙这个驱动不了
![image](https://user-images.githubusercontent.com/98245255/210496630-f757366c-2370-435e-96b4-ddb72a7395ef.png)
@M69W

**Comment by M69W** [comment]
这就不太清楚了。
不过你看下教程有没有说；如果没有的话，估计要问下卖家了。

**Comment by EvilMoOd** [comment]
解决了，找了卖家要的驱动打上就可以了
