### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by zui-lang** [daliansky/XiaoXinPro-13-hackintosh#232]
据了解，有一个付费群好像已经修复睡眠问题，五小时睡眠耗电0，不知道大佬能不能跟进一下，新年快乐

**Comment by M69W** [comment]
哪个群，发一下？

**Comment by zui-lang** [comment]
我找到github链接了

https://github.com/xuanxue11/xuanxue

**Comment by M69W** [comment]
是另外一个小新黑苹果群
我加的群太多了，就退了。

认准宪武的EFI 就没错了。
旧版本 是这个[EFI-OC088-PRO13-10210-4360.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
新版还没更新到 GitHub 上，
最近更新

**Comment by zui-lang** [comment]
不太懂，就想知道睡眠是修复了吗，mac好久没用就是因为续航问题

**Comment by lovelinessmoe** [comment]
睡眠没有修复 修复的是休眠 指 s4睡眠
而且也不是xuanxue修复的 还是宪武大佬
主要是在EFI配置中增加一个保留内存

**Comment by M69W** [comment]
> 睡眠没有修复 修复的是休眠 指 s4睡眠 而且也不是xuanxue修复的 还是宪武大佬 主要是在EFI配置中增加一个保留内存

"他们"是同一人

**Comment by lovelinessmoe** [comment]
> > 睡眠没有修复 修复的是休眠 指 s4睡眠 而且也不是xuanxue修复的 还是宪武大佬 主要是在EFI配置中增加一个保留内存
> 
> "他们"是同一人
> 
> 

有这事！！

![784ade475d724d35.gif](https://user-images.githubusercontent.com/32808610/217743810-bf1166b1-7c3d-40ee-b1df-412f722ccd8c.gif)

**Comment by M69W** [comment]
不妨对比一下 EFI

**Comment by zui-lang** [comment]
我想换一块固态，幻影的，不知道对mac有没有影响

**Comment by M69W** [comment]
不清楚。
