### ISSUE TITLE
EFI3.0.9插入鼠标后无法休眠

### ISSUE THREAD

**Issue by hongbaio** [daliansky/XiaoXinPro-13-hackintosh#238]
在USB口插入鼠标后合盖，观察到电源键灯一直亮，第二天发现电池耗尽。在USB口未插入任何设备后，盒盖后发现1分钟内电源键灯熄灭，合盖发现进入休眠

**Comment by M69W** [comment]
系统？
插着电源？

**Comment by hongbaio** [comment]
系统为macos 13.1 ，没插电源

**Comment by hongbaio** [comment]
> 系统？ 插着电源？

系统为macos 13.1 ，没插电源

**Comment by M69W** [comment]
群里有更新 了 EFI，不妨先试试

**Comment by hongbaio** [comment]
> 群里有更新 了 EFI，不妨先试试

可以关闭问题了，重置bios 重新设置好后不再出现此问题
