### ISSUE TITLE
youtube全屏问题

### ISSUE THREAD

**Issue by handsomebroB** [daliansky/XiaoXinPro-13-hackintosh#24]
youtube视频全屏时候会闪烁，近几个版本都是这样子的，不知道是什么问题？

**Comment by M69W** [comment]
哪一个版本是好的

**Comment by handsomebroB** [comment]
不太确定 因为突然出现的这个问题 现在有点怀疑是chrome的原因 其他的视频软件都没有这个问题

**Comment by M69W** [comment]
不妨试试safari？

**Comment by nujabse** [comment]
试试关掉 hidpi？我的开启hidpi 貌似就有这个闪烁问题

**Comment by nujabse** [comment]
试过safari 和 chrome 全屏播放 YouTube 都会有闪屏的问题，使用的是最新的 OC

**Comment by M69W** [comment]
我那边没有这个情况
小新pro13 i7 15.4 + hidpi +最新oc

**Comment by nujabse** [comment]
@handsomebroB 试试在设置里面把鼠标指针调大一些看看能不能解决问题。我在网上搜了一圈有很多 mac 用户也有这方面的问题。最终在 [macrumors](https://forums.macrumors.com/threads/screen-flicker-when-watching-video-fullscreen-on-safari-after-updating-to-10-14-6.2190943/) 上看到了一个回答：

> Dunno if this post of mine helps anyone but I updated my MBP (early 2015") from Sierra to High Sierra 10.13.6 and short while after that noticed that when watching a movie in iTunes the screen would flicker constantly from normal to brighter screen (kinda hard to explain...). I did some research and discovered that turning off subtitles helped a bit to minimize the flicker but it was still there. Also not using fullscreen helped. But as I wanted to use subtitles and fullscreen while watching movies, I continued seeking answers to this effin' annoying bug and FINALLY I FOUND A SOLUTION: all I had to do was to go to Settings - Accessibility - Display -> Change the size of the cursor bigger! After that little change, the flickerin

> 
我设置了之后就再没出现过闪屏了，仅供参考。

**Comment by iugo** [comment]
我也遇到了这个问题. 只在全屏出现, 如果不全屏或者把统计信息打开就不会闪烁.

**Comment by cytown** [comment]
同样碰到了，修改一下cursor就行，这个方法好，简单没有副作用。
