### ISSUE TITLE
iMessage无法使用，登陆几秒后返回登陆界面

### ISSUE THREAD

**Issue by ReginaldZZZ** [daliansky/XiaoXinPro-13-hackintosh#244]
我也不知道跟前面蓝牙有没有关系，第一次登陆Apple ID是正常的，过了几天突然就如题。
然后网上办法试了很多也重装了还是如题的问题。

**Comment by M69W** [comment]
之前是正常，说明之前的配置没问题。
这种常见于苹果服务，可能是网络问题。
