### ISSUE TITLE
2.1 clover 每次开机都会报错"您的电脑因出现问题而重新启动"

### ISSUE THREAD

**Issue by anjing529** [daliansky/XiaoXinPro-13-hackintosh#26]
小新pro 2020 i5版本 2.0的efi正常  升级到2.1 clover启动   每次都是正常关机   开机或重启 都会报错  详细报错如下 望大佬帮看下啥原因  感谢

panic(cpu 0 caller 0xffffff800ca4c32a): Kernel trap at 0xffffff7f90137e92, type 13=general protection, registers:
CR0: 0x0000000080010033, CR2: 0x00000001062fb000, CR3: 0x000000002224f000, CR4: 0x00000000003626e0
RAX: 0x3f0011c111c40d72, RBX: 0x0000000000000000, RCX: 0x0000000000000002, RDX: 0x0000000000000800
RSP: 0xffffff820aa53d70, RBP: 0xffffff820aa53e00, RSI: 0x2956891f5c2046a9, RDI: 0xffffff80412d0000
R8:  0x0000000000000001, R9:  0x0000000000000013, R10: 0x0000000000000002, R11: 0xffffff803e1bf710
R12: 0x0000000000000000, R13: 0xffffff8040fbe000, R14: 0x0000000000000000, R15: 0xffffff80412d0000
RFL: 0x0000000000010286, RIP: 0xffffff7f90137e92, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00000001062fb000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 0

Backtrace (CPU 0), Frame : Return Address
0xffffff800c751220 : 0xffffff800c9215cd mach_kernel : _handle_debugger_trap + 0x49d
0xffffff800c751270 : 0xffffff800ca5a3c5 mach_kernel : _kdp_i386_trap + 0x155
0xffffff800c7512b0 : 0xffffff800ca4bf7e mach_kernel : _kernel_trap + 0x4ee
0xffffff800c751300 : 0xffffff800c8c7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff800c751320 : 0xffffff800c920c97 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff800c751420 : 0xffffff800c921087 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff800c751470 : 0xffffff800d0c2c7c mach_kernel : _panic + 0x54
0xffffff800c7514e0 : 0xffffff800ca4c32a mach_kernel : _sync_iss_to_iks + 0x2aa
0xffffff800c751660 : 0xffffff800ca4c028 mach_kernel : _kernel_trap + 0x598
0xffffff800c7516b0 : 0xffffff800c8c7a40 mach_kernel : _return_from_trap + 0xe0
0xffffff800c7516d0 : 0xffffff7f90137e92 com.apple.driver.AirPort.BrcmNIC : _osl_wificc_logDebug + 0x60
0xffffff820aa53e00 : 0xffffff7f9013b8c7 com.apple.driver.AirPort.BrcmNIC : __ZN15AirPort_BrcmNIC5probeEP9IOServicePi + 0x5d
0xffffff820aa53e40 : 0xffffff800d00841a mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0x7aa
0xffffff820aa53ef0 : 0xffffff800d007ade mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2de
0xffffff820aa53f50 : 0xffffff800d00a296 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x186
0xffffff820aa53fa0 : 0xffffff800c8c713e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.apple.driver.AirPort.BrcmNIC(1400.1.1)[4E7A869F-6FEE-302F-A6FE-8C029D32BE63]@0xffffff7f90117000->0xffffff7f90958fff
            dependency: com.apple.iokit.IOSkywalkFamily(1)[7F77753D-3290-35D5-8603-09DC66FF6BAB]@0xffffff7f8d3a5000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f8d6b3000
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[3F6EDFDE-6EF7-38D8-8006-C4EE6DB4D4B5]@0xffffff7f8d36e000
            dependency: com.apple.driver.corecapture(1.0.4)[48A8A59D-258A-33D7-B950-E5C53F52357B]@0xffffff7f8ee8e000
            dependency: com.apple.driver.mDNSOffloadUserClient(1.0.1b8)[9A4F333F-A231-35F0-8E01-15C2E93D9D18]@0xffffff7f8e760000
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[043696D2-853D-3775-A87F-79C42F324EEB]@0xffffff7f8ffbc000

BSD process name corresponding to current thread: kernel_task
Boot args: keepsyms=1

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x000000000c600000
Kernel text base: 0xffffff800c800000
__HIB  text base: 0xffffff800c700000
System model name: MacBookAir9,1 (Mac-0CFF9C7C2B63DF8D)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 6183513319
last loaded kext at 6179554057: >AirPort.Brcm4360	1400.1.1 (addr 0xffffff7f90959000, size 6189056)
last unloaded kext at 4888808638: >ACPI_SMC_PlatformPlugin	1.0.0 (addr 0xffffff7f8e63b000, size 86016)
loaded kexts:
me.kishorprins.VoodooInput	1.0.5
com.alexandred.VoodooI2CHID	1
org.rehabman.driver.FakePCIID	1.3.15
ru.joedm.SMCSuperIO	1.1.3
as.acidanthera.BrcmPatchRAM3	2.5.3
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.4
com.alexandred.VoodooI2C	2.3
as.acidanthera.voodoo.driver.PS2!C	2.1.4
org.coolstar.VoodooGPIO	1.1
as.vit9696.SMCProcessor	1.1.3
as.acidanthera.BrcmFirmwareStore	2.5.3
as.lvs1974.AirportBrcmFixup	2.0.7
com.alexandred.VoodooI2CServices	1
ru.usrsse2.SMCLightSensor	1
ru.usrsse2.SMCBatteryManager	1
as.vit9696.VirtualSMC	1.1.3
as.vit9696.!AALC	1.5.0
as.vit9696.WhateverGreen	1.3.9
org.acidanthera.NVMeFix	1.0.2
as.vit9696.Lilu	1.4.4
>AirPort.Brcm4360	1400.1.1
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>AirPort.BrcmNIC	1400.1.1
>!AUpstreamUserClient	3.6.8
>!AHDAHardwareConfigDriver	283.15
>!AHDA	283.15
>!A!IKBLGraphics	14.0.5
>!AGraphicsDevicePolicy	5.1.16
@AGDCPluginDisplayMetrics	5.1.16
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.4f6
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!ASMCLMU	212
>!A!ISlowAdaptiveClocking	4.0.0
>!A!ICFLGraphicsFramebuffer	14.0.5
>!A!IPCHPMC	2.0.1
>AGDCBacklightControl	5.1.16
>!ABacklight	180.3
>!AMCCSControl	1.11
>!AFIVRDriver	4.1.0
@private.KextAudit	1.0
>!ATopCaseHIDEventDriver	3430.1
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.101.1
>!ASmartBatteryManager	161.0.0
>!AHPET	1.8
>!ARTC	2.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
|IO80211!F	1200.12.2b1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOSkywalk!F	1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!AGraphicsControl	5.1.16
>!ASMBusPCI	1.0.14d1
>!ASSE	1.0
>IOPlatformPluginLegacy	1.0.0
>!A16X50Serial	3.2
@!AGPUWrangler	5.1.16
|IOSlowAdaptiveClocking!F	1.0.0
|IOAccelerator!F2	438.4.5
>!AHDA!C	283.15
|IOHDA!F	283.15
@!AGraphicsDeviceControl	5.1.16
>!ABacklightExpert	1.1.0
|IONDRVSupport	575.1
>!ASMBus!C	1.0.18d1
|IOGraphics!F	575.1
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.4f6
>!AActuatorDriver	3440.1
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	7.0.4f6
|IO!BHost!CUSBTransport	7.0.4f6
|IO!BHost!CTransport	7.0.4f6
|IO!B!F	7.0.4f6
|IO!BPacketLogger	7.0.4f6
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AXsanScheme	3
|IONVMe!F	2.1.0
>!AEFINVRAM	2.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOSMBus!F	1.1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.101.1
|IOSCSIBlockCommandsDevice	422.101.1
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.101.3
|IOSCSIArchitectureModel!F	422.101.1
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1

**Comment by M69W** [comment]
重建缓存试试，
这情况一般是上次启动异常出现的？

**Comment by bocaikun** [comment]
重刷bios可以解决
