### ISSUE TITLE
Macs Fan Control不能识别风扇

### ISSUE THREAD

**Issue by lrxwisdom01** [daliansky/XiaoXinPro-13-hackintosh#27]
您好！
我用OC安装了MacOS 10.15.4并成功升级到了10.15.5。然后想用Macs Fan Control查看并调整风扇。我试了Macs Fan Control 1.4.X到1.5.X的好几个版本。他们能够识别CPU和SSD的温度，但是都没法识别到风扇。1.5.X的版本提示我需要重置SMC，但是我不知道hackintosh如何重制。
我也尝试了其他能识别风扇的软件，例如Turbo Boost Switcher。同样无法识别到风扇。
还请大佬帮忙查看。多谢！

**Comment by M69W** [comment]
如果之前版本可以，有可能是软件还不没支持10.15.5，也有可能是黑苹果驱动还没支持10.15.5

**Comment by lrxwisdom01** [comment]
谢谢回复。10.15.4和10.15.5都不行。
