### ISSUE TITLE
硬盘为 SKHynix_HFS512GD9TNI-L2A0B 无法安装

### ISSUE THREAD

**Issue by kang558** [daliansky/XiaoXinPro-13-hackintosh#29]
硬盘为 SKHynix_HFS512GD9TNI-L2A0B 无法安装
-config中选择install-xxx之后
一直无限重启，无法进入安装界面
换了很多个EFI和系统镜像也一样

**Comment by kang558** [comment]
可能是未识别硬盘原因，群里有个老哥换了硬盘就好了

**Comment by kang558** [comment]
![QQ图片20200606203619](https://user-images.githubusercontent.com/22288837/83966767-d35d2080-a8ee-11ea-883e-dc9ff77806bf.png)

**Comment by M69W** [comment]
@daliansky 是否此型号不支持黑苹果？

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/84520786-ab165d00-ad06-11ea-8984-4f83e6c96e04.png)

**Comment by kang558** [comment]
我举得海力士应该也可以，关键得弄一个补丁。XPS13就有海力士不识别硬盘的，通过配置可实现安装 [https://github.com/0xHJK/XPS13-9360-i5-8250U-macOS](https://github.com/0xHJK/XPS13-9360-i5-8250U-macOS)

**Comment by M69W** [comment]
没有此配置，建议尝试

**Comment by kang558** [comment]
> 没有此配置，建议尝试

能否帮忙迁移一个配置，我不太会改这个 config.plist  [这个是xps13的海力士固态硬盘配置文件](https://github.com/0xHJK/XPS13-9360-i5-8250U-macOS/blob/master/CLOVER/config-hynix.plist)

**Comment by M69W** [comment]
> > 没有此配置，建议尝试
> 
> 能否帮忙迁移一个配置，我不太会改这个 config.plist [这个是xps13的海力士固态硬盘配置文件](https://github.com/0xHJK/XPS13-9360-i5-8250U-macOS/blob/master/CLOVER/config-hynix.plist)

https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/29#issuecomment-643574617

**Comment by M69W** [comment]
下面帖子有关的说明
https://www.insanelymac.com/forum/topic/319764-guide-dell-xps-15-9550-mojave-1014-1015-quick-installation/

https://github.com/RehabMan/patch-nvme/issues/53
https://github.com/RehabMan/patch-nvme/pull/54/commits/7e4bcae858d1296a519f6cd32777aab2c81b6460

**Comment by kang558** [comment]
多谢，我尝试一下

**Comment by kang558** [comment]
最后还是换了硬盘
