### ISSUE TITLE
amd的CPU可以用这个EFI吗？

### ISSUE THREAD

**Issue by eurly** [daliansky/XiaoXinPro-13-hackintosh#30]
准备入手联想(Lenovo)小新Pro13 2020 锐龙版（6核R5-4600U 16G 512G 2.5K屏）
本人是小白，不太懂黑苹果，只会用别人做好的EFI替换，所以想问一下这个支持AMD的CPU不？

**Comment by M69W** [comment]
暂时不支持，黑苹果建议Intel 版
