### ISSUE TITLE
何时支持macOS 11？

### ISSUE THREAD

**Issue by ltesla** [daliansky/XiaoXinPro-13-hackintosh#31]

**Comment by BosonLiu** [comment]
已支持，请自行阅读readme加群

**Comment by M69W** [comment]
虽然已支持，看到群里的方法跟网上提供的一样，
都不能直接安装，略麻烦，
建议等待一个友好的安装流程或等待引导的支持

**Comment by M69W** [comment]
已支持，但部分SMC感应器驱动不支持
[v2.1.5beta](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1.5beta)
