### ISSUE TITLE
[EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49

### ISSUE THREAD

**Issue by dosyadd** [daliansky/XiaoXinPro-13-hackintosh#32]
I have a laptop Ideapad s540-13iml with i5-10210u and mx250 (as far as I know it's identical to xiaoxin pro 13 2019). I tried to install macOS 10.15.5 through opencore and clover, but installation stucks at [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]. I also tried changing the values of RebuildAppleMemoryMap and SetupVirtualMap as written in this post https://www.reddit.com/r/hackintosh/comments/g7rqt1/if_youre_stuck_at_endrandomseed_or/ ,but still get this error.

**Comment by nekomiao123** [comment]
My computer is xiaoxin pro 13 2019 i7. When I use clover, it works. But when I use the opencore 0.59 to install macOS 10.15.5, the installation stuck at [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]. I tried to use opencore 0.58, it works. Maybe you can try the opencore 0.58 and 0.60.

**Comment by nekomiao123** [comment]
有没有其他老哥遇到了这个问题啊，[EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]，我clover全都正常（虽然每次开机必花屏，但后面正常使用就没问题），据说oc不会怎么花屏也可以用随航，但我oc059不能用，我好想用oc啊，机型配置（2019 xiaoxin pro13 i7 sn750 dw1820a）

**Comment by M69W** [comment]
> I have a laptop Ideapad s540-13iml with i5-10210u and mx250 (as far as I know it's identical to xiaoxin pro 13 2019). I tried to install macOS 10.15.5 through opencore and clover, but installation stucks at [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]. I also tried changing the values of RebuildAppleMemoryMap and SetupVirtualMap as written in this post https://www.reddit.com/r/hackintosh/comments/g7rqt1/if_youre_stuck_at_endrandomseed_or/ ,but still get this error.


`xiaoxinpro13 i7` remove Emulate also get same error.
try add both [Emulate](https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI-OC-PRO13/OC/config.plist#L864-L874) and add [DVMT for 10.15.5 patch](https://github.com/athlonreg/Common-patches-for-hackintosh)

**Comment by M69W** [comment]
> My computer is xiaoxin pro 13 2019 i7. When I use clover, it works. But when I use the opencore 0.59 to install macOS 10.15.5, the installation stuck at [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]. I tried to use opencore 0.58, it works. Maybe you can try the opencore 0.58 and 0.60.



> > I have a laptop Ideapad s540-13iml with i5-10210u and mx250 (as far as I know it's identical to xiaoxin pro 13 2019). I tried to install macOS 10.15.5 through opencore and clover, but installation stucks at [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]. I also tried changing the values of RebuildAppleMemoryMap and SetupVirtualMap as written in this post https://www.reddit.com/r/hackintosh/comments/g7rqt1/if_youre_stuck_at_endrandomseed_or/ ,but still get this error.
> 
> `xiaoxinpro13 i7` remove Emulate also got same error.
> try add both [Emulate](https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI-OC-PRO13/OC/config.plist#L864-L874) and add [DVMT for 10.15.5 patch](https://github.com/athlonreg/Common-patches-for-hackintosh)

same questions？pay focus on:  [v2.1.3's warning](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1.3)

**Comment by dosyadd** [comment]
Thanks for your replies. I tried multiple versions of clover after creating this post but the process of installation was extremely slow. However, OC 0.5.8 with ig-platform-id = 0x12345678 allowed to bo

**Comment by dosyadd** [comment]
Installation of macOS 10.15.5, Opencore 0.5.9 (using ig-platform-id = 0x12345678, otherwise get panic) to ssd Samsung 970 Evo Plus was successful. Then I executed commands `sudo spctl --master-disable, sudo kextcache -i /` in terminal. After that, I added AppleIntelCFLGraphicsFramebuffer patch, changed ig-platform-id = 0x19160000 and added framebuffer-stolenmem = 00003001, framebuffer-fbmem = 00090000. Now the boot process comes to `IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0`, then the system boots with no gpu acceleration. About this MAC shows Screen 15mb in graphics. Also tried framebuffer-stolenmem=00000004, no luck. My config.plist `https://drive.google.com/file/d/1sGG-aOqA1y8FtWkXyjdNjFzK3WYYszKw/view?usp=sharing`.

**Comment by dosyadd** [comment]
Okay, ig-platform-id = 0x9B3E0000 works fine. Now, the system can't boot without USB drive. I followed this [guide](https://dortania.github.io/OpenCore-Desktop-Guide/post-install/oc2hdd.html) but there is no option in boot menu.

**Comment by cytown** [comment]
> 有没有其他老哥遇到了这个问题啊，[EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 and [EB|#LOG:EXITBS:START]，我clover全都正常（虽然每次开机必花屏，但后面正常使用就没问题），据说oc不会怎么花屏也可以用随航，但我oc059不能用，我好想用oc啊，机型配置（2019 xiaoxin pro13 i7 sn750 dw1820a）

问下你的OC是否正常工作了，我也是clover花屏，很烦啊，用OC启动直接就是一堆EBI错误。。。。

**Comment by cytown** [comment]
Exactly the same issue, with ig-platform-id = 0x9B3E0000....

**Comment by dosyadd** [comment]
> Exactly the same issue, with ig-platform-id = 0x9B3E0000....
Try Opencore 0.5.9 with ig-platform-id = 0x12345678

**Comment by cytown** [comment]
@dosyadd you meant don't use https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/download/v2.1.6/EFI-OC06-PRO13.zip ???  Or just change ig-platform-id? 

p.s. how about the device-id, change also?

**Comment by cytown** [comment]
IMO, that zip file should contain the newest opencore, at least 0.5.8.

**Comment by dosyadd** [comment]
Okay, if you want to use OpenCore 0.5.9 or above, you need to remove # in Emulate section and add dvmt patch cuz it removed in 0.5.9.

**Comment by albi74** [comment]
@dosyadd 
Hi, 
xactly the same issue, with ig-platform-id = 0x9B3E0000 and 0x12345678 on thinkbook 13-iml with comet lake i5-10210U.
Stuck on [EB|#LOG:EXITBS:START]

**Comment by dosyadd** [comment]
@albi74 Hi, there are differences in our Opencore 0.5.8 and 0.5.9 EFI (Emulate section disabled in config.plist) which caused this problem in my case. You can try our Opencore 0.5.8 EFI or clover.

**Comment by albi74** [comment]
Hi,,
I tried both by enabling emulte in opencore 0.5.9 and 0.6.0 and with clover but I'm stuck on exitbs

**Comment by dosyadd** [comment]
@albi74 Oh, I forgot. Have you added a dvmt patch in Opencore 0.5.9 and 0.6.0? Or have you tried Opencore 0.5.8? Because in this EFI dvmt patch already added in config.plist.
If yes: 
What is the version of your Bios? Is advanced settings available? I found that bios updater for my laptop is identical to the Xiaoxin pro 13 bios updater (our latest version of bios is CLCN32WW). I think this is the reason why multiple ACPI patches work on my laptop as well. If your version of bios is not like CLCN**WW, probably you need to find your Xiaoxin counterpart (if it's exist) and try to find a hackintosh guide for it.

**Comment by cytown** [comment]
> Okay, if you want to use OpenCore 0.5.9 or above, you need to remove # in Emulate section and add dvmt patch cuz it removed in 0.5.9.

Thank you, it works when I remove the # in emulate section.  I did patch dvmt already.

**Comment by albi74** [comment]
Hi,
I’ve try with opencore 0.5.9 and 0.6.0 with dvmt patch but stuck on exitbs 😫

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Cytown <notifications@github.com>
Inviato: Friday, July 24, 2020 4:05:14 AM
A: daliansky/XiaoXinPro-13-hackintosh <XiaoXinPro-13-hackintosh@noreply.github.com>
Cc: albi74 <albi74@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [daliansky/XiaoXinPro-13-hackintosh] [EB|`B:WFDW] Err(0xE), 0 @ LocHB 71B4903C-14EC-42C4-BDC6-CE1449930E49 (#32)


Okay, if you want to use OpenCore 0.5.9 or above, you need to remove # in Emulate section and add dvmt patch cuz it removed in 0.5.9.

Thank you, it works when I remove the # in emulate section. I did patch dvmt already.

**Comment by M69W** [comment]
> Hi,,
> I tried both by enabling emulte in opencore 0.5.9 and 0.6.0 and with clover but I'm stuck on exitbs

Add Emulate and remove '#' let them works

**Comment by albi74** [comment]
I don't think I made any mistakes but in doubt take a look. I also tried with 0x12345678 but it doesn't work



		<key>Emulate</key>
		<dict>
			<key>Cpuid1Data</key>
			<data>
			7AYIAAAAAAAAAAAAAAAAAA==
			</data>
			<key>Cpuid1Mask</key>
			<data>
			/////wAAAAAAAAAAAAAAAA==
			</data>
		</dict>
		<key>Patch</key>
		<array>
			<dict>	
				<key>Base</key>	
				<string></string>	
				<key>Comment</key>	
				<string>DVMTpatch-10.15-10.15.1-10.15.2-10.15.3</string>	
				<key>Count</key>	
				<integer>0</integer>	
				<key>Enabled</key>	
				<true/>	
				<key>Find</key>	
				<data>	
				D4KnAwAA	
				</data>	
				<key>Identifier</key>	
				<string>com.apple.driver.AppleIntelCFLGraphicsFramebuffer</string>	
				<key>Limit</key>	
				<integer>0</integer>	
				<key>Mask</key>	
				<data>	
				</data>	
				<key>MaxKernel</key>	
				<string>19.3.0</string>	
				<key>MinKernel</key>	
				<string></string>	
				<key>Replace</key>	
				<data>	
				D4IAAAAA	
				</data>	
				<key>ReplaceMask</key>	
				<data>	
				</data>	
				<key>Skip</key>	
				<integer>0</integer>	
			</dict>	
			<dict>	
				<key>Base</key>	
				<string></string>	
				<key>Comment</key>	
				<string>DVMTpatch-10.15.4,10.15.5,10.15.6</string>	
				<key>Count</key>	
				<integer>0</integer>	
				<key>Enabled</key>	
				<true/>	
				<key>Find</key>	
				<data>	
				D4KPAwAA	
				</data>	
				<key>Identifier</key>	
				<string>com.apple.driver.AppleIntelCFLGraphicsFramebuffer</string>	
				<key>Limit</key>	
				<integer>0</integer>	
				<key>Mask</key>	
				<data>	
				</data>	
				<key>MaxKernel</key>	
				<string>19.6.0</string>	
				<key>MinKernel</key>	
				<string>19.4.0</string>	
				<key>Replace</key>	
				<data>	
				D4IAAAAA	
				</data>	
				<key>ReplaceMask</key>	
				<data>	
				</data>	
				<key>Skip</key>	
				<integer>0</integer>	
			</dict>
		</array>

**Comment by dosyadd** [comment]
> > Okay, if you want to use OpenCore 0.5.9 or above, you need to remove # in Emulate section and add dvmt patch cuz it removed in 0.5.9.
> 
> Thank you, it works when I remove the # in emulate section. I did patch dvmt already.

You're welcome.

**Comment by dosyadd** [comment]
@albi74 So, what's your version of bios?

**Comment by cytown** [comment]
> I don't think I made any mistakes but in doubt take a look. I also tried with 0x12345678 but it doesn't work
> 
> ```
> 	<key>Emulate</key>
> 	<dict>
> 		<key>Cpuid1Data</key>
> 		<data>
> 		7AYIAAAAAAAAAAAAAAAAAA==
> 		</data>
> 		<key>Cpuid1Mask</key>
> 		<data>
> 		/////wAAAAAAAAAAAAAAAA==
> 		</data>
> 	</dict>
> 	<key>Patch</key>
> 	<array>
> 		<dict>	
> 			<key>Base</key>	
> 			<string></string>	
> 			<key>Comment</key>	
> 			<string>DVMTpatch-10.15-10.15.1-10.15.2-10.15.3</string>	
> 			<key>Count</key>	
> 			<integer>0</integer>	
> 			<key>Enabled</key>	
> 			<true/>	
> 			<key>Find</key>	
> 			<data>	
> 			D4KnAwAA	
> 			</data>	
> 			<key>Identifier</key>	
> 			<string>com.apple.driver.AppleIntelCFLGraphicsFramebuffer</string>	
> 			<key>Limit</key>	
> 			<integer>0</integer>	
> 			<key>Mask</key>	
> 			<data>	
> 			</data>	
> 			<key>MaxKernel</key>	
> 			<string>19.3.0</string>	
> 			<key>MinKernel</key>	
> 			<string></string>	
> 			<key>Replace</key>	
> 			<data>	
> 			D4IAAAAA	
> 			</data>	
> 			<key>ReplaceMask</key>	
> 			<data>	
> 			</data>	
> 			<key>Skip</key>	
> 			<integer>0</integer>	
> 		</dict>	
> 		<dict>	
> 			<key>Base</key>	
> 			<string></string>	
> 			<key>Comment</key>	
> 			<string>DVMTpatch-10.15.4,10.15.5,10.15.6</string>	
> 			<key>Count</key>	
> 			<integer>0</integer>	
> 			<key>Enabled</key>	
> 			<true/>	
> 			<key>Find</key>	
> 			<data>	
> 			D4KPAwAA	
> 			</data>	
> 			<key>Identifier</key>	
> 			<string>com.apple.driver.AppleIntelCFLGraphicsFramebuffer</string>	
> 			<key>Limit</key>	
> 			<integer>0</integer>	
> 			<key>Mask</key>	
> 			<data>	
> 			</data>	
> 			<key>MaxKernel</key>	
> 			<string>19.6.0</string>	
> 			<key>MinKernel</key>	
> 			<string>19.4.0</string>	
> 			<key>Replace</key>	
> 			<data>	
> 			D4IAAAAA	
> 			</data>	
> 			<key>ReplaceMask</key>	
> 			<data>	
> 			</data>	
> 			<key>Skip</key>	
> 			<integer>0</integer>	
> 		</dict>
> 	</array>
> ```

IMO, you should change the ig-platform-id and device-id, it works on my side with 0400A53E and A53E0400

**Comment by dosyadd** [comment]
@cytown Are you experiencing screen flickering with this ig-platform-id? And what is your hidpi screen resolution?

**Comment by albi74** [comment]
> @albi74 So, what's your version of bios?

My Lenovo is a thinkbook 13s-iml same as the XiaoXin Pro-13 motherboard which in Europe is sold under the name of s540 or thinkbook. But my bios is this cqcn21ww and it is not possible to make changes for both the cfg and the ram of the iGPU

**Comment by albi74** [comment]
> > I don't think I made any mistakes but in doubt take a look. I also tried with 0x12345678 but it doesn't work
> > ```
> > 	<key>Emulate</key>
> > 	<dict>
> > 		<key>Cpuid1Data</key>
> > 		<data>
> > 		7AYIAAAAAAAAAAAAAAAAAA==
> > 		</data>
> > 		<key>Cpuid1Mask</key>
> > 		<data>
> > 		/////wAAAAAAAAAAAAAAAA==
> > 		</data>
> > 	</dict>
> > 	<key>Patch</key>
> > 	<array>
> > 		<dict>	
> > 			<key>Base</key>	
> > 			<string></string>	
> > 			<key>Comment</key>	
> > 			<string>DVMTpatch-10.15-10.15.1-10.15.2-10.15.3</string>	
> > 			<key>Count</key>	
> > 			<integer>0</integer>	
> > 			<key>Enabled</key>	
> > 			<true/>	
> > 			<key>Find</key>	
> > 			<data>	
> > 			D4KnAwAA	
> > 			</data>	
> > 			<key>Identifier</key>	
> > 			<string>com.apple.driver.AppleIntelCFLGraphicsFramebuffer</string>	
> > 			<key>Limit</key>	
> > 			<integer>0</integer>	
> > 			<key>Mask</key>	
> > 			<data>	
> > 			</data>	
> > 			<key>MaxKernel</key>	
> > 			<string>19.3.0</string>	
> > 			<key>MinKernel</key>	
> > 			<string></string>	
> > 			<key>Replace</key>	
> > 			<data>	
> > 			D4IAAAAA	
> > 			</data>	
> > 			<key>ReplaceMask</key>	
> > 			<data>	
> > 			</data>	
> > 			<key>Skip</key>	
> > 			<integer>0</integer>	
> > 		</dict>	
> > 		<dict>	
> > 			<key>Base</key>	
> > 			<string></string>	
> > 			<key>Comment</key>	
> > 			<string>DVMTpatch-10.15.4,10.15.5,10.15.6</string>	
> > 			<key>Count</key>	
> > 			<integer>0</integer>	
> > 			<key>Enabled</key>	
> > 			<true/>	
> > 			<key>Find</key>	
> > 			<data>	
> > 			D4KPAwAA	
> > 			</data>	
> > 			<key>Identifier</key>	
> > 			<string>com.apple.driver.AppleIntelCFLGraphicsFramebuffer</string>	
> > 			<key>Limit</key>	
> > 			<integer>0</integer>	
> > 			<key>Mask</key>	
> > 			<data>	
> > 			</data>	
> > 			<key>MaxKernel</key>	
> > 			<string>19.6.0</string>	
> > 			<key>MinKernel</key>	
> > 			<string>19.4.0</string>	
> > 			<key>Replace</key>	
> > 			<data>	
> > 			D4IAAAAA	
> > 			</data>	
> > 			<key>ReplaceMask</key>	
> > 			<data>	
> > 			</data>	
> > 			<key>Skip</key>	
> > 			<integer>0</integer>	
> > 		</dict>
> > 	</array>
> > ```
> 
> IMO, you should change the ig-platform-id and device-id, it works on my side with 0400A53E and A53E0400

I'll give it a try

**Comment by cytown** [comment]
> @cytown Are you experiencing screen flickering with this ig-platform-id? And what is your hidpi screen resolution?

It flicker in clover when boot up or resume from sleep, so I changed to oc, now it works, only occasionally it flicker when boot up, but the strange is not before I login with my account...

My hidpi use 1680x1050, just same as my MBP2013.

**Comment by gamecss** [comment]
你搞好了么？我也一直这样
