### ISSUE TITLE
AX200.zip，里面的教程，开启以太网的方法失败。

### ISSUE THREAD

**Issue by iwsbiwy** [daliansky/XiaoXinPro-13-hackintosh#33]
注释或删除那两条，重启后还是不能添加以太网

**Comment by M69W** [comment]
[修复使用 `AX200` 网卡时无法显示`以太网`](https://github.com/daliansky/XiaoXinPro-13-hackintosh/commit/f386115d506c134394ea9d16b36e86e12d0c91ef)

**Comment by iwsbiwy** [comment]
多谢，我晚上回去试试。

**Comment by iwsbiwy** [comment]
> 已[修复使用 `AX200` 网卡时无法显示`以太网`](https://github.com/daliansky/XiaoXinPro-13-hackintosh/commit/f386115d506c134394ea9d16b36e86e12d0c91ef)
我用的macos10，OC引导。
1. 使用`EFI-OC-PRO13-20200710.zip`，复制到EFI。
2. 使用`Code`页的` EFI/EFI-OC06-PRO13for11/AX200文件夹内的复制到EFI，其中`config.plist`和`config的副本.plist`替换原来的。
3. 重启进OC卡如下界面 ![IMG_20200715_203739__01.jpg](https://i.loli.net/2020/07/15/KEYT2q93htMmzup.jpg)

我的方法对吗？还是说先用`EFI-OC-PRO13-20200710.`进系统，然后再复制`AX200`至EFI？

**Comment by M69W** [comment]
### OC是比较特殊的，不同日期的releases EFI 可能设置不同，就导致其他问题

简单说下
[这部分#L484-L497 ](https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI-OC06-PRO13for11/AX200/config.plist#L484-L497) 两个`#`表示屏蔽或者说禁用，为什么要这样，[具体原因不明](https://github.com/OpenIntelWireless/itlwm/issues/146)，只知道这样才能出现【以太网】
```
<key>#PciRoot(0x0)/Pci(0x1C,0x0)</key>
<dict>
	<key>pci-aspm-default</key>
	<data>
	AgAAAA==
	</data>
</dict>
<key>#PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)</key>
<dict>
	<key>pci-aspm-default</key>
	<data>
	AgEAAA==
	</data>
</dict>
```

### 禁止PCI是让小新pro13 出现【以太网】，
![network](https://user-images.githubusercontent.com/15809201/87572497-35831f80-c6fe-11ea-926e-d5cccf595b40.png)

### `OC引入AX200 网卡和蓝牙驱动`：[#L798-L845](https://github.com/daliansky/XiaoXinPro-13-hackintosh/blob/master/EFI/EFI-OC06-PRO13for11/AX200/config.plist#L798-L845)
```
<dict>
	<key>BundlePath</key>
	<string>itlwmx.kext</string>
	<key>Comment</key>
	<string>AX200 Wi-Fi</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/itlwmx</string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>IntelBluetoothFirmware.kext</string>
	<key>Comment</key>
	<string>AX200 Bluetooth Firmware</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/IntelBluetoothFirmware</string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>IntelBluetoothInjector.kext</string>
	<key>Comment</key>
	<string>AX200 Bluetooth Switch</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string></string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
```

**Comment by M69W** [comment]
网卡是多少？
如果是AX201，目前是用不了

**Comment by iwsbiwy** [comment]
> 网卡是多少？
> 如果是AX201，目前是用不了

AX200

**Comment by M69W** [comment]
再次确认，[v2.1.5beta](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1.5beta)的没问题
![network](https://user-images.githubusercontent.com/15809201/87669226-3076ac80-c7a0-11ea-8eba-b53f366e471f.png)

**Comment by M69W** [comment]
> > 已[修复使用 `AX200` 网卡时无法显示`以太网`](https://github.com/daliansky/XiaoXinPro-13-hackintosh/commit/f386115d506c134394ea9d16b36e86e12d0c91ef)
> > 我用的macos10，OC引导。
> 
> 1. 使用`EFI-OC-PRO13-20200710.zip`，复制到EFI。
> 2. 使用`Code`页的` EFI/EFI-OC06-PRO13for11/AX200`文件夹内的复制到`EFI`，其中`config.plist`和`config的副本.plist`替换原来的。
> 3. 重启进OC卡如下界面 ![IMG_20200715_203739__01.jpg](https://camo.githubusercontent.com/0cc4087881eac7cb4c07167715cf4d502f364795/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f31352f4b4559543271393368744d6d7a75702e6a7067)
> 
> 我的方法对吗？还是说先用`EFI-OC-PRO13-20200710`进系统，然后再复制`AX200`至`EFI`？

卡这里是其他问题

**Comment by iwsbiwy** [comment]
> 再次确认，[v2.1.5beta](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1.5beta)的没问题
> 请自行检查
> 
> ![network](https://user-images.githubusercontent.com/15809201/87669226-3076ac80-c7a0-11ea-8eba-b53f366e471f.png)
> <img alt="network1" width="633" src="https://user-images.githubusercontent.com/15809201/87669392-75024800-c7a0-11ea-9920-1dc5534eb120.png">
> <img alt="network2" width="1516" src="https://user-images.githubusercontent.com/15809201/87670083-bb0bdb80-c7a1-11ea-9aa5-11fbcc80c863.png">
> <img alt="network3" width="1641" src="https://user-images.githubusercontent.com/15809201/87670103-c52dda00-c7a1-11ea-9f3c-bcffbcb2d1c4.png">

好的，我再试试看看。

**Comment by M69W** [comment]
[OC 使用AX200的简单教程](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/AX200)
这个issues 先关闭，如果还不能解决，请再开issues。
