### ISSUE TITLE
首次安装最新版本到重启进入新系统出现In Memory Panic错误

### ISSUE THREAD

**Issue by cytown** [daliansky/XiaoXinPro-13-hackintosh#34]
硬件：小新Pro13 i7 10代U 2019款。更换了硬盘、网卡DW1820A.
安装文件是macOS Catalina 10.15.6(19G73) Installer for Clover 5119 and WEPE.dmg
修改了U盘的EFI为 Pro13_I7_Installer_DW1820A_and_UMIS_12-4-2019_by_黑果小兵.zip目录下的EFI

几次重启都正常，最后一次安装，识别到了网卡，进入系统后，输入了几个sudo命令，完全正常。然后使用clover configurator挂载了ssd上的EFI和u盘上的EFI，按照blog上提示，因为ssd上EFI是空的，把u盘EFI目录整个复制过去，然后安装u盘上的clover bootloader，完成。

重启以后就选择config(之前一直是config_install)，结果就报错了，显示In Memory Panic Stackshot Succeeded

然后重新启动选择config_install，把u盘上EFI目录下的文件复制到ssd的EFI下，而不是EFI目录，结果依然如此。

查了一下Google，好像说是IGPU的问题，是否是内置intel显卡的问题？还是我应该在bios里面想办法禁用MX250？

**Comment by cytown** [comment]
补充一下，启动时候好像是有提示说igpu错误还是无法识别什么的。

**Comment by M69W** [comment]
你用的EFI只限于安装，
安装后需要替补别的EFI
推荐最新的releases

即使用不到11  Big Sur
最新efi也内置15.*的DVMT补丁

**Comment by cytown** [comment]
@M69W 你是说我需要清空EFI分区，然后把CLOVER_7-17-2020@daliansky_with_BS.zip里面的文件copy进去？

那个i7-i5.DVMT-Patch-15.6+CPUID+DW1820A+id11.zip怎么用？

另外，我要改成OC，是需要把EFI-OC06-PRO13.zip里面的文件放进去么？

现在的blog里面还是老的说法，就是我之前操作的方式。

强烈建议release里面增加这些文件怎么用。

**Comment by cytown** [comment]
刚刚用config_installer启动后mount了ssd的efi，清空其内容，然后把CLOVER_7-17-2020@daliansky_with_BS.zip复制进去了，只有一个clover文件，但是重启以后选择config依然是一样的错误。。。

**Comment by cytown** [comment]
又试了一次，这次是关机，然后启动的，依然错误。

p.s. 这次把EFI-OC06-PRO13.zip里面的文件也放到EFI分区里面了，但是好像没有什么作用。

**Comment by cytown** [comment]
晕死，我之前没操作bootice，所以失败了。

但我加上bootice以后，好像启动的时候option里面什么都没有，但我确定我放入的文件里面有config.plist和config-sample.plist。难道还是需要copy u盘里面的efi进去？而不是CLOVER_7-17-2020@daliansky_with_BS.zip里面的内容？

**Comment by cytown** [comment]
再次重新操作了一下，把u盘的分区的efi目录复制到ssd的efi分区，然后重启进入pe，删除原来的启动项，增加新指向的C:\EFI\EFI\CLOVER\CLOVERX64.efi，保存，重启拔u盘，直接认不出启动盘，插入u盘然后立刻拿掉，弹出clover界面，选择config启动，还是memory panic。。。。。

**Comment by cytown** [comment]
@M69W 麻烦再给看看，或者哪里有正确的教程？尤其是最后创建ssd上EFI的。

在线急等。

**Comment by cytown** [comment]
我搞定了，具体需要这样：
1. 把USB的EFI目录下的文件复制到SSD上
2. 删除CLOVER目录
3. 把CLOVER_7-17-2020@daliansky_with_BS.zip目录解压，然后复制里面的CLOVER目录。

重启就可以了。

但是又有新的问题出现了，开机花屏+随机花屏，目前唯一解决办法是关闭屏幕，然后重新打开，按电源键恢复。

听说OC可以解决这个问题？那么我需要怎样做才行？是把CLOVER目录删掉，然后复制OC到EFI下面么？需要执行BOOTICE么？

**Comment by cytown** [comment]
强烈建议修正下blog的安装说明。目前全网都没有一个正确的安装方法。

**Comment by M69W** [comment]
CC @daliansky

**Comment by cytown** [comment]
再次更新一下，改成OC启动失败：
操作方法如下：
1. EFI-OC06-PRO13.zip解压，然后把原来的EFI里面的BOOT改名成BOOT2，然后复制解压出来的文件进去。
2. 重启然后进入PE内的BOOTICE，增加OC目录，指向C:\EFI\EFI\OpenClover.efi
3. 重启执行reset nvram
4. 再次执行2
5. 重启选择1
6. 显示一堆莫名错误然后死机

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki

**Comment by cytown** [comment]
@M69W 请问是要我看这个wiki么？我是执行过hacktool，确定我的cpu是0660的i7，所以不存在兼容性问题。

我网卡硬盘都换掉了。
还是说我需要打DVMT补丁才能正常使用clover和OC？？？？

**Comment by cytown** [comment]
> @M69W 请问是要我看这个wiki么？我是执行过hacktool，确定我的cpu是0660的i7，所以不存在兼容性问题。
> 
> 我网卡硬盘都换掉了。
> 还是说我需要打DVMT补丁才能正常使用clover和OC？？？？

已经第一次能启动OC了，需要手工增加DVMT的patch和去掉emulate里面的#，尤其后一步，不注意根本不知道。不过系统被认为是两个不同的机器，但我应该设置一样的type/serial/bord serial/smuuid啊，请问需要修改哪里让oc和clover不被认为是两个不同的设备。

p.s. Opencore configurator好像在clover下面启动会 ANR，是设计如此么？OC下面就没有这个问题。。。

**Comment by cytown** [comment]
还有一个问题，oc的菜单是1. macos， 2. win10，但我没有win10啊，如何去掉呢？

**Comment by cytown** [comment]
> 还有一个问题，oc的菜单是1. macos， 2. win10，但我没有win10啊，如何去掉呢？

这个搞定了。

现在OC偶尔屏幕闪一下，有人知道是什么原因么？

其它好像都还比较正常。就是有次pmset sleepnow以后起来进入系统转圈不停，只能强制关机重启。

**Comment by cytown** [comment]
release文件里面的是630的显卡设置，所以错误了要改成655的。。。

为何release里面不放正确的小新pro的oc配置呢？？？

**Comment by cytown** [comment]
已经都搞定了，目前来看没什么太大问题，回头可以把我的配置分享出来，以免更多人走弯路。

**Comment by cytown** [comment]
> 已经都搞定了，目前来看没什么太大问题，回头可以把我的配置分享出来，以免更多人走弯路。

好像还有些配置问题，重启进入系统，大概率会花屏一阵，好像一会儿自己又好了。。。

好在休眠回来是不会花屏。

**Comment by M69W** [comment]
BIOS 设置不同，config也会不同。
[v2.1.7](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1.7)

**Comment by cytown** [comment]
> BIOS 设置不同，config也会不同。
> [v2.1.7](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1.7)

所谓bios设置不同，是说是否使用测试版bios么？那么是否应该多几个不同的config文件，针对测试版bios和普通bios的不一样。

**Comment by M69W** [comment]
关键是cfglock和dvmt

测试版提供设置入口
出厂机器都是正式版不提供入口修改，

config文件中可以设置cfglock和dvmt
但dvmt最好还是在bios中设置为好，
如果没有人找这个dvmt补丁，可以升级或大版本更新就会因dvmt而进不了系统，例如开机重启

**Comment by cytown** [comment]
> 关键是cfglock和dvmt
> 
> 测试版提供设置入口
> 出厂机器都是正式版不提供入口修改，
> 
> config文件中可以设置cfglock和dvmt
> 但dvmt最好还是在bios中设置为好，
> 如果没有人找这个dvmt补丁，如果升级或大版本更新就会因dvmt而进不了系统，例如开机重启

说实话，这样的解释不是很清晰。那么哪个文件是针对测试版bios有用，而正式版bios没用？哪个文件对正式版bios有用，对测试版bios没用？？？

DVMT的patch到底是给正式版用的还是给测试版用的？？？

cfglock我的理解应该是bios里面设置secure boot关闭就没事了，对吧？这个跟正式版测试版bios都没太大关系，对吧？

**Comment by M69W** [comment]
首先说明一点，我只是EFI的维护团队中的一员，

日常制作EFI的大佬，是小兵、宪武这两位大佬日常更新；
其实不止这两位大佬，可以说小新pro13这个机型经过很多大佬的折腾，才到今天这个黑苹果程度
比如说i7在开始一段时间内不能黑，触摸板驱动不了，早期研究并制作脚本或工具篡改BIOS来达到关闭CFG 和 设置 DVMT 目的、替换开机logo 等等。

几乎每次更新 EFI，除了照搬 制作EFI大佬的更新信息，
还要一部分信息是我对比上个版本得出差异，整合一起提交更新。
大部分工作过程我没有参与，同时这方面知识受限，并不能非常详细说明。
要想学习相关知识或深入研究，估计要自己亲自探索了。


开始回到你的问题，
DVMT 补丁 不是针对正式版BIOS、测试版本BIOS，
这两个版本都有对应设置的方式去达到设置DVMT。
更新中提到是让用EFI的人注意一下自己的机子是否有设置相关设置．


至于为什么 要设置 CFGLOCK 和 DVMT 补丁 ,
这个问题网上有很多帖子讨论过
这里不展开.

**Comment by cytown** [comment]
首先，我必须非常感谢所有参与这个项目的人的付出，包括你，包括小兵和宪武等等更多我不知道名字的人。

其次，我觉得文档力所能及的清楚就行，没人要求从原理等各方面说明，甚至只要把使用方法和适用环境写清楚就行，毕竟这才是使用者或者说下载者最关心的问题，至于说原理，那当然是各人兴趣不用多说。

回到我的问题，我看到的DVMT补丁就是wiki里面的内如，可你说的是针对正式版和测试版bios有对应的设置方式，我就晕了，那么wiki里面并没有说明这个补丁是针对测试版还是正式版，或者说会有两个不同的补丁。。。

那么我们长话短说，我的是正式版的bios，那么需要打这个wiki里面的DVMT补丁么？另外我已经把secure boot关闭，而且目前没发现什么问题，那么我需要设置CFGLOCK么？如果需要，设置项是否就是AppleCpuPmCfgLock和AppleXcpmCfgLock？？？

**Comment by M69W** [comment]
可以在config.plist中禁用cfglock或禁用dvmt补丁
尝试能否正常开机进系统就知道了

**Comment by cytown** [comment]
> 可以在config.plist中禁用cfglock或禁用dvmt补丁
> 尝试能否正常开机进系统就知道了

就是说，每台机器不一样？所以要自己测试。。。

但我禁用或者不禁用都正常开机进系统的话，算是怎么个答案？:P
