### ISSUE TITLE
wiki里面的xml是错的

### ISSUE THREAD

**Issue by cytown** [daliansky/XiaoXinPro-13-hackintosh#36]
https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki

<key></key>写成了<key><key> 或者<array/>写成了<array>

所有的斜线都被去掉了。

**Comment by M69W** [comment]
谢谢反馈！

为了折叠使用了details标签，里面的markdown格式失效了
然后补丁部分使用了对所有的<**></**>做了转义

下次改为独立一个链接页面显示

**Comment by M69W** [comment]
> https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki
> 
> 写成了 或者写成了
> 
> 所有的斜线都被去掉了。

已更新
