### ISSUE TITLE
键盘映射里面的左右ctrl反了

### ISSUE THREAD

**Issue by cytown** [daliansky/XiaoXinPro-13-hackintosh#37]
因为mbp上只有一个ctrl，所以没有发现吧。
我是在keyboard里面把option和control对调了，然后：
用item2发现里面的设置左右option键的功能，发现键盘映射里面的ctrl的左右定义是反的，在item2里面设置左面的option实际设置的是右面的。

**Comment by M69W** [comment]
因为这个软件本来就是白苹果专属
白苹果键盘和黑苹果笔记本键盘不一样
可以认为是iterm2的问题吗？

**Comment by cytown** [comment]
不是的，如果我没有对调，其实也不会发现这个问题，因为你会发现左面的win对应的就是左面的option.

**Comment by M69W** [comment]
已更新 [键盘](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/%E9%94%AE%E7%9B%98) 说明，参考解决。
