### ISSUE TITLE
有没有可能实现深度睡眠

### ISSUE THREAD

**Issue by cytown** [daliansky/XiaoXinPro-13-hackintosh#39]
就是把内存里面的做个快照放到硬盘上，然后关机，这样恢复的时候从硬盘恢复到内存中。

早期windows/linux是实现这个功能的，现在是ssd时代了，应该更方便实现了。

我当前的系统i7 2019款pro13，现在的休眠方式会每小时掉1%的电，实在有点高。

**Comment by cytown** [comment]
很遗憾测试失败了。。。。

目前的结果是：
sudo pmset -a hibernatemode 25
然后
pmset sleepnow

系统确实实现了关机，把内存放到/var/vm/sleepimage中。

但是oc好像并不支持这个，再次开机，系统并不会从休眠中恢复，而是貌似崩溃了，会自动重启，然后重新引导后进入系统，等于关机。

**Comment by cytown** [comment]
刚刚发现oc里面的HibernateMode没有改，导致问题，不过修改成Auto以后，依然是不行，只是现象变了：休眠后开机选择进入系统后系统好像死机，键盘灯都不亮，按记下power键以后系统自动重启进入正常模式。

**Comment by cytown** [comment]
是否我应该安装个HibernationFixup？我看到一个说明说WhateverGreen里面会包含这个，但找了半天，好像没有发现包含的支持。

**Comment by cytown** [comment]
问下是否只支持hibernatemode 0？？？？

**Comment by cytown** [comment]
因为是测试hibernatemode 3，结果睡死了，所以才有上面疑问，结果并非必现。大部分情况下，3还是能正常唤醒的。

**Comment by ifaswind** [comment]
期待一下

**Comment by stevezhengshiqi** [comment]
> 是否我应该安装个HibernationFixup？我看到一个说明说WhateverGreen里面会包含这个，但找了半天，好像没有发现包含的支持。

据我理解，`hibernatemode 25` 就是大家所说的S4睡眠，需要加入 `HibernationFixup` 来开启，可从 https://github.com/acidanthera/HibernationFixup/releases 里下载

**Comment by cytown** [comment]
> > 是否我应该安装个HibernationFixup？我看到一个说明说WhateverGreen里面会包含这个，但找了半天，好像没有发现包含的支持。
> 
> 据我理解，`hibernatemode 25` 就是大家所说的S4睡眠，需要加入 `HibernationFixup` 来开启，可从 https://github.com/acidanthera/HibernationFixup/releases 里下载

测试过了，好像并不行，你可以也试试。

**Comment by stevezhengshiqi** [comment]
我的是小米笔记本Pro，是可以S4睡眠的。

**Comment by cytown** [comment]
> 我的是小米笔记本Pro，是可以S4睡眠的。

请问就是加上这个驱动，然后设置hibernatemode 25就成功了么？

我的现象是启动后确实看似准备恢复，但是黑屏一阵以后就重启了。这里好像还没有日志输出。。。

**Comment by M69W** [comment]
从之前宪武等人之前的研究看到，
大概意思是小新pro13没有传统睡眠模式(例如S3)
BIOS代码里面即使出现S3，但实现方法等为空或不工作
只能仿真睡眠，这里涉及AOAC。


说明：以上仅以BIOS版本为`CLEC32WW`或之前版本为研究对象说明，不代表未来也如此。
但基于AOAC，个人认为，不可能后面会添加传统睡眠模式

当然，折腾出奇迹。

**Comment by cytown** [comment]
传统睡眠方式我的理解应该是S3，但S4或者说mode 25好像不完全一样，因为这种是更加原始一点，在还没有其它hibernate方式的时候就已经有了，原理就是所有运行时状态存入硬盘中，然后从硬盘恢复原始状态。所以，我觉得这种实现其实应该跟硬件关系并不大。

不过hibernationfix好像是分RTC和NVram两种，而25是属于哪种我还真是拿不准。。。
@stevezhengshiqi 请问你的小米里面S4是用的RTC还是nvram???

**Comment by cytown** [comment]
新的宪武的版本，同时我修改了bios，还是没有成功设置25模式，每次都是黑屏，然后不得不强制关机。但我打开了所有的日志功能，但没有任何记录下来。包括hibernationfix，最新的1.3.3也进行了测试，完全没有任何区别。

**Comment by YH2135** [comment]
这个可以参考一下，https://zhuanlan.zhihu.com/p/350758984  希望能有所帮助

**Comment by cytown** [comment]
> 这个可以参考一下，https://zhuanlan.zhihu.com/p/350758984 希望能有所帮助

那个是针对amd的cpu的，能黑苹果的都是intel平台的。

**Comment by chenjiangui** [comment]
> > 是否我应该安装个HibernationFixup？我看到一个说明说WhateverGreen里面会包含这个，但找了半天，好像没有发现包含的支持。
> 
> 据我理解，`hibernatemode 25` 就是大家所说的S4睡眠，需要加入 `HibernationFixup` 来开启，可从 https://github.com/acidanthera/HibernationFixup/releases 里下载

我认为这是纯软件的功能, 不应该是S4睡眠.  windows下是支持休眠的, 不管睡几天1的电都不会掉, 其实就等于关机了   但是osx下休眠直接报错, 设置成25后报错如下

![image](https://user-images.githubusercontent.com/18565140/115483465-67c03f80-a283-11eb-8a17-ffdd7dd14473.png)

是哪里要设置吗?  我对唤醒速度没要求,  只想长时间扔包里不掉电,  能开盖直接继续工作

**Comment by cytown** [comment]
> > > 是否我应该安装个HibernationFixup？我看到一个说明说WhateverGreen里面会包含这个，但找了半天，好像没有发现包含的支持。
> > 
> > 
> > 据我理解，`hibernatemode 25` 就是大家所说的S4睡眠，需要加入 `HibernationFixup` 来开启，可从 https://github.com/acidanthera/HibernationFixup/releases 里下载
> 
> 我认为这是纯软件的功能, 不应该是S4睡眠. windows下是支持休眠的, 不管睡几天1的电都不会掉, 其实就等于关机了 但是osx下休眠直接报错, 设置成25后报错如下
> 
> ![image](https://user-images.githubusercontent.com/18565140/115483465-67c03f80-a283-11eb-8a17-ffdd7dd14473.png)
> 
> 是哪里要设置吗? 我对唤醒速度没要求, 只想长时间扔包里不掉电, 能开盖直接继续工作

暂时无解。。。

**Comment by surill** [comment]
最近也在纠结这个问题，期待大佬显灵

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)，设置25睡眠
有问题再 reopened
