### ISSUE TITLE
Not working on similar build MSI prestige 15

### ISSUE THREAD

**Issue by Yusepp** [daliansky/XiaoXinPro-13-hackintosh#4]
Faking the cpuid makes memory to allocate properly but the My screen got stuck with a row of ++++++++++++++++++++++++++++++++++++++++++++++++++++++++. Any ideas?

**Comment by M69W** [comment]
> Faking the cpuid makes memory to allocate properly but the My screen got stuck with a row of ++++++++++++++++++++++++++++++++++++++++++++++++++++++++. Any ideas?

Same CPU i7-10710U？
`FakeCPUID` like ：`0x0806EC` or `0x0806EB` to solve it for now.
Good Luck

**Comment by Yusepp** [comment]
> > Faking the cpuid makes memory to allocate properly but the My screen got stuck with a row of ++++++++++++++++++++++++++++++++++++++++++++++++++++++++. Any ideas?
> 
> Same CPU i7-10710U？
> `FakeCPUID` like ：`0x0806EC` or `0x0806EB` to solve it for now.
> Good Luck

Yeah same cpu but `FakeCPUID` like ：`0x0806EC` or `0x0806EB` does not work , it gives me the ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ message.
![d886e54c-d739-4b91-bad6-df0c84c1d357](https://user-images.githubusercontent.com/36641566/71760025-51884780-2eb7-11ea-8685-cd58bf1eb7e9.jpg)

**Comment by M69W** [comment]
> > > Faking the cpuid makes memory to allocate properly but the My screen got stuck with a row of ++++++++++++++++++++++++++++++++++++++++++++++++++++++++. Any ideas?
> > 
> > 
> > Same CPU i7-10710U？
> > `FakeCPUID` like ：`0x0806EC` or `0x0806EB` to solve it for now.
> > Good Luck
> 
> Yeah same cpu but `FakeCPUID` like ：`0x0806EC` or `0x0806EB` does not work , it gives me the ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ message.
> ![d886e54c-d739-4b91-bad6-df0c84c1d357](https://user-images.githubusercontent.com/36641566/71760025-51884780-2eb7-11ea-8685-cd58bf1eb7e9.jpg)

Can I have a look your EFI?

**Comment by Yusepp** [comment]
> Can I have a look your EFI?

Sure! Im using this based on my specs
[EFI.zip](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/files/4022217/EFI.zip)

**Comment by Yusepp** [comment]
> > > > Faking the cpuid makes memory to allocate properly but the My screen got stuck with a row of ++++++++++++++++++++++++++++++++++++++++++++++++++++++++. Any ideas?
> > > 
> > > 
> > > Same CPU i7-10710U？
> > > `FakeCPUID` like ：`0x0806EC` or `0x0806EB` to solve it for now.
> > > Good Luck
> > 
> > 
> > Yeah same cpu but `FakeCPUID` like ：`0x0806EC` or `0x0806EB` does not work , it gives me the ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ message.
> > ![d886e54c-d739-4b91-bad6-df0c84c1d357](https://user-images.githubusercontent.com/36641566/71760025-51884780-2eb7-11ea-8685-cd58bf1eb7e9.jpg)
> 
> Can I have a look your EFI?

so... any ideas?

**Comment by M69W** [comment]
May this EFI could help you...

[Tested hardware configuration](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh#%E7%94%B5%E8%84%91%E9%85%8D%E7%BD%AE)

[Pro13_I7_Installer_DW1820A_and_UMIS_12-4-2019_by_黑果小兵.zip](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/files/4035840/Pro13_I7_Installer_DW1820A_and_UMIS_12-4-2019_by_.zip)

**Comment by Yusepp** [comment]
> May this EFI could help you...
> 
> [Tested hardware configuration](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh#%E7%94%B5%E8%84%91%E9%85%8D%E7%BD%AE)
> 
> [Pro13_I7_Installer_DW1820A_and_UMIS_12-4-2019_by_daliansky黑果小兵.zip](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/files/4035870/Pro13_I7_Installer_DW1820A_and_UMIS_12-4-2019_by_daliansky.zip)

Tried everything but can't pass the +++++++ mark, I don't get why same CPUs can't be that hard to make working. A memory fix is needed am I right? It's a shame because the msi prestige 15 is such a good laptop

**Comment by neblogas** [comment]
Try the one for notebooks with coffeelake

https://www.olarila.com/topic/5676-clover-folder-for-all-chipsets/

**Comment by Yusepp** [comment]
I'll give it I try btw I passed the +++++ mark to the load kexts and kernel patches but it crush at reset. It gives me something related to  MACH Reboot error.

**Comment by johnnync13** [comment]
![795F7A58-0F42-434E-BE36-345FA5B7787B](https://user-images.githubusercontent.com/22727137/74932601-822e2d00-53e2-11ea-968f-0b75bd6ee251.png)

**Comment by M69W** [comment]
https://github.com/acidanthera/Lilu/pull/55
https://github.com/acidanthera/WhateverGreen/pull/42

**Comment by johnnync13** [comment]
@Yusepp works now?

**Comment by sarkrui** [comment]
> @Yusepp works now?

Please feel free to try them out. It ain't complied by me though, a member from the QQ group did. 
[WhateverGreen.kext.zip](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/files/4242416/WhateverGreen.kext.zip)
[Lilu.kext.zip](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/files/4242415/Lilu.kext.zip)

**Comment by Yusepp** [comment]
@johnnync13  @sarkrui  I tried the new daliansky's commit with new lilu and whatevergreen but just gave me a dark screen after clover selection menu. Also tried to use my efi with the new kexts but nothing changed: it loads kexts and kernel patches and after that gives MACH Reboot error

**Comment by sarkrui** [comment]
Whenever updating your kexts, it would be wise to clear kext caches by the following command,
```bash
sudo kextcache -i /
```
Some errors could have been avoided. Many members from the group have made successful reports. Good luck mate.

**Comment by johnnync13** [comment]
@sarkrui But he can’t install macOS because is his first boot, so can’t rebuilt kextcache

**Comment by sarkrui** [comment]
@Yusepp  @johnnync13  If you did not even manage to install macOS, as suggested by @M69W in the release page, you shall install with a  [Clover EFI](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/tree/master/EFI/EFI-CLOVER-PRO13) using `config_install.plist` (should be renamed to config.plist for the installation. `config.plist` is for post-installation FYI)

**Comment by Yusepp** [comment]
> @Yusepp @johnnync13 If you did not even manage to install macOS, as suggested by @M69W in the release page, you shall install with a [Clover EFI](https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh/tree/master/EFI/EFI-CLOVER-PRO13) using `config_install.plist` (should be renamed to config.plist for the installation. `config.plist` is for post-installation FYI)

I tried and got the typical error +++++++
![E28D04AC-AA80-469E-BEE9-E72ED115DD2F](https://user-images.githubusercontent.com/36641566/75123097-ade03a00-56a4-11ea-9146-740e1767edaa.jpeg)

This is using Installation plist and efi from the repository. Using my efi gives me as I said to load kext/kernel but Mach reboot. 

Anyways I think that fixing the repo is the way. Any suggestions for the ++++?

**Comment by sarkrui** [comment]
Jesus...
I just found your laptop ain't a XiaoXin Pro 13 mate...This repository is **explicitly** designed for **Lenovo XiaoXin Pro13/Pro13s** with i5/i7 CPU. ![image](https://user-images.githubusercontent.com/14228455/75123265-36130f00-56a6-11ea-9573-a50ffa4692fe.png)
![image](https://user-images.githubusercontent.com/14228455/75123275-44f9c180-56a6-11ea-8929-a55486183053.png)

**Comment by Yusepp** [comment]
> Jesus...
> I just found your laptop ain't a XiaoXin Pro 13 mate...This repository is **explicitly** designed for **Lenovo XiaoXin Pro13/Pro13s** with i5/i7 CPU. ![image](https://user-images.githubusercontent.com/14228455/75123265-36130f00-56a6-11ea-9573-a50ffa4692fe.png)
> ![image](https://user-images.githubusercontent.com/14228455/75123275-44f9c180-56a6-11ea-8929-a55486183053.png)

Well yeah that's correct mine is msi prestige 15 which packs the same i7 10710U as stated in the title. So I thought that it could work. Also Im using my own custom efi which makes me pass the ++++++ wait but gives me the MACH reboot error after patching Kernel/apply kexts. I don't know if you know about that error 
![0F013004-F11F-4581-8B2D-F0AA1A5B2F1F](https://user-images.githubusercontent.com/36641566/75123375-1a5c3880-56a7-11ea-82ec-dbd784c775df.jpeg)

**Comment by gungun974** [comment]
know that this issue has nothing to do with Lenovo XiaoXin Pro13 but has there been progress to make the MSI prestige 15 compatible?

**Comment by Yusepp** [comment]
> know that this issue has nothing to do with Lenovo XiaoXin Pro13 but has there been progress to make the MSI prestige 15 compatible?

The maximum I reached was the screen shown in the last comment, I'm waiting to 10.15.4  since beta 4 included some code related to cometlake, imo they will be compatible natively in that version

**Comment by olmostblue** [comment]
Hi, I have the same laptop, MSI Prestige 15 and I would like to start install macOS on it, do you have solved your issues?

**Comment by rlymdk** [comment]
> > know that this issue has nothing to do with Lenovo XiaoXin Pro13 but has there been progress to make the MSI prestige 15 compatible?
> 
> The maximum I reached was the screen shown in the last comment, I'm waiting to 10.15.4 since beta 4 included some code related to cometlake, imo they will be compatible natively in that version

Hi, any news or progress?

**Comment by hla63** [comment]
hello, 
(not exactly the same as prestige 15) i have the modern 15 with 10210u
I am able to start the catalina installation with opencore :
-> Booter ->
AvoidRuntimeDefrag ,DevirtualiseMmio
 EnableWriteUnprotector & ProtectUefiService needs to be set to true
& kernel -> DisableIoMapper

**Comment by olmostblue** [comment]
> hello,
> (not exactly the same as prestige 15) i have the modern 15 with 10210u
> I am able to start the catalina installation with opencore :
> -> Booter ->
> AvoidRuntimeDefrag ,DevirtualiseMmio
> EnableWriteUnprotector & ProtectUefiService needs to be set to true
> & kernel -> DisableIoMapper

Hi, can you please send your EFI? I would like to try
Thanks

**Comment by hla63** [comment]
sure
[OC_EFI.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/4593090/OC_EFI.zip)

**Comment by Yusepp** [comment]
> sure
> [OC_EFI.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/4593090/OC_EFI.zip)

How many things did you manage to get working?(like trackpad, audio, etc)?

**Comment by hla63** [comment]
for now, I just created my installation key.i have 1 acpi error to fix with SB.PCI.LPCB_EC 'QD1'.

keyboard & trackpad works.

**Comment by Yusepp** [comment]
> sure
> 
> [OC_EFI.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/4593090/OC_EFI.zip)
> 
> 

I gave a try to the OC efi but im getting the Next error, any suggests?![image](https://user-images.githubusercontent.com/36641566/81442690-5d8d5a00-9174-11ea-9b7b-7b6a117b1399.jpeg)

**Comment by hla63** [comment]
I've encountered this problem before.
Make sure DevirtualiseMmio set true .

**Comment by hla63** [comment]
[https://dortania.github.io/vanilla-laptop-guide/images/config/config-laptop.plist/icelake/booter.png](url)

**Comment by Yusepp** [comment]
> [https://dortania.github.io/vanilla-laptop-guide/OpenCore/config-laptop.plist/icelake.html#booter](url)

I took a look at that guide and configured the plist as stated, now I get a more messages(still error tho)![image](https://user-images.githubusercontent.com/36641566/81451482-e7452380-9184-11ea-8df2-1627551a8174.jpeg)

**Comment by hla63** [comment]
Cfg lock disabled ?
take a look at [https://www.tonymacx86.com/threads/guide-msi-ps63-modern-using-clover-uefi.282632/page-5#post-2031543](url) to unlock hidden bios menu. Works for me

**Comment by Yusepp** [comment]
> Cfg lock disabled ?
> 
> take a look at [https://www.tonymacx86.com/threads/guide-msi-ps63-modern-using-clover-uefi.282632/page-5#post-2031543](url) to unlock hidden bios menu. Works for me

I thought that I already disabled It(I knew about hidden bios) but I dont find the option(I revised all optioms slowly)

**Comment by hla63** [comment]
Maybe another memory fix needed.
Another way to fix:
Booter -> 
RebuildAppleMemoryMap -> true
SyncRuntimePermissions -> true
II have reworked my OC_EFI with these option & also
AvoidRuntimeDefrag -> true
Devirtualisemmio -> true
Protectuefiuser -> true

**Comment by Yusepp** [comment]
> Maybe another memory fix needed.
> Another way to fix:
> Booter ->
> RebuildAppleMemoryMap -> true
> SyncRuntimePermissions -> true
> II have reworked my OC_EFI with these option & also
> AvoidRuntimeDefrag -> true
> Devirtualisemmio -> true
> Protectuefiuser -> true
> 
> cfg lock (hidden menu)
> go to advanced->power & Performance ->CPU - Power Management Control ->CPU lock Configuration ->CFG lock

Thanks for your suggestions! I've been trying them and googling for solutions because didn't work at all. Maybe the log file can provide a more accurate info...
[opencore-2020-05-09-213047.txt](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/4604364/opencore-2020-05-09-213047.txt)

**Comment by hla63** [comment]
Try SetupVirtualMap -> true 
& RebuildAppleMemoryMap -> false

**Comment by Yusepp** [comment]
> Try SetupVirtualMap -> true
> & RebuildAppleMemoryMap -> false

Also tried this one, I'm running out of ideas...

**Comment by weidongbcn** [comment]
you can use my msi ps63 clover.

**Comment by Yusepp** [comment]
But

> you can use my msi ps63 clover.

But that MSI is based on coffe lake/whiskey lake @ 8th gen. The problem here is that this is a comet lake @ 10th gen chip

**Comment by hla63** [comment]
Dortania opencore guide had a [comet lake section ](https://dortania.github.io/OpenCore-Desktop-Guide/config.plist/comet-lake.html) now.

Also, you can re-try clover again.Clover works with [ocquirks](https://github.com/ReddestDream/OcQuirks) & the right quirks config.
[UEFI.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/4736921/UEFI.zip)
=>must be placed on EFI->CLOVER->DRIVERS->UEFI

**Comment by vaqif14** [comment]
Did anyone success?

**Comment by weidongbcn** [comment]
https://github.com/weidongbcn/Msi-Ps63-OC6.0-EFI

**Comment by Yusepp** [comment]
> https://github.com/weidongbcn/Msi-Ps63-OC6.0-EFI

This laptop uses 10th gen Intel. Then laptop you provide is an 8th generation so its not compatible

**Comment by ImEvwan** [comment]
any progress? I've had my prestige 15 since launch and have been itching to triple boot it

**Comment by Yusepp** [comment]
> > sure
> > [OC_EFI.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/4593090/OC_EFI.zip)
> 
> I gave a try to the OC efi but im getting the Next error, any suggests?![image](https://user-images.githubusercontent.com/36641566/81442690-5d8d5a00-9174-11ea-9b7b-7b6a117b1399.jpeg)

This was the best I tried. Never tried new stuff but i didn't see any news at other forums. 
Clover cant get past of: MACH reboot error
OC the quoted error.

**Comment by hla63** [comment]
https://github.com/hla63/Msi-modern-15-Hackintosh

**Comment by ImEvwan** [comment]
> https://github.com/hla63/Msi-modern-15-Hackintosh

I was able to use this to get through the web recovery, past the web installation, but in the actual macos setup I get kernel panics before it finishes and it's like I'm on a timer. We're very close even though that's clover, not oc.

**Comment by ImEvwan** [comment]
nvm I was able to go through setup fast enough to complete it, but once in macos the computer just hard shuts down, and while booting it seems like a kernel panic as it says something along those lines. I installed macos in the second SSD bay on a sabrent 256gb rocket. 
![20200811_105732](https://user-images.githubusercontent.com/61602941/89913486-c811c400-dbc1-11ea-88f6-6b0454270d96.jpg)
![20200811_105740](https://user-images.githubusercontent.com/61602941/89913489-c8aa5a80-dbc1-11ea-8fa8-c042f3860324.jpg)
![20200811_105755](https://user-images.githubusercontent.com/61602941/89913493-c942f100-dbc1-11ea-9bb3-024eb132b563.jpg)

**Comment by ImEvwan** [comment]
First reboot after panic gets me this. Then I just restart and boot again
![20200811_110038](https://user-images.githubusercontent.com/61602941/89913668-fc858000-dbc1-11ea-8ed9-fa95e7c496d5.jpg)

**Comment by ImEvwan** [comment]
also wrong trackpad driver/kext. Trackpad left click does something weird. Here is the panic error
![20200811_110200](https://user-images.githubusercontent.com/61602941/89914028-6867e880-dbc2-11ea-9727-39a00107388c.jpg)
![20200811_110203](https://user-images.githubusercontent.com/61602941/89914031-69007f00-dbc2-11ea-9d61-41f6b79c8fb0.jpg)
![20200811_110205](https://user-images.githubusercontent.com/61602941/89914036-69991580-dbc2-11ea-94a2-1294cbbfdfe6.jpg)
![20200811_110207](https://user-images.githubusercontent.com/61602941/89914038-6a31ac00-dbc2-11ea-8672-9234e26dc210.jpg)

**Comment by ImEvwan** [comment]
Sometimes it doesnt boot properly, but otherwise success. No more kernel panics. I swapped the wifi card for a 7260 (originally ax200)

**Comment by gungun974** [comment]
@ImEvwan. How did you manage to make macos work on the msi prestige? I could see that you use the EFI of hla63 but when I use it I find myself blocked in verbose on gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0
Could you help me or give me your EFI if you had to modify it?

**Comment by ImEvwan** [comment]
I literally used the modern EFI. @gungun974 . It's super buggy and will no longer boot lol. Someone with braincells should use the modern EFI to get the prestige to work. I have no experience with this stuff.

**Comment by hla63** [comment]
https://github.com/wgjas2/MSI-Prestige-15-Hackintosh

**Comment by ImEvwan** [comment]
> https://github.com/wgjas2/MSI-Prestige-15-Hackintosh

Couldnt get this to work @hla63 . The first time I got into the installer but every time I boot into clover OR opencore I either cant boot into the recovery/install partition or straight up don't see it. I have no clue what I'm doing wrong.

**Comment by Yusepp** [comment]
> https://github.com/wgjas2/MSI-Prestige-15-Hackintosh

Manage to make it works! Runs smooth. Im trying tofix the wifi tho

**Comment by ImEvwan** [comment]
> > https://github.com/wgjas2/MSI-Prestige-15-Hackintosh
> 
> Manage to make it works! Runs smooth. Im trying tofix the wifi tho

HOW? Can you make a guide or help a fellow out?

**Comment by Yusepp** [comment]
literally copy pasted the efi nothing more. Its normal that sometimes fails to boot. 1/3 tries fails

**Comment by ImEvwan** [comment]
> literally copy pasted the efi nothing more. Its normal that sometimes fails to boot. 1/3 tries fails

My laptop has had so many problems from the start, I'm going to RMA my laptop and retry this whole process. I got half way through the install process the first time and since then I haven't been able to even see the recovery partition after retrying a dozen times.

**Comment by Yusepp** [comment]
> https://github.com/wgjas2/MSI-Prestige-15-Hackintosh

Since that efi folder works perfectly I'm going to close this issue, thanks to all people who collaborated!
