### ISSUE TITLE
请问  安装完成后替换efi是替换的U盘中的efi还是硬盘中的？

### ISSUE THREAD

**Issue by kuangxiaoye** [daliansky/XiaoXinPro-13-hackintosh#41]

**Comment by cytown** [comment]
晕，当然是替换硬盘中的，u盘不用动，以后万一还用得着。

**Comment by M69W** [comment]
正常来说，U盘中的是`通用版EFI`，不具备小新pro13 专属的`EFI`

**Comment by cytown** [comment]
> 正常来说，U盘中的是`通用版EFI`，不具备小新pro13 专属的`EFI`

我建议既然这里是小新pro13的地方，就应该放专属的会比较好，否则大家都晕菜了。

**Comment by M69W** [comment]
系统文件太大，单独封装一个带EFI的系统不现实
大部分EFI提供带installer-recovery的plist
分清替换和覆盖的区分就好

**Comment by cytown** [comment]
> 系统文件太大，单独封装一个带EFI的系统不现实
> 大部分EFI提供带installer-recovery的plist
> 分清替换和覆盖的区分就好

我觉得，起码该有的说明不要省，这么多release文件，说实话根本不知道什么场合该用哪个，如何使用。

比如clover的话，是可以选择使用的config plist文件的，那么只需要选项里面选择对应的就可以。但OC好像并不行，必须命名config_xxxx_recovery.pilist为config.plist才能在OC中使用，但根本没有文档说明这个。

还有oc-pro13和oc-pro13mod有什么区别，随便用哪个都行么？060目前并不是正式版相对于059有什么进步，也没有说。

**Comment by M69W** [comment]
> > 系统文件太大，单独封装一个带EFI的系统不现实
> > 大部分EFI提供带installer-recovery的plist
> > 分清替换和覆盖的区分就好
> 
> 我觉得，起码该有的说明不要省，这么多release文件，说实话根本不知道什么场合该用哪个，如何使用。
> 
> 比如clover的话，是可以选择使用的config plist文件的，那么只需要选项里面选择对应的就可以。但OC好像并不行，必须命名config_xxxx_recovery.pilist为config.plist才能在OC中使用，但根本没有文档说明这个。
> 
> 还有oc-pro13和oc-pro13mod有什么区别，随便用哪个都行么？060目前并不是正式版相对于059有什么进步，也没有说。

这么多releases ，不知道怎么用
就应该看完再用，没必要每次发releases 都要说明。
[v2.1](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1)

**Comment by cytown** [comment]
> > > 系统文件太大，单独封装一个带EFI的系统不现实
> > > 大部分EFI提供带installer-recovery的plist
> > > 分清替换和覆盖的区分就好
> > 
> > 
> > 我觉得，起码该有的说明不要省，这么多release文件，说实话根本不知道什么场合该用哪个，如何使用。
> > 比如clover的话，是可以选择使用的config plist文件的，那么只需要选项里面选择对应的就可以。但OC好像并不行，必须命名config_xxxx_recovery.pilist为config.plist才能在OC中使用，但根本没有文档说明这个。
> > 还有oc-pro13和oc-pro13mod有什么区别，随便用哪个都行么？060目前并不是正式版相对于059有什么进步，也没有说。
> 
> 这么多releases ，不知道怎么用
> 就应该看完再用，没必要每次发releases 都要说明。
> [v2.1](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.1)

我也觉得没必要每次发release都要说明，而是应该在项目的README.md里面统一说明一次，把所有的release文件都列进去就行。

**Comment by cytown** [comment]
@M69W 请问一下，如果060的OC要想显示install或recovery配置，以及多系统支持，是否也要增加ACPI-> Quirks-> EnableForAll,Booter-> Quirks-> EnableForAll,Misc->boot->SkipCustomEntryCheck 三个选项？？？

**Comment by WangYeCoder** [comment]
我已经刷完了   谢谢
