### ISSUE TITLE
睡眠无法唤醒

### ISSUE THREAD

**Issue by cytown** [daliansky/XiaoXinPro-13-hackintosh#42]
不是必现，设置成hibernatemode 3以后，偶尔睡眠以后，按电源键没有反应。

最后只能长按强制关机。

p.s. 在电池状态下，没有设置power nap，但系统依然会被定时Wake reason: RTC (Alarm)
目前每小时休眠耗电1%，最新的测试版OC 060 + 15.6

i7 + DW1820A

**Comment by stevezhengshiqi** [comment]
RTC Alarm问题可通过添加并启用ACDT给的`Disable RTC wake scheduling`来解决：
https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist#L435-L462

**Comment by cytown** [comment]
> RTC Alarm问题可通过添加并启用ACDT给的 `Disable RTC wake scheduling` 补丁来解决：
> https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist#L435-L462

好的，我会找时间试试，谢谢。

**Comment by cytown** [comment]
有4天的没有睡死的问题了，暂时关闭吧。

**Comment by cytown** [comment]
安装了宪武29号的版本后，发现待机耗电出现问题了，基本上每小时消耗增加到了2%，原来的系统是1%左右，但我的power设置没有问题：

```
# pmset -g
System-wide power settings:
Currently in use:
 standby              1
 halfdim              1
 hibernatefile        /var/vm/sleepimage
 proximitywake        0
 gpuswitch            0
 powernap             0
 disksleep            10
 standbydelayhigh     86400
 sleep                1
 hibernatemode        3
 ttyskeepawake        0
 displaysleep         2
 tcpkeepalive         0
 highstandbythreshold 50
 standbydelaylow      10800
```

log last 1d查看发现休眠到唤醒中间完全没有日志，怪了。

**Comment by cytown** [comment]
最新的10.06的版本，依然会有睡死的情况。

**Comment by M69W** [comment]
默认情况下，电源键唤醒，暂时没发先睡死问题，
只发现睡眠过程中没电后自动关机了

**Comment by cytown** [comment]
我用了几个月了，不可能是不会按电源键导致的。现在问题是，按电源键无效，只能长按5秒后强制关机，然后重新启动。

**Comment by cytown** [comment]
最近几天每天都睡死，幸好2.2.9出了，要去试试新版本是否稳定了。

**Comment by cytown** [comment]
2.2.9启动不停重启，包括QQ群里面传的064版本也是一样，只能用回2.2.8了，凑合用吧。。。

**Comment by cytown** [comment]
2.3.2可以用了，EFI-OC.0.6.4.-PRO13-2020-12-25。
但还是会有睡死问题。

还没开始用2.3.3。

**Comment by cytown** [comment]
最新的2.3.5没有出现睡死现象，不过我的睡眠模式改成0了。不知道3是否还是会睡死。

**Comment by cytown** [comment]
昨晚试了mode3，今天是没有问题，正常启动了。不过mode0和3在耗电上没太大区别，15个小时耗电25左右。

**Comment by cytown** [comment]
> 昨晚试了mode3，今天是没有问题，正常启动了。不过mode0和3在耗电上没太大区别，15个小时耗电25左右。

今天早上mode3睡死了，看来还是要换回0才行。。。

**Comment by cytown** [comment]
最新的3.0.0复现。。。

**Comment by cytown** [comment]
发现两个问题，一个是有时不休眠，另一个是有时休眠了不能再次唤醒，不确定是否同一个问题。。。

3.0.0，就修改了3码，其它没动。哦，加了yogasmcpane的patch。

**Comment by cytown** [comment]
基本上每天都会出现不能唤醒的情况。。。见鬼了。。。

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)，设置25睡眠
有问题再 reopened
