### ISSUE TITLE
从10.15.4升级到10.15.6失败的一些疑问

### ISSUE THREAD

**Issue by AaronJny** [daliansky/XiaoXinPro-13-hackintosh#44]
首先，感谢大佬们的贡献。

我当前使用的系统版本是Clover引导的15.4，我尝试将它升级到15.6（非11）。我的操作步骤如下：
1. 替换最新的Clover EFI
2. 在设置中下载15.6的更新包，大概5个G。
3. 点击安装，之后电脑自动重启。然后clover里面多了一个安装的选项（之前只有windows和15.4两个）。
4. 选择安装，跑一段代码之后就重启了，又进入clover页面。然后，选安装就一直这么循环，而选启动mac进来就是15.4……

怎么破，是我操作不对吗？
求大佬们指点，非常感激！

**Comment by LitCcc** [comment]
亲测使用最新版OC即可解决

**Comment by AaronJny** [comment]
> 亲测使用最新版OC即可解决

非常感谢，花了一下午折腾Clover转OC，最后使用v2.1.7版本启动成功了。

最新的OC EFI我无法启动系统，而v2.1.7版本的更新仍出现和使用Clover相同的问题。

难顶。

**Comment by AaronJny** [comment]
已解决。

解决方案：
1. 刷入测试版的BIOS。
2. 设置测试版的BIOS。
3. 替换最新的OC EFI。
4. 正常更新即可。
