### ISSUE TITLE
How to flash BIOS after installing hackintosh 【黑苹果后 怎样刷BIOS】

### ISSUE THREAD

**Issue by wyq977** [daliansky/XiaoXinPro-13-hackintosh#45]
我现在已经刷了opencore 但是bios刷好像要在Windows下才可以执行 有没有什么办法可以直接刷bios 或者在pe下可不可以？

谢谢

**Comment by cytown** [comment]
pe下应该可以，你可以试试

**Comment by wyq977** [comment]
我试过优启通v3.5 和微pe 好像都不可以安装 优启通v3.5 提示说"Mount EFI failed" 微pe提示说有malware，安装不了

@cytown 你是用哪个pe的，而且macOS下制作pe好像很麻烦的样子

**Comment by cytown** [comment]
> 我试过优启通v3.5 和微pe 好像都不可以安装 优启通v3.5 提示说"Mount EFI failed" 微pe提示说有malware，安装不了
> 
> @cytown 你是用哪个pe的，而且macOS下制作pe好像很麻烦的样子

我用的就是小兵的那个catalina的安装盘，带一个pe。

**Comment by wyq977** [comment]
@cytown 谢谢啦 我再试一下 我先关了 如果可以再update一下
