### ISSUE TITLE
i7 2020版无法唤醒(已解决)

### ISSUE THREAD

**Issue by 844704781** [daliansky/XiaoXinPro-13-hackintosh#48]
硬盘是intel 760p，用的是clover引导，efi用的是2.2.0版本。
现象:
盖上二十秒后 ，不管是按键盘任意键还是电源键都无法唤醒，但是电源灯在亮，只有强制重启才能正常使用(无法唤醒) 。

**Comment by 844704781** [comment]
已解决，clover引导后就是不会唤醒，但是使用oc引导就可以电源键唤醒

**Comment by 844704781** [comment]
触摸板不灵敏的解决办法:
当你发现触摸板不灵敏后，可以尝试关闭键盘灯(fn+空格)，我的是i7+2020版本，实测这方法有效。但是实际体验，触摸板还是没有win10用的舒服(个人感觉)，总感觉有时候会误触，希望有解决办法的同学贡献出解决办法

**Comment by cytown** [comment]
触摸板误触的原因在于触摸板驱动的问题，x、y设定不对，导致系统认为的触摸板的边距大于实际的边距，这样误触系统判断失误。解决方法只有调教触摸板的边距才行。这个没接触过，谁知道如何校准？
