### ISSUE TITLE
连接个人热点问题

### ISSUE THREAD

**Issue by duanqichao** [daliansky/XiaoXinPro-13-hackintosh#52]
问题机器：小新pro13 2020，i5，dw1820a。系统 catalina
问题描述：连接跟机器同一 appleid 的 iphone 个人热点十分困难，基本连不上，蓝牙和线连都可以连上，连接非同一 appleid 的设备（家庭共享，手机会弹出是否同意连接，同意就能连上了）也没有问题。

**Comment by M69W** [comment]
[DW1820A/BCM94350ZAE/BCM94356ZEPA50DX插入的正确姿势](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)

**Comment by duanqichao** [comment]
> DW1820A/BCM94350ZAE/BCM94356ZEPA50DX插入的正确姿势
看了好长时间这个帖子，也试了，不行，你这边也是dw1820a这个卡吗，没有问题？

**Comment by IazgnoT** [comment]
请问这个问题你解决了吗，我也遇到一样的情况
