### ISSUE TITLE
AX201是否需要屏蔽。15.6 使用中屏幕卡住并自动重启

### ISSUE THREAD

**Issue by ukhack** [daliansky/XiaoXinPro-13-hackintosh#53]
跟 #40 描述的内容很像，就是在正常的使用中会突然卡住然后电脑重启。
网卡是AX201，我看其他网卡解决方案好像是屏蔽金手指，AX201也需要么？

**Comment by ukhack** [comment]
谢谢回复。
在和SN550对比下，已经确认是硬盘海康威视C2000 PRO的问题。海康威视在macOS下存在掉盘情况
目前换了SN550，并打上了nvmefix补丁，不知道您是否使用过这个补丁，有什么明显的效果么？

> AX201 / AX200 不需要屏蔽，
> 已使用AX201 / AX200 将近一个月，并无此现象
> 
> 另外：如果能提供日志，相信会让想提供帮忙人更加了解你遇到的问题

**Comment by laoxiajiadeyun** [comment]
> 谢谢回复。
> 在和SN550对比下，已经确认是硬盘海康威视C2000 PRO的问题。海康威视在macOS下存在掉盘情况
> 目前换了SN550，并打上了nvmefix补丁，不知道您是否使用过这个补丁，有什么明显的效果么？
> 
> > AX201 / AX200 不需要屏蔽，
> > 已使用AX201 / AX200 将近一个月，并无此现象
> > 另外：如果能提供日志，相信会让想提供帮忙人更加了解你遇到的问题

正准备换c2000 pro装 这个真的会掉盘吗？请问一下有没有相关链接啊
