### ISSUE TITLE
Applekeystore operation failed

### ISSUE THREAD

**Issue by ctwillson** [daliansky/XiaoXinPro-13-hackintosh#54]
![595A1117-6B3C-4F1F-B82A-073D5A652D33](https://user-images.githubusercontent.com/16146306/90971326-ae696880-e541-11ea-983c-af7db7193d6d.jpeg)
最新的clover 一直卡在这里进不了系统了

**Comment by M69W** [comment]
推荐 使用 [XiaoXinPro-13-hackintosh v3.0.8](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.8)
有问题再 reopened
