### ISSUE TITLE
更新10代触控板驱动（2.4.4）后触控板失灵，找不到触控板

### ISSUE THREAD

**Issue by q944093** [daliansky/XiaoXinPro-13-hackintosh#57]
驱动已加载但未起作用，换回2.4.3后正常

**Comment by M69W** [comment]
i7 11beta4使用正常

**Comment by yalay** [comment]
我也是，比较高概率重启后触摸板不可用，只能再重启。我是2.2.5版本

看更新记录是删除了默认的驱动
> 删除(屏蔽)macOS内置触摸板驱动

**Comment by wklxd** [comment]
2.2.6的触摸板，目前ok
