### ISSUE TITLE
最新版的 OC 配置显示屏亮度太亮

### ISSUE THREAD

**Issue by nujabse** [daliansky/XiaoXinPro-13-hackintosh#61]
使用 9-17 版本的 OC，发现即使屏幕背光亮度调到最低还是很亮，约为以前版本的亮度中档。能否设置让屏幕背光最低档更暗一些，或者提高背光调节的级数？经常需要在夜间使用电脑，背光太亮有些难受。

**Comment by sujambin** [comment]
+1

**Comment by M69W** [comment]
这个问题是在 [XiaoXinPro-13-hackintosh v2.2.5](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.2.5)（09-04-2020）版本开始替换新的处理亮度补丁衍生出来的

**Comment by Mintimate** [comment]
换成EFI-OC062-PRO13，亮度正常了，不会过亮了
