### ISSUE TITLE
屏幕亮度不能保存

### ISSUE THREAD

**Issue by xiaobai403** [daliansky/XiaoXinPro-13-hackintosh#62]
* 问题：屏幕亮度不能保存，在睡眠或者是关机重启后，屏幕的亮度总是变为一个固定值(一般是三格亮度)。
* 使用的是OC v2.7.7
* 重置nvram后可以起作用。但是在很短的时间内会再次失效。

**Comment by M69W** [comment]
已解决 [v2.3.5](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.3.5)
