### ISSUE TITLE
音响用着用着没声音

### ISSUE THREAD

**Issue by onnonn** [daliansky/XiaoXinPro-13-hackintosh#63]
v2.7.7 i7 2019 Chrome播放视频用着用着音响就没有声音，手动在设置里面切换内置扬声器和耳机一次，能好一会，过一会还是没声音（没有插耳机不知道为啥会有耳机输出的选项）

**Comment by yalay** [comment]
你插个耳机后在切换到内置扬声器，之后就好了。拔掉耳机也没事

**Comment by nekomiao123** [comment]
我也有这个问题 而且有时候插着耳机也会这样

**Comment by M69W** [comment]
这个问题 经常在 `断开 电源时 出现`，暂时无解。

**Comment by M69W** [comment]
**尝试设置如下，layout-id 为11(不一定用11)**
```diff
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1C,0x0)</key>
			<dict>
				<key>pci-aspm-default</key>
				<data>AgAAAA==</data>
			</dict>
                        ...
+			<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
+			<dict>
+				<key>alc-delay</key>
+				<integer>500</integer>
+				<key>#alc-verbs</key>
+				<data>
+				AQAAAA==
+				</data>
+				<key>layout-id</key>
+				<integer>11</integer>
+			</dict>
			...
		</dict>
	</dict>
```

**Comment by M69W** [comment]
断开电源
已测试2小时，正常使用中

**Comment by M69W** [comment]
使用一段时间，暂无重现此问题。

鉴于只有一个人测试(我)，
而且没有其他人继续跟进测试此问题。

先关闭，如有疑问再 reopen.

**Comment by Xhichn** [comment]
> **尝试设置如下，layout-id 为11(不一定用11)**
> 
> ```diff
> <key>DeviceProperties</key>
> 	<dict>
> 		<key>Add</key>
> 		<dict>
> 			<key>PciRoot(0x0)/Pci(0x1C,0x0)</key>
> 			<dict>
> 				<key>pci-aspm-default</key>
> 				<data>AgAAAA==</data>
> 			</dict>
>                         ...
> +			<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
> +			<dict>
> +				<key>alc-delay</key>
> +				<integer>500</integer>
> +				<key>#alc-verbs</key>
> +				<data>
> +				AQAAAA==
> +				</data>
> +				<key>layout-id</key>
> +				<integer>11</integer>
> +			</dict>
> 			...
> 		</dict>
> 	</dict>
> ```

如上设置后仍然出现如[issue#81](https://github.com/daliansky/XiaoXinPro-13-hackintosh/issues/81)的问题，断开电源一段时间后有线耳机突然无声，重新插入也只有部分音频。而扬声器与蓝牙耳机不受该问题影响。

**Comment by M69W** [comment]
OC什么版本？

**Comment by Xhichn** [comment]
> OC什么版本？

机型：联想小新Pro13 IML 2019 i7-10710U
OC 版本：0.6.8 Release
macOS 版本：11.3.1
AppleALC 版本：1.5.8
Codec ID：11

经过数次尝试，我觉得这个问题与**电脑冷启动时耳机是否连接**有关。

以下是我的数次测试结果，均是测试在不连接电源下启动电脑对耳机音频输出的影响：

| 测试时长 | 播放设备 | 是否出现异常 | 电源状态                 | 备注                               | 重新拔插耳机后的变化 |
| -------- | -------- | ------------ | ------------------------ | ---------------------------------- | -------------------- |
| 22m      | 有线耳机 | 无           | 断开电源冷启动           | 开机时已插上耳机                   | 正常                 |
| 21m      | 有线耳机 | 无           | 开机状态下接入电源又拔出 | 接入电源时与移除电源时，耳机未拔出 | 正常                 |
| 播放时立即异常    | 有线耳机 | 耳机无声     | 断开电源冷启动           | 开机时耳机拔出                     | 耳机声音异常         |
| 播放时立即异常        | 有线耳机 | 声音异常     | 断开电源重启             | 开机时耳机拔出                     | 耳机声音异常或爆音   |
| 13m      | 有线耳机 | 无           | 断开电源冷启动           | 开机时已插上耳机                   | 正常                 |

测试方式为电池供电下通过Apple Music播放音乐，鉴于出现异常前所需时间很短（一般为1～2分钟），每次测试的时间应该不需要很长

似乎耳机与扬声器的问题是一起出现的，如果耳机声音没问题，扬声器应该也不会出现突然无声的问题

目前的数据还是较少，接下来我会多测试几次来检验这个结论

**Comment by M69W** [comment]
我那边目前只测试了内置喇叭，多次测试结果表明，已经不再出现异常。

至于耳机，太多变量了。
不同声卡ID 也可能出现不同结果。
所以耳机就没有特意测试。

**Comment by brandbao** [comment]
> **尝试设置如下，layout-id 为11(不一定用11)**
> 
> ```diff
> <key>DeviceProperties</key>
> 	<dict>
> 		<key>Add</key>
> 		<dict>
> 			<key>PciRoot(0x0)/Pci(0x1C,0x0)</key>
> 			<dict>
> 				<key>pci-aspm-default</key>
> 				<data>AgAAAA==</data>
> 			</dict>
>                         ...
> +			<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
> +			<dict>
> +				<key>alc-delay</key>
> +				<integer>500</integer>
> +				<key>#alc-verbs</key>
> +				<data>
> +				AQAAAA==
> +				</data>
> +				<key>layout-id</key>
> +				<integer>11</integer>
> +			</dict>
> 			...
> 		</dict>
> 	</dict>
> ```

我也是遇到这个问题，想试试这个方法。
但是一只不太明白，这种xml格式的文本如何写到config.plist里面去
以前一直用properTree来该config.plist，这个是不是得用opencore configurator来改，但是用configurator打开之后好像也找不到黏贴的地方，是需要一行一行新增变量进去吗？求点个明路。

**Comment by xiaobai403** [comment]
应该和输入有关。我觉得是小新默认的麦克风无法驱动的问题。在睡眠唤醒后，出现耳机没有声音的情况下，在接上一个蓝牙耳机后，也就是输入设备多出一个选项后，声音恢复正常。

**Comment by M69W** [comment]
> 我也偶然发现一个临时解决的办法：打开 **系统偏好设置** -> **声音** ，选择 **输入** 选项卡，声音就出现了，应该是和输入有关。只要一直保持这个系统设置界面开启，声音就能正常输出。

+1。
我以为例外就写进 Wiki。
小新这声卡太神奇了

**Comment by wyq977** [comment]
这个问题还一直存在吗？@Xhichn

我也一直有这个问题 不插电源时候的时候耳机会时不时断开 得打开设置才能重新听到

alcid=100/11都会有这个问题

**Comment by wyq977** [comment]
还有两三个问题

1. 开机时插着耳机会有刺耳的高频噪音，只有几秒
2. 偶尔会听到高频的爆炸声 不太好描述 类似于爆音

**Comment by xiaobai403** [comment]
你可以试试下载 Background Music 这个软件。安装过后，它会虚拟出一个输入和输出设备。这样睡眠之后应该就不会出现没有声音的情况。

**Comment by spuuhv** [comment]
> 你可以试试下载 Background Music 这个软件。安装过后，它会虚拟出一个输入和输出设备。这样睡眠之后应该就不会出现没有声音的情况。
试了一下没有效果 还是会出现

**Comment by M69W** [comment]
建议使用非100 声卡id，如11等
[ 小新pro13的声卡ID设置](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/%E5%A3%B0%E5%8D%A1)
有问题 reopened
