### ISSUE TITLE
最新的 OC 中似乎无法正确地显示电池剩余时间

### ISSUE THREAD

**Issue by nujabse** [daliansky/XiaoXinPro-13-hackintosh#66]
<img width="1094" alt="图片" src="https://user-images.githubusercontent.com/9455367/96364065-05b73e00-116b-11eb-8e95-37a0a68373e8.png">
试用了一下最新的 10-06-2020 发布的 OC，发现在这一版本下活动监视器中始终无法显示电池剩余时间，永远是 0:00. Mac OS 系统版本号是 10.15.7。尝试过 reset NVRAM 和 clear NVRAM 但是没有效果。切换回七月份发布的 OC 又可以显示剩余时间了。

**Comment by cytown** [comment]
确实如此，我也复现了，100%复现。

**Comment by M69W** [comment]
+1

**Comment by ruigemen** [comment]
我也是，等待更新

**Comment by wklxd** [comment]
你不说，我都不知道2.2.7可以看到电池时间

**Comment by amisu233** [comment]
这个问题很容易处理，修改smc那个电源kext改成acpi的kext就行了

**Comment by nujabse** [comment]
@amisu233  请问怎么修改 smc 的kext 为 acpi 的kext？

**Comment by amisu233** [comment]
@nujabse 
![image](https://user-images.githubusercontent.com/20884723/101276736-eabb8e80-37e9-11eb-84ea-e50ef325a9db.png)
更换驱动 之前用的是smc开头的电源管理 
更换为ACPIBatteryManager.kext   就可以了

**Comment by M69W** [comment]
> @amisu233 请问怎么修改 smc 的kext 为 acpi 的kext？

这个驱动很久没更新了，
之前在别的机子上因为循环次数过多，也换这个驱动正常使用

**Comment by M69W** [comment]
> > @amisu233 请问怎么修改 smc 的kext 为 acpi 的kext？
> 
> 这个驱动很久没更新了，
> 之前在别的机子上因为循环次数过多，也换这个驱动正常使用


https://github.com/RehabMan/OS-X-ACPI-Battery-Driver
https://bitbucket.org/RehabMan/os-x-acpi-battery-driver/downloads/

**Comment by jiangbeilaodao** [comment]
这个问题修正通过修正电池补丁可以解决

**Comment by nujabse** [comment]
@jiangbeilaodao 有详细教程可以分享吗？

**Comment by jiangbeilaodao** [comment]
https://github.com/acidanthera/VirtualSMC/blob/master/Docs/Battery%20Information%20Supplement.md

**Comment by Hush-vv** [comment]
[SSDT-BATS-PRO13.aml.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5938383/SSDT-BATS-PRO13.aml.zip)
更新ssdt一下就下来

**Comment by Hush-vv** [comment]
更新一下SSDT-BATS-PRO13.aml就行了
[SSDT-BATS-PRO13.aml.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5938385/SSDT-BATS-PRO13.aml.zip)

**Comment by nujabse** [comment]
更新了 SSDT-BATS-PRO13.aml 之后，确实能够正确显示剩余电量了，非常感谢！

**Comment by M69W** [comment]
@nujabse @Hush-vv 
上面的文件只是简单测试【能显示剩余时间和能显示充满时间】，
但只是我对比之前的SSDT复制粘贴初步看到结果，
不知道有没有什么不良，具体最后的更新。
可能有变也可能不变。

当然先用着观察一下帮忙测试反馈的话，非常感谢。

**Comment by M69W** [comment]
使用一段时间后，暂无发现不良现象。
