### ISSUE TITLE
更新Big Sur 1820a无法驱动

### ISSUE THREAD

**Issue by Smileandlove** [daliansky/XiaoXinPro-13-hackintosh#68]
原来使用的是15.7的系统，EFI是v2.2.8。
更新了Big Sur之后，先进windows后进mac可以暂时驱动1820a网卡，蓝牙在efi注入驱动后完全正常。
第二次重启后蓝牙正常驱动，但是wifi一直是未找到硬件的状态，需要再次进入windows再重启进mac来恢复驱动。
现在用的还是v2.2.8的EFI（2.2.9好像有点问题）

**Comment by Smileandlove** [comment]
<img width="1280" alt="截屏2020-11-07 下午7 21 06" src="https://user-images.githubusercontent.com/74047458/98449846-55b46f80-212f-11eb-8da2-f8486872a423.png">

**Comment by Smileandlove** [comment]
![截屏2020-11-07 下午72106](https://user-images.githubusercontent.com/74047458/98449979-74673600-2130-11eb-9771-590c2a3ce2e2.png)

**Comment by skrbug** [comment]
我也遇到这样的问题了，有时候wifi打不开

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/554
试试这个EFI的相关设置
