### ISSUE TITLE
外接 typec 显示器无法开启 4k 60hz

### ISSUE THREAD

**Issue by minbox-x** [daliansky/XiaoXinPro-13-hackintosh#69]
非常感谢提供的efi文件，所有功能都基本上正常，对我来说，最大的问题是外接显示器无法4k60hz输出。

我的显示器是戴尔的u2720qm，使用c2c线进行连接；使用的efi文件是063版本的1820a；系统版本号是10.15.7。

显示输出情况：30hz时无论什么分辨率和是否开启hidpi都基本显示正常，但60hz时基本上所有分辨率都黑屏。从内部的监视器来看是能输出的4k60的，但显示器就是黑屏，有时候会闪现一下60hz然后继续黑屏。

请问这种情况该如何解决，能否提供下解决思路？
<img width="819" alt="截屏2020-11-18 下午4 59 41" src="https://user-images.githubusercontent.com/48126297/99606913-86ae6300-29bf-11eb-97cb-d345fd61bbd5.png">

**Comment by Hush-vv** [comment]
AAPL,ig-platform-id data=04 00 A5 3E
device-id data=A5 3E 00 00

**Comment by minbox-x** [comment]
> AAPL,ig-platform-id data=04 00 A5 3E
> device-id data=A5 3E 00 00

感谢你的回复，我按照提示更改了 AAPL,ig-platform-id 和 device-id ， 现在外接已经一切正常了。但有时候开机时，内建显示器会产生花屏，但只要合盖强制睡眠再唤醒后一般都能恢复正常，已经不影响使用。再次感谢你！

花屏情况如下图所示，不知道问题能否解决。
![Uploading huaping.png…]()

**Comment by Hush-vv** [comment]
> AAPL，ig-platform-id data = 04 00 A5 3E
> 设备ID数据= A5 3E 00 00
> 
> 感谢你的回复，我按照提示更改了AAPL，ig-platform-id和device-id，现在已经已经一切正常了。但有时开机时，内建显示器会产生花屏，但只要合盖强制睡眠再唤醒后一般都能恢复正常，已经不影响使用。再次感谢你！
> 
> 花屏情况如下图所示，不知道问题能否解决。



<img width="800" alt="QQ20201119-223736@2x" src="https://user-images.githubusercontent.com/61744850/99680448-09b2e480-2ab8-11eb-8ddf-5dedca3f8288.png">
[config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5567425/config.plist.zip)
加入这些或许可以解决部分，

**Comment by minbox-x** [comment]
> > AAPL，ig-platform-id data = 04 00 A5 3E
> > 设备ID数据= A5 3E 00 00
> > 感谢你的回复，我按照提示更改了AAPL，ig-platform-id和device-id，现在已经已经一切正常了。但有时开机时，内建显示器会产生花屏，但只要合盖强制睡眠再唤醒后一般都能恢复正常，已经不影响使用。再次感谢你！
> > 花屏情况如下图所示，不知道问题能否解决。
> 
> <img alt="QQ20201119-223736@2x" width="800" src="https://user-images.githubusercontent.com/61744850/99680448-09b2e480-2ab8-11eb-8ddf-5dedca3f8288.png">
> 
> [config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5567425/config.plist.zip) 加入这些或许可以解决部分，

感谢你的回复，我添加了内屏的epid并修改了显存 ，但好像并没有什么好转的现象。

**Comment by Owoeo** [comment]
> > > AAPL，ig-platform-id data = 04 00 A5 3E
> > > 设备ID数据= A5 3E 00 00
> > > 感谢你的回复，我按照提示更改了AAPL，ig-platform-id和device-id，现在已经已经一切正常了。但有时开机时，内建显示器会产生花屏，但只要合盖强制睡眠再唤醒后一般都能恢复正常，已经不影响使用。再次感谢你！
> > > 花屏情况如下图所示，不知道问题能否解决。
> > 
> > 
> > <img alt="QQ20201119-223736@2x" width="800" src="https://user-images.githubusercontent.com/61744850/99680448-09b2e480-2ab8-11eb-8ddf-5dedca3f8288.png">
> > [config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5567425/config.plist.zip) 加入这些或许可以解决部分，
> 
> 感谢你的回复，我添加了内屏的epid并修改了显存 ，但好像并没有什么好转的现象。

内屏花屏可以尝试一下更换hidpi的分辨率

**Comment by phostann** [comment]
> AAPL,ig-platform-id data=04 00 A5 3E
> device-id data=A5 3E 00 00

非常感谢，终于能4k60 了

**Comment by akFace** [comment]
> > AAPL,ig-platform-id data=04 00 A5 3E
> > device-id data=A5 3E 00 00
> 
> 非常感谢，终于能4k60 了

你的是c-to-c线吗？我的不行，还是4k30zh。
有60hz的选项但也只能是非hdpi
像这样的低分辨率才有60hz
![image](https://user-images.githubusercontent.com/22288837/130330089-040df44f-2163-48c4-9068-e97a3f12a5af.png)

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/130338044-f24ade46-1b72-40ef-b1c0-eece96bd415d.png)
![image](https://user-images.githubusercontent.com/15809201/130338066-2ab276fd-a488-433b-a312-108a09363431.png)

**Comment by M69W** [comment]
以上截图，
基于 [v3.0.0](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v3.0.0) ，除了三码不同

不过以往的 config( EFI )设备设置基本上不变，估计是线材等问题。

**Comment by cytown** [comment]
> > AAPL，ig-platform-id data = 04 00 A5 3E
> > 设备ID数据= A5 3E 00 00
> > 感谢你的回复，我按照提示更改了AAPL，ig-platform-id和device-id，现在已经已经一切正常了。但有时开机时，内建显示器会产生花屏，但只要合盖强制睡眠再唤醒后一般都能恢复正常，已经不影响使用。再次感谢你！
> > 花屏情况如下图所示，不知道问题能否解决。
> 
> <img alt="QQ20201119-223736@2x" width="800" src="https://user-images.githubusercontent.com/61744850/99680448-09b2e480-2ab8-11eb-8ddf-5dedca3f8288.png">
> 
> [config.plist.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5567425/config.plist.zip) 加入这些或许可以解决部分，

我测试了这个，直接启动黑屏。。。
