### ISSUE TITLE
新作的安装u盘 clover启动卡住

### ISSUE THREAD

**Issue by zktz** [daliansky/XiaoXinPro-13-hackintosh#71]
我是用的 macOS Catalina 10.15.4(19E287) Installer for Clover 5109 and WEPE Support UEFI and MBR.dmg
电脑是小新pro13 2020 i7版，已经替换了EFI，用的10070u的config
启动之后

![image](https://user-images.githubusercontent.com/4505200/99923021-abfbf200-2d6e-11eb-8873-58a2aa5f346f.png)

卡在白苹果图标一宿 都没动。

**Comment by onnonn** [comment]
刷wiki里面的bios解锁显存

**Comment by evilpwn** [comment]
我的解锁了 但也是卡在这里，换OC安装一次成功

**Comment by wulie88** [comment]
> 刷wiki里面的bios解锁显存

请问怎么安装测试版bios，我安装重启后提示文件无效

**Comment by M69W** [comment]
Clover 很久没有更新，建议更新Clover 或 用 OC
