### ISSUE TITLE
最新efi文件，简化电源按键唤醒方法，无法唤醒。

### ISSUE THREAD

**Issue by gsdukbh** [daliansky/XiaoXinPro-13-hackintosh#72]
## 系统版本 
10。15.7
## oc
最新github efi文件

## 问题
电脑在开盖，自动息屏后，按电源建无法唤醒屏幕，只能通过重启解决唤醒问题 。

**Comment by q944093** [comment]
最新版这个简化操作的效果是什么呢，开盖可以不按电源键直接唤醒吗？

**Comment by M69W** [comment]
11.0.1 (20B29) 正常，跟之前一样

**Comment by gsdukbh** [comment]
> 最新版这个简化操作的效果是什么呢，开盖可以不按电源键直接唤醒吗？

对的，休眠下可以按键启动。

**Comment by q944093** [comment]
> > 最新版这个简化操作的效果是什么呢，开盖可以不按电源键直接唤醒吗？
> 
> 对的，休眠下可以按键启动。

那不是和之前版本没什么区别吗？

**Comment by gsdukbh** [comment]
> > > 最新版这个简化操作的效果是什么呢，开盖可以不按电源键直接唤醒吗？
> > 
> > 
> > 对的，休眠下可以按键启动。
> 
> 那不是和之前版本没什么区别吗？

可以直接开盖，按键唤醒，倒是偶尔，连电源建也无法唤醒。

**Comment by allentoday** [comment]
> > > > 最新版这个简化操作的效果是什么呢，开盖可以不按电源键直接唤醒吗？
> > > 
> > > 
> > > 对的，休眠下可以按键启动。
> > 
> > 
> > 那不是和之前版本没什么区别吗？
> 
> 可以直接开盖，按键唤醒，倒是偶尔，连电源建也无法唤醒。

Big Sur 正式版，遇到了类似的问题，开机第一次可以AOAC，第二次开始随机性的，可以按键或开盖唤醒（是不是就没有进入AOAC状态？），暂先回到之前的efi了

**Comment by M69W** [comment]
SSDT-PCI0.LPCB-Wake-AOAC.aml
把这个文件换回之前的看看

**Comment by cytown** [comment]
好像确实是无法唤醒几率比之前高了些。。。

**Comment by gsdukbh** [comment]
> SSDT-PCI0.LPCB-Wake-AOAC.aml
> 把这个文件换回之前的看看

哭了。 我换会上个版本的，然后几乎都不能唤醒，最近两天都不能
