### ISSUE TITLE
将F1、F2等键用作标准功能键

### ISSUE THREAD

**Issue by moxuandeng** [daliansky/XiaoXinPro-13-hackintosh#75]
在使用ide开发的时候常常会使用到F1～F12中的一些功能， 目前“系统偏好设置-键盘设置”不支持设置，有什么配置方式能够支持修改吗？

**Comment by qq452755439** [comment]
bios改呢

**Comment by moxuandeng** [comment]
> bios改呢

可以了
BIOS里将Hotkey Mode项设置为 Disable即可
