### ISSUE TITLE
v2.2.9版本在11.0.1系统下按键盘同时滑动触摸板卡顿

### ISSUE THREAD

**Issue by qq452755439** [daliansky/XiaoXinPro-13-hackintosh#76]
也不是所有键，数字键，字母键，f1-f12等同时滑动触摸板，光标基本无法滑动

**Comment by stevezhengshiqi** [comment]
@qq452755439 这是正常现象，VoodooI2C 为了缓解打字时的触控板误触问题而设计了此功能：打字时会短暂禁用触控板。
如需禁用，请打开 `VoodooI2CHID.kext/Contents/Info.plist` 并把 `VoodooI2CHIDDevice Precision Touchpad HID Event Driver` 里的 `QuietTimeAfterTyping` 数值改为0。这个值控制着 按键后禁用触控板的时间。

**Comment by M69W** [comment]
> @qq452755439 这是正常现象，VoodooI2C 为了缓解打字时的触控板误触问题而设计了此功能：打字时会短暂禁用触控板。
> 如需禁用，请打开 `VoodooI2CHID.kext/Contents/Info.plist` 并把 `VoodooI2CHIDDevice Precision Touchpad HID Event Driver` 里的 `QuietTimeAfterTyping` 数值改为0。这个值控制着 按键后禁用触控板的时间。

@qq452755439 @stevezhengshiqi 
确实可以这样设置。

另外，个人觉得大部分人在还是需要这个“防误触”功能的，并没有特意改这个值，不然下一个issue可能就是它的反例。
