### ISSUE TITLE
v2.3.1的EFI中网卡的教程会白苹果

### ISSUE THREAD

**Issue by iwsbiwy** [daliansky/XiaoXinPro-13-hackintosh#77]
按EFI中关于网卡的说明信息，修改后会卡在白苹果。
![1.png](https://i.loli.net/2020/12/14/UT3JXQPFMt17HN8.png)
---
己解决，`AirportItlwm`驱动的`AirportItlwm.kext`要改名为`AirportItlwm_Big_Sur.kext`；`itlwm`驱动无影响。

**Comment by imerdell-55** [comment]
那你有没有把对应的kext文件放到对应文件夹下，

**Comment by iwsbiwy** [comment]
> 那你有没有把对应的kext文件放到对应文件夹下，
放了。

**Comment by iwsbiwy** [comment]
己解决，下载的AirportItlwm.k
