### ISSUE TITLE
v2.3.2 无法安装

### ISSUE THREAD

**Issue by LukeTu** [daliansky/XiaoXinPro-13-hackintosh#80]
感谢最新的EFI更新！我在使用最新的v2.3.2安装系统时卡在第一次重启 显示应用软件更新时出错 请问这是什么问题呢？

![微信图片_20201226201040](https://user-images.githubusercontent.com/38886685/103151175-b61e6f80-47b6-11eb-8414-9ada2b657c02.jpg)

**Comment by LukeTu** [comment]
2.3.1也有同样状况~

**Comment by M69W** [comment]
昨晚才从11.0.1 升级到 11.1，没有问题，
注意的地方：GUI引导界面，以前显示`Installxxx`的地方显示不一样了。
重启后GUI界面显示`Macintosh HD`为`继续安装选项`

**Comment by LukeTu** [comment]
> 昨晚才从11.0.1 升级到 11.1，没有问题，
> 注意的地方：GUI引导界面，以前显示`Installxxx`的地方显示不一样了。
> 重启后GUI界面显示`Macintosh HD`为`继续安装选项`

感谢回复~ 我不是由11.01升级的 而是由11.1的镜像直接安装  我记得GUI界面选择了Install... 我现在再按您的方法试一遍

**Comment by LukeTu** [comment]
![微信图片_20201227102218](https://user-images.githubusercontent.com/38886685/103162594-80689d80-482d-11eb-9ff8-730d4c7df6a0.jpg)
在第一次读条后 GUI界面并没有Macintosh HD这一选项 选择Installer选项之后 在只剩19分钟时会卡死

**Comment by brucedu1342** [comment]
> 昨晚才从11.0.1 升级到 11.1，没有问题，
> 注意的地方：GUI引导界面，以前显示`Installxxx`的地方显示不一样了。
> 重启后GUI界面显示`Macintosh HD`为`继续安装选项`

3.2.2 我发现睡眠和蓝牙不可用。不知道前辈有无这个问题

**Comment by brucedu1342** [comment]
> 昨晚才从11.0.1 升级到 11.1，没有问题，
> 注意的地方：GUI引导界面，以前显示`Installxxx`的地方显示不一样了。
> 重启后GUI界面显示`Macintosh HD`为`继续安装选项`

谢谢前辈我犯二了，搞定了

**Comment by brucedu1342** [comment]
> 昨晚才从11.0.1 升级到 11.1，没有问题，
> 注意的地方：GUI引导界面，以前显示`Installxxx`的地方显示不一样了。
> 重启后GUI界面显示`Macintosh HD`为`继续安装选项`

Macintosh HD gui界面enter 后闪退， 然后点击原来系统安装盘打开后还是11.01，不知前辈有没有碰到类似问题

**Comment by brucedu1342** [comment]
> ![微信图片_20201227102218](https://user-images.githubusercontent.com/38886685/103162594-80689d80-482d-11eb-9ff8-730d4c7df6a0.jpg)
> 在第一次读条后 GUI界面并没有Macintosh HD这一选项 选择Installer选项之后 在只剩19分钟时会卡死

我又重装一次碰到与你一样的问题，请问前辈知道问题了吗？

**Comment by M69W** [comment]
检查一下 DVMT 和 CFGLOCK 是否已经设置好了

**Comment by LukeTu** [comment]
> 检查一下 DVMT 和 CFGLOCK 是否已经设置好了


> > ![微信图片_20201227102218](https://user-images.githubusercontent.com/38886685/103162594-80689d80-482d-11eb-9ff8-730d4c7df6a0.jpg)
> > 在第一次读条后 GUI界面并没有Macintosh HD这一选项 选择Installer选项之后 在只剩19分钟时会卡死
> 
> 我又重装一次碰到与你一样的问题，请问前辈知道问题了吗？


DVMT 和 CFGLOCK均以按照EFI说明设置好~
后面我采用了B站网友提供的小新pro13efi成功安装了(估计是基于Github OC 0.6.3的efi）
安装完成再采用GitHub上最新的efi引导也可以成功进系统，但全新安装使用该efi就是不行

**Comment by brucedu1342** [comment]
> > 检查一下 DVMT 和 CFGLOCK 是否已经设置好了
> 
> > > ![微信图片_20201227102218](https://user-images.githubusercontent.com/38886685/103162594-80689d80-482d-11eb-9ff8-730d4c7df6a0.jpg)
> > > 在第一次读条后 GUI界面并没有Macintosh HD这一选项 选择Installer选项之后 在只剩19分钟时会卡死
> > 
> > 
> > 我又重装一次碰到与你一样的问题，请问前辈知道问题了吗？
> 
> DVMT 和 CFGLOCK均以按照EFI说明设置好~
> 后面我采用了B站网友提供的小新pro13efi成功安装了(估计是基于Github OC 0.6.3的efi）
> 安装完成再采用GitHub上最新的efi引导也可以成功进系统，但全新安装使用该efi就是不行

方便share 一下是哪个efi嘛？

**Comment by Kevin3256** [comment]
曲线救国，可以用v2.3.0的efi文件安装最新big sur 11.1，安装完毕设置好后，将oc里的efi更换为最新的就可以，我是这样装好的

**Comment by brucedu1342** [comment]
> 曲线救国，可以用v2.3.0的efi文件安装最新big sur 11.1，安装完毕设置好后，将oc里的efi更换为最新的就可以，我是这样装好的

我用v2.3.0的efi会无限重启 阿西吧

**Comment by brucedu1342** [comment]
最后用换了2.2.5版装上升级后用2.3.2efi，稳健

**Comment by Bencool** [comment]
本人是北美版S540，用v2.3.2  和 v2.3.1 都没办法从11.0.1 直升到11.1，或者重新用镜像安装也出现同样的问题。后来用了隔壁的EFI 成功升级。 https://github.com/Hush-vv/Lenovo-XiaoXinPro13-Hackintosh

**Comment by LukeTu** [comment]
>    本人是北美版S540，用v2.3.2  和 v2.3.1 都没办法从11.0.1 直升到11.1，或者重新用镜像安装也出现同样的问题。后来用了隔壁的EFI 成功升级。 https://github.com/Hush-vv/Lenovo-XiaoXinPro13-Hackintosh

想请问隔壁的efi有什么区别呢

**Comment by Bencool** [comment]
> > 本人是北美版S540，用v2.3.2  和 v2.3.1 都没办法从11.0.1 直升到11.1，或者重新用镜像安装也出现同样的问题。后来用了隔壁的EFI 成功升级。 https://github.com/Hush-vv/Lenovo-XiaoXinPro13-Hackintosh
> 
> 想请问隔壁的efi有什么区别呢

Hush 的EFI做的不错。其实小兵之前xiaoxin pro的EFI也是借鉴他的。

**Comment by M69W** [comment]
试试 [v2.3.5](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.3.5)
