### ISSUE TITLE
big sur 11.2更新卡重启

### ISSUE THREAD

**Issue by LiuWhale** [daliansky/XiaoXinPro-13-hackintosh#88]
用1.6发布的EFI 进行 big sur 11.2更新，卡重启，无法更新。

**Comment by hongbaio** [comment]
估计是这个RestrictEvents.kext的原因，我我在11.2更新时黑屏，在win下取消了这个成功进入系统

**Comment by LiuWhale** [comment]
这个问题我解决了，我是通过在config里删除未启用的驱动解决的。
