### ISSUE TITLE
i7 10710U只能到3.9GHz 无法超过4.0+GHz

### ISSUE THREAD

**Issue by bywwcnll** [daliansky/XiaoXinPro-13-hackintosh#89]
如下图，是不是只能到3.9
![PNG图像](https://user-images.githubusercontent.com/14292067/106995397-c8c69400-67b9-11eb-83f8-2672f4b43c79.png)

**Comment by Hush-vv** [comment]
更换SMBIOS为MacbookPro16.2并替换SSDT-PLUG-_SB.PR00.aml即可
[SSDT-PLUG-_SB.PR00.aml.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/5939768/SSDT-PLUG-_SB.PR00.aml.zip)

**Comment by ferstar** [comment]
睿频正常, 10710U终于不再太监, 谢谢 @Hush-vv 
![image](https://user-images.githubusercontent.com/2854276/107568045-6f2ef100-6c21-11eb-8e79-8b21190980e5.png)

**Comment by Hush-vv** [comment]
> 睿频正常, 10710U终于不再太监, 谢谢 @Hush-vv
> ![image](https://user-images.githubusercontent.com/2854276/107568045-6f2ef100-6c21-11eb-8e79-8b21190980e5.png)

替换新的SSDT-PLUG-_SB.PR00并加载CPUFriend、CPUFriendDataProvider可使变频更完美（REQ与AVG基本重叠
[SSDT-PLUG-_SB.PR00.aml.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6014078/SSDT-PLUG-_SB.PR00.aml.zip)
[CPUFriend.kext.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6014079/CPUFriend.kext.zip)
[CPUFriendDataProvider.kext.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6014080/CPUFriendDataProvider.kext.zip)
<img width="800" alt="QQ20210220-115320@2x" src="https://user-images.githubusercontent.com/61744850/108583083-41a91c80-7372-11eb-8f1c-a32ae3fc8d74.png">
<img width="397" alt="QQ20210220-114936@2x" src="https://user-images.githubusercontent.com/61744850/108583087-440b7680-7372-11eb-8137-7ac1fefe4b4a.png">

**Comment by ferstar** [comment]
@Hush-vv 哈哈, 我就是这样弄的, 而且其实不需要替换`SSDT-PLUG-_SB.PR00`, 改型号加CPUFriend及Data就可以

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/108600631-13a7f480-73d3-11eb-89b8-aa72345a2541.png)

MacbookPro16.2 + CPUFriend  + CPUFriendDataProvider

**Comment by Hush-vv** [comment]
> @Hush-vv 哈哈, 我就是这样弄的, 而且其实不需要替换`SSDT-PLUG-_SB.PR00`, 改型号加CPUFriend及Data就可以

我的要3个一起配合使用，否则变频效果不理想。

**Comment by ferstar** [comment]
> > @Hush-vv 哈哈, 我就是这样弄的, 而且其实不需要替换`SSDT-PLUG-_SB.PR00`, 改型号加CPUFriend及Data就可以
> 
> 我的要3个一起配合使用，否则变频效果不理想。

我`SSDT-PLUG-_SB.PR00.aml`没你的那么复杂

```aml
/*
 * Intel ACPI Component Architecture
 * AML/ASL+ Disassembler version 20200925 (64-bit version)
 * Copyright (c) 2000 - 2020 Intel Corporation
 * 
 * Disassembling to symbolic ASL+ operators
 *
 * Disassembly of iASLdIXRWA.aml, Mon Feb 22 10:45:13 2021
 *
 * Original Table Header:
 *     Signature        "SSDT"
 *     Length           0x000000A6 (166)
 *     Revision         0x02
 *     Checksum         0x82
 *     OEM ID           "ACDT"
 *     OEM Table ID     "CpuPlug"
 *     OEM Revision     0x00003000 (12288)
 *     Compiler ID      "INTL"
 *     Compiler Version 0x20190703 (538511107)
 */
DefinitionBlock ("", "SSDT", 2, "ACDT", "CpuPlug", 0x00003000)
{
    External (_SB_.PR00, ProcessorObj)

    Scope (_SB.PR00)
    {
        Method (DTGP, 5, NotSerialized)
        {
            If ((Arg0 == ToUUID ("a0b5b7c6-1318-441c-b0c9-fe695eaf949b") /* Unknown UUID */))
            {
                If ((Arg1 == One))
                {
                    If ((Arg2 == Zero))
                    {
                        Arg4 = Buffer (One)
                            {
                                 0x03                                             // .
                            }
                        Return (One)
                    }

                    If ((Arg2 == One))
                    {
                        Return (One)
                    }
                }
            }

            Arg4 = Buffer (One)
                {
                     0x00                                             // .
                }
            Return (Zero)
        }

        Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
        {
            Local0 = Package (0x02)
                {
                    "plugin-type", 
                    One
                }
            DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
            Return (Local0)
        }
    }
}

```

**Comment by Hush-vv** [comment]
> > > @Hush-vv 哈哈, 我就是这样弄的, 而且其实不需要替换`SSDT-PLUG-_SB.PR00`, 改型号加CPUFriend及Data就可以
> > 
> > 
> > 我的要3个一起配合使用，否则变频效果不理想。
> 
> 我`SSDT-PLUG-_SB.PR00.aml`没你的那么复杂, 配上`CPUfriend`就看起来变频已经足够好了
> 
> ```
> /*
>  * Intel ACPI Component Architecture
>  * AML/ASL+ Disassembler version 20200925 (64-bit version)
>  * Copyright (c) 2000 - 2020 Intel Corporation
>  * 
>  * Disassembling to symbolic ASL+ operators
>  *
>  * Disassembly of iASLdIXRWA.aml, Mon Feb 22 10:45:13 2021
>  *
>  * Original Table Header:
>  *     Signature        "SSDT"
>  *     Length           0x000000A6 (166)
>  *     Revision         0x02
>  *     Checksum         0x82
>  *     OEM ID           "ACDT"
>  *     OEM Table ID     "CpuPlug"
>  *     OEM Revision     0x00003000 (12288)
>  *     Compiler ID      "INTL"
>  *     Compiler Version 0x20190703 (538511107)
>  */
> DefinitionBlock ("", "SSDT", 2, "ACDT", "CpuPlug", 0x00003000)
> {
>     External (_SB_.PR00, ProcessorObj)
> 
>     Scope (_SB.PR00)
>     {
>         Method (DTGP, 5, NotSerialized)
>         {
>             If ((Arg0 == ToUUID ("a0b5b7c6-1318-441c-b0c9-fe695eaf949b") /* Unknown UUID */))
>             {
>                 If ((Arg1 == One))
>                 {
>                     If ((Arg2 == Zero))
>                     {
>                         Arg4 = Buffer (One)
>                             {
>                                  0x03                                             // .
>                             }
>                         Return (One)
>                     }
> 
>                     If ((Arg2 == One))
>                     {
>                         Return (One)
>                     }
>                 }
>             }
> 
>             Arg4 = Buffer (One)
>                 {
>                      0x00                                             // .
>                 }
>             Return (Zero)
>         }
> 
>         Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
>         {
>             Local0 = Package (0x02)
>                 {
>                     "plugin-type", 
>                     One
>                 }
>             DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
>             Return (Local0)
>         }
>     }
> }
> ```

因为我的包含了定制HWP的数据

**Comment by ferstar** [comment]
@Hush-vv 我对比了你的定制`SSDT-PLUG-_SB.PR00.aml`, 发现其实并没有多大差异, 在CPUfriend加持下, 定制HWP感觉不是很必要的操作

**Comment by Hush-vv** [comment]
> @Hush-vv 我对比了你的定制`SSDT-PLUG-_SB.PR00.aml`, 发现实际使用其实并没有多大差异, 在CPUfriend加持下, 定制HWP感觉不是很必要的操作
> 
> PS: 附我仅使用CPUfriend的图, `AVG`和`REQ`几乎大都重叠, 变频表现完美
> 
> ![image](https://user-images.githubusercontent.com/2854276/109244402-9c7ec000-7819-11eb-9537-697716e4bcef.png)

呃，看着正常的，不知道你闲置时cpu频率是否可以到0.9G甚至更低。这影响睡眠耗电

**Comment by ferstar** [comment]
> > @Hush-vv 我对比了你的定制`SSDT-PLUG-_SB.PR00.aml`, 发现实际使用其实并没有多大差异, 在CPUfriend加持下, 定制HWP感觉不是很必要的操作
> > PS: 附我仅使用CPUfriend的图, `AVG`和`REQ`几乎大都重叠, 变频表现完美
> > ![image](https://user-images.githubusercontent.com/2854276/109244402-9c7ec000-7819-11eb-9537-697716e4bcef.png)
> 
> 呃，看着正常的，不知道你闲置时cpu频率是否可以到0.9G甚至更低。这影响睡眠耗电

我闲置时CPU频率甚至能到0.3G...睡眠耗电表现优秀, 每小时不到1%
![image](https://user-images.githubusercontent.com/2854276/109363528-bf67ad80-78c7-11eb-819e-a4fdb472edc5.png)

**Comment by bocaikun** [comment]
改型号加CPUFriend及Data后，发现在线播放同一个视频时，CPU功耗变高了，从4w作用变成8w左右
<img width="468" alt="15,3" src="https://user-images.githubusercontent.com/52200860/111195111-41addc80-85ff-11eb-907f-8e7006da62ca.png">
<img width="468" alt="16,2" src="https://user-images.githubusercontent.com/52200860/111195121-45d9fa00-85ff-11eb-9dc0-c84e6ad58aac.png">

**Comment by M69W** [comment]
所以，下次还是去掉 `rps-control` 吧

**Comment by ferstar** [comment]
> 所以，下次还是去掉 `rps-control` 吧

像这种控制参数, 能写就尽量写到`boot-args`里, 也好改

```shell
alcid=11 brcmfx-country=#a igfxrpsc=1 igfxonln=1
```

另外本来`rps-control`的作用作者写的很清楚就是可以提高核显性能的一个参数
> igfxrpsc=1 boot argument (rps-control property) to enable RPS control patch (improves IGPU performance).

**Comment by bocaikun** [comment]
> > 所以，下次还是去掉 `rps-control` 吧
> 
> 像这种控制参数, 能写就尽量写到`boot-args`里, 也好改
> 
> ```shell
> alcid=11 brcmfx-country=#a igfxrpsc=1 igfxonln=1
> ```
> 
> 另外本来`rps-control`的作用作者写的很清楚就是可以提高核显性能的一个参数
> 
> > igfxrpsc=1 boot argument (rps-control property) to enable RPS control patch (improves IGPU performance).
> 
> 还有改型号以及添加 CPUfriend 以后, CPU 调度会变的比较激进, 比如`15,4`没办法单核睿频`4.7GHz`, 而`16,2`或`16,3`却可以, 性能增强的代价就是功耗变高
> 
> 另外还有 macOS 本身的问题, 我同样的 EFI, 退回 Catalina 以后同样负载任务(开若干 Chrome tabs+开个 IDE), 功耗比 BigSur 节省了`1/3~1/2`
> 
> 电池供电情况下, 锁 9W 功耗, Catalina 日用浏览网页搜狗输入法打字几乎无卡顿, 而 BigSur 输入法出字明显延迟, 接外接显示器卡顿更加明显

自从改了机型为`16,2`以及添加CPUfriend以后，风扇转的时间变多了，以前风扇不会转的任务负载下，都会转了。即使保持机型为`16,2`，并停用CPUfriend后，仍是如此。

**Comment by Hush-vv** [comment]
又想马儿跑，又想马儿不吃草，你们想什么呢？高性能提升点功耗正常啊！不满意自己换回air9.1，换SMBIOS又不难

**Comment by bocaikun** [comment]
> 又想马儿跑，又想马儿不吃草，你们想什么呢？高性能提升点功耗正常啊！不满意自己换回air9.1，换SMBIOS又不难

另外，我认为性能的增强是需要高频率时能够提供高频率，这时的高功耗是可以接收的。而不是同样任务下反而需要更高的功耗。

**Comment by Hush-vv** [comment]
建议你买白的

**Comment by M69W** [comment]
自行设置就好，各有所需。

**Comment by ferstar** [comment]
> > > 所以，下次还是去掉 `rps-control` 吧
> > 
> > 
> > 像这种控制参数, 能写就尽量写到`boot-args`里, 也好改
> > ```shell
> > alcid=11 brcmfx-country=#a igfxrpsc=1 igfxonln=1
> > ```
> > 
> > 
> > 另外本来`rps-control`的作用作者写的很清楚就是可以提高核显性能的一个参数
> > > igfxrpsc=1 boot argument (rps-control property) to enable RPS control patch (improves IGPU performance).
> > 
> > 
> > 还有改型号以及添加 CPUfriend 以后, CPU 调度会变的比较激进, 比如`15,4`没办法单核睿频`4.7GHz`, 而`16,2`或`16,3`却可以, 性能增强的代价就是功耗变高
> > 另外还有 macOS 本身的问题, 我同样的 EFI, 退回 Catalina 以后同样负载任务(开若干 Chrome tabs+开个 IDE), 功耗比 BigSur 节省了`1/3~1/2`
> > 电池供电情况下, 锁 9W 功耗, Catalina 日用浏览网页搜狗输入法打字几乎无卡顿, 而 BigSur 输入法出字明显延迟, 接外接显示器卡顿更加明显
> 
> 自从改了机型为`16,2`以及添加CPUfriend以后，风扇转的时间变多了，以前风扇不会转的任务负载下，都会转了。即使保持机型为`16,2`，并停用CPUfriend后，仍是如此。

改机型以后对应 macOS 的 CPU 调度也会跟着调整, 保守/激进的调度方案实际表现差异很大, 所以其实这个没啥好纠结的

**Comment by bocaikun** [comment]
最新的EFI，修改机型为15,4, 并重新用`one-key-cpufriend`定制（低频率模式：`800mhz`，性能模式：`平衡性能模式`）Data文件后，CPU可以睿频到4.7Ghz了。同时测试之前同样的任务，功耗仍为4w左右，暂时未发现问题

<img width="512" alt="截屏2021-03-17 16 05 31" src="https://user-images.githubusercontent.com/52200860/111428976-a1a99d80-873b-11eb-83d8-b2896bba64a6.png">

**Comment by cytown** [comment]
> 最新的EFI，修改机型为15,4, 并重新用`one-key-cpufriend`定制（低频率模式：`800mhz`，性能模式：`平衡性能模式`）Data文件后，CPU可以睿频到4.7Ghz了。同时测试之前同样的任务，功耗仍为4w左右，暂时未发现问题
> 
> <img alt="截屏2021-03-17 16 05 31" width="512" src="https://user-images.githubusercontent.com/52200860/111428976-a1a99d80-873b-11eb-83d8-b2896bba64a6.png">

这个好，我目前也是用的15,4，但其它没有修正，能否发个pr？？？

**Comment by M69W** [comment]
其实就是定制 CPUFriend(Data) 吧

**Comment by ferstar** [comment]
> 其实就是定制 CPUFriend(Data) 吧

改回15,4以后重新订制了CPUFriend，跑分基本无变化，不过类似负载的功耗是低了一些

**Comment by M69W** [comment]
已更新 [v2.3.5](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.3.5)

**Comment by surill** [comment]
> 更换SMBIOS为MacbookPro16.2并替换SSDT-PLUG-_SB.PR00.aml即可

请教：更换aml，并加载了CPUFriend和Date，在Intel Power中使用 CPU test运行Maximum Frequency
core max依然维持在3.9-4.0，core req显示4.7，功率15上下波动
是什么问题，是正常的吗
![截屏2021-04-27 13 07 55](https://user-images.githubusercontent.com/75652673/116188385-e3c1f800-a759-11eb-96ac-9462816267ab.png)

**Comment by surill** [comment]
图一：用回原来的aml，加载CPU Friend和Date
图二：用回原来的aml，不加载CPU Friend和Date
看来是失败了啊……
![截屏2021-04-27 13 20 13](https://user-images.githubusercontent.com/75652673/116190199-c4789a00-a75c-11eb-8303-9b5ad2698ba8.png)
<img width="512" alt="截屏2021-04-27 13 28 20" src="https://user-images.githubusercontent.com/75652673/116190207-c8a4b780-a75c-11eb-905a-800dfdad935b.png">

**Comment by surill** [comment]
@M69W 大佬能帮忙看看吗
<img width="989" alt="截屏2021-04-27 13 44 55" src="https://user-images.githubusercontent.com/75652673/116191375-c6435d00-a75e-11eb-93ac-0cf02f22b240.png">
![截屏2021-04-27 13 44 26](https://user-images.githubusercontent.com/75652673/116191390-c93e4d80-a75e-11eb-8c37-cfa04897e866.png)

**Comment by M69W** [comment]
不是大佬。。。

看上面的讨论，定制一下定制 CPUFriend(Data) 试试

**Comment by surill** [comment]
> 不是大佬。。。
> 
> 看上面的讨论，定制一下定制 CPUFriend(Data) 试试

刚刚一通乱试
用第一个aml配合CPUFriend，可以正常睿频，但是core MIN一直维持在0.9-1
![截屏2021-04-28 17 51 46](https://user-images.githubusercontent.com/75652673/116384613-9bcece00-a84a-11eb-88a8-c1d2e414a1a0.png)

最后用了@Hush-vv的三个文件，刚刚试了一下又可以了……不过测试的时候core max经常会出现锯齿，不能稳定保持4.7，不知道是否正常，先这样吧，感觉已经可以
![截屏2021-04-28 17 51 07](https://user-images.githubusercontent.com/75652673/116384623-9ffaeb80-a84a-11eb-8a93-ce7779130fa9.png)
![截屏2021-04-28 17 50 50](https://user-images.githubusercontent.com/75652673/116384652-a6896300-a84a-11eb-9d96-ae3bc1ccb250.png)

**Comment by ferstar** [comment]
你搞毛啊, kext都没启用
![image](https://user-images.githubusercontent.com/2854276/116393125-d6893400-a853-11eb-83b9-cf7fcf3e7b07.png)

**Comment by surill** [comment]
别激动，我启用了，截图的时候把了关了而已

发自我的iPhone

**Comment by surill** [comment]
> 最新的EFI，修改机型为15,4, 并重新用 `one-key-cpufriend` 定制（低频率模式：`800mhz`，性能模式：`平衡性能模式`）Data文件后，CPU可以睿频到4.7Ghz了。同时测试之前同样的任务(去掉 `rps-control` )，功耗仍为4w左右，暂时未发现问题
> 
> <img alt="截屏2021-03-17 16 05 31" width="512" src="https://user-images.githubusercontent.com/52200860/111428976-a1a99d80-873b-11eb-83d8-b2896bba64a6.png">
> 
> > Geekbench5 跑分
> 
> <img alt="截屏2021-03-17 17 03 51" width="837" src="https://user-images.githubusercontent.com/52200860/111434760-47143f80-8743-11eb-8066-362eaabf5232.png">

老兄，我用15,4+CPU Friend +Date为何到不了4.7
