### ISSUE TITLE
插入外置蓝牙后，内置蓝牙不可用

### ISSUE THREAD

**Issue by nilfei** [daliansky/XiaoXinPro-13-hackintosh#93]
![image](https://user-images.githubusercontent.com/18027182/108388165-5047e480-7249-11eb-8204-eb32fad5506a.png)

dw1820a 网卡，蓝牙

![image](https://user-images.githubusercontent.com/18027182/108388324-7d949280-7249-11eb-9b36-ca8e22602cc0.png)
下面的是内置的1820A 上面的是免驱外置蓝牙

求大佬要怎么解决这个问题

**Comment by stevezhengshiqi** [comment]
苹果系统不支持双蓝牙同时工作，如果想使用外置蓝牙，请先重新配置 `USBMap.kext` 来禁用内置蓝牙。

**Comment by nilfei** [comment]
> 苹果系统不支持双蓝牙同时工作，如果想使用外置蓝牙，请先重新配置 `USBMap.kext` 来禁用内置蓝牙。

如何恢复默认的蓝牙呢

**Comment by stevezhengshiqi** [comment]
拔掉外置蓝牙

**Comment by nilfei** [comment]
> 拔掉外置蓝牙

拔掉之后，内置蓝牙是关闭状态，无法启动

**Comment by nilfei** [comment]
![image](https://user-images.githubusercontent.com/18027182/108595139-37f6d780-73b9-11eb-8d3f-0f8613ba6475.png)
打开后无法连接
打开偏好设置后，出现如下图
![image](https://user-images.githubusercontent.com/18027182/108595126-30cfc980-73b9-11eb-89c8-8ad25586476a.png)

**Comment by nilfei** [comment]
![image](https://user-images.githubusercontent.com/18027182/108597213-cf145d00-73c2-11eb-8e0d-c76d839a8421.png)
