### ISSUE TITLE
2.3.4 no suitable signature - security violation

### ISSUE THREAD

**Issue by Hscpro** [daliansky/XiaoXinPro-13-hackintosh#95]
![image](https://user-images.githubusercontent.com/13926044/108798409-b9708480-75c8-11eb-9cb8-c08089b83008.png)
 更新2.3.4后OS无法引导系统

**Comment by Hscpro** [comment]
SecureBootModel  设为  Disabled 后正常

**Comment by M69W** [comment]
这个设置主要是针对15.x系统用AX200/AX201 [网卡的设置](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E9%A9%B1%E5%8A%A8%E5%86%85%E7%BD%AE%E8%8B%B1%E7%89%B9%E5%B0%94%E6%97%A0%E7%BA%BF%E7%BD%91%E5%8D%A1), 
下次还是改为Disabled，
只要能安装、能进系统都好说。

**Comment by M69W** [comment]
这个设置主要是针对15.x系统用AX200/AX201 [网卡的设置](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/%E9%A9%B1%E5%8A%A8%E5%86%85%E7%BD%AE%E8%8B%B1%E7%89%B9%E5%B0%94%E6%97%A0%E7%BA%BF%E7%BD%91%E5%8D%A1), 
下次还是改为Disabled，
只要能安装、能进系统都好说。
