### ISSUE TITLE
替换最新的OC.0.6.7.-PRO13，进入引导后无法开机

### ISSUE THREAD

**Issue by anledehai** [daliansky/XiaoXinPro-13-hackintosh#96]
系统版本：11.1
OC固件包：EFI-OC.0.6.7.-PRO13_no_network_.driver_20210223.zip
现象：替换后，关机时出现代码行很快消失，成功关机。
第一次开机，进入oc引导，选择MAC启动，刷过代码行然后正常开机，此时关机
第二次开机，进入oc引导，选择MAC启动，刷过代码行无法开机，看起来像是acpi错误，具体没拍照片留证，急着工作便将备份的原OC替换回去，成功开机。

**Comment by yanxu117** [comment]
我更新之后也是无法开机，后来切换回原来的efi也不行了，试了几次发现好像是网卡的问题，于是我把后盖打开，把网卡拔出来重新装一遍，用原来的efi就好了，新的不敢用了。

**Comment by sowhat4999** [comment]
我使用新的EFI没有问题，网卡是免驱的。

**Comment by M69W** [comment]
> 系统版本：11.1
> OC固件包：EFI-OC.0.6.7.-PRO13_no_network_.driver_20210223.zip
> 现象：替换后，关机时出现代码行很快消失，成功关机。
> 第一次开机，进入oc引导，选择MAC启动，刷过代码行然后正常开机，此时关机
> 第二次开机，进入oc引导，选择MAC启动，刷过代码行无法开机，看起来像是acpi错误，具体没拍照片留证，急着工作便将备份的原OC替换回去，成功开机。

最近改的ACPI 有 这个 `SSDT-BATS-PRO13.aml`，但不确定是不是这个导致的。
我那边能正常在线更新系统，，但没有全新安装过。

**Comment by anledehai** [comment]
> > 系统版本：11.1
> > OC固件包：EFI-OC.0.6.7.-PRO13_no_network_.driver_20210223.zip
> > 现象：替换后，关机时出现代码行很快消失，成功关机。
> > 第一次开机，进入oc引导，选择MAC启动，刷过代码行然后正常开机，此时关机
> > 第二次开机，进入oc引导，选择MAC启动，刷过代码行无法开机，看起来像是acpi错误，具体没拍照片留证，急着工作便将备份的原OC替换回去，成功开机。
> 
> 最近改的ACPI 有 这个 `SSDT-BATS-PRO13.aml`，但不确定是不是这个导致的。
> 我那边能正常在线更新系统，，但没有全新安装过。

![QQ图片20210301193815](https://user-images.githubusercontent.com/38025570/109494017-484d3780-7ac8-11eb-8ac8-8687e19816ba.jpg)
今天又重试了下，替换OC和BOOT后重启第二次便会报错，我是2020版的I5 不知道是不是有关系

**Comment by M69W** [comment]
再次重启试试？

最近也发现这个问题
再次重启正常进入系统

**Comment by anledehai** [comment]
> 再次重启试试？
> 
> 最近也发现这个问题
> 再次重启正常进入系统

重启多次依旧是在这里

**Comment by ClayMoreBoy** [comment]
不行就rest nvram 基本万能

**Comment by M69W** [comment]
试试 [v2.3.5](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.3.5)

**Comment by anledehai** [comment]
> 试试 [v2.3.5](https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases/tag/v2.3.5)

今天刚替换好，目前可以正常进系统了，开机进系统后要刷串代码，不过最终还是能进去了

**Comment by M69W** [comment]
可以去掉 `-v`
