### ISSUE TITLE
贡献一组可能解决花屏/闪屏问题的显卡ID

### ISSUE THREAD

**Issue by ferstar** [daliansky/XiaoXinPro-13-hackintosh#97]
| AAPL,ig-platform-id | device-id | 备注                   |
| ------------------- | --------- | ---------------------- |
| 0500A53E            | A53E0000  | 解决i7-10710u花屏/闪屏 |

**Comment by M69W** [comment]
感谢，已更新至 [Wiki/HiDPi](https://github.com/daliansky/XiaoXinPro-13-hackintosh/wiki/HiDPi)

**Comment by surill** [comment]
请问是直接用文本编辑在config文件中添加吗，我因为开启HIDPI出现花屏，添加了id之后重启进入系统，分辨率变成了2560*1600，没有其他选项。

<key>AAPL,ig-platform-id</key>
				<data>BQCmPg==</data>
				<key>device-id</key>

实在上面两个id的后面直接加“:0500A53E”、":A53E0000"吗？？？

**Comment by ferstar** [comment]
> 请问是直接用文本编辑在config文件中添加吗，我因为开启HIDPI出现花屏，添加了id之后重启进入系统，分辨率变成了2560*1600，没有其他选项。
> 
> AAPL,ig-platform-id
> BQCmPg==
> device-id
> 
> 实在上面两个id的后面直接加“:0500A53E”、":A53E0000"吗？？？

谁给你的勇气用纯文本编辑器编辑config?

**Comment by M69W** [comment]
可以，只不过要知道对应的设置
```
<data>这里的data值都是转义的</data>
```
