### ISSUE TITLE
语言设置 prev-lang:kbd 默认是俄语

### ISSUE THREAD

**Issue by ClayMoreBoy** [daliansky/XiaoXinPro-13-hackintosh#99]
prev-lang:kbd = 7a682d48616e733a323532 (zh-Hans:252)
[config.zip](https://github.com/daliansky/XiaoXinPro-13-hackintosh/files/6095314/config.zip)

https://opencore.slowgeek.com/?file=laptopicelake066mV1Z61&rs=laptopicelake066

**Comment by M69W** [comment]
下次更新会设置该设置为中文
